format_version = 1

[[top]]
name = "Roar Ljøkelsøy"
pos = 1
score = 1515
time = "Wed 31 Dec 2003  3:11"

[[top]]
name = "Roar Ljøkelsøy"
pos = 1
score = 1343
time = "Wed 31 Dec 2003  3:11"

[[top]]
name = "Sigurd Pettersen"
pos = 2
score = 1212
time = "Wed 31 Dec 2003  3:11"

[[top]]
name = "Janne Ahonen"
pos = 3
score = 1101
time = "Wed 31 Dec 2003  3:11"

[[top]]
name = "Adam Malysz"
pos = 4
score = 999
time = "Wed 31 Dec 2003  3:11"

[[top]]
name = "Tami Kiuru"
pos = 5
score = 888
time = "Wed 31 Dec 2003  3:11"

[[top]]
name = "Martin Höllwarth"
pos = 6
score = 777
time = "Wed 31 Dec 2003  3:11"

[[top]]
name = "Sven Hannawald"
pos = 7
score = 665
time = "Wed 31 Dec 2003  3:11"

[[top]]
name = "Veli-Matti Lindström"
pos = 8
score = 555
time = "Wed 31 Dec 2003  3:11"

[[top]]
name = "Matti Hautamäki"
pos = 10
score = 494
time = "Wed 31 Dec 2003  3:11"

[[top]]
name = "Michael Uhrmann"
pos = 12
score = 444
time = "Wed 31 Dec 2003  3:11"

[[top]]
name = "Thomas Morgenstern"
pos = 14
score = 383
time = "Wed 31 Dec 2003  3:11"

[[top]]
name = "Peter Zonta"
pos = 16
score = 333
time = "Wed 31 Dec 2003  3:11"

[[top]]
name = "Maximilian Mechler"
pos = 18
score = 272
time = "Wed 31 Dec 2003  3:11"

[[top]]
name = "Andreas Goldberger"
pos = 20
score = 222
time = "Wed 31 Dec 2003  3:11"

[[top]]
name = "Rok Benkovic"
pos = 22
score = 161
time = "Wed 31 Dec 2003  3:11"

[[top]]
name = "Martin Schmitt"
pos = 25
score = 111
time = "Wed 31 Dec 2003  3:11"

[[top]]
name = "Andreas Küttel"
pos = 30
score = 77
time = "Wed 31 Dec 2003  3:11"

[[top]]
name = "Reinhard Schwarzenberger"
pos = 35
score = 33
time = "Wed 31 Dec 2003  3:11"

[[top]]
name = "Marcin Bachleda"
pos = 40
score = 11
time = "Wed 31 Dec 2003  3:11"

[[top]]
name = "Germany"
pos = 1
score = 42
time = "Wed 31 Dec 2003  3:11"

[[top]]
name = "Austria"
pos = 2
score = 35
time = "Wed 31 Dec 2003  3:11"

[[top]]
name = "Finland"
pos = 3
score = 28
time = "Wed 31 Dec 2003  3:11"

[[top]]
name = "Japan"
pos = 4
score = 21
time = "Wed 31 Dec 2003  3:11"

[[top]]
name = "Norway"
pos = 5
score = 17
time = "Wed 31 Dec 2003  3:11"

[[top]]
name = "Poland"
pos = 6
score = 11
time = "Wed 31 Dec 2003  3:11"

[[top]]
name = "Slovenia"
pos = 7
score = 8
time = "Wed 31 Dec 2003  3:11"

[[top]]
name = "Switzerland/Czech Rep."
pos = 8
score = 5
time = "Wed 31 Dec 2003  3:11"

[[top]]
name = "Russia"
pos = 9
score = 3
time = "Wed 31 Dec 2003  3:11"

[[top]]
name = "Finland II"
pos = 10
score = 1
time = "Wed 31 Dec 2003  3:11"

[[top]]
name = "Roar Ljøkelsøy"
pos = 1
score = 1011.1
time = "Wed 31 Dec 2003  3:11"

[[top]]
name = "Janne Ahonen"
pos = 3
score = 987.6
time = "Wed 31 Dec 2003  3:11"

[[top]]
name = "Martin Höllwarth"
pos = 6
score = 944.9
time = "Wed 31 Dec 2003  3:11"

[[top]]
name = "Matti Hautamäki"
pos = 10
score = 901.0
time = "Wed 31 Dec 2003  3:11"

[[top]]
name = "Tommy Ingebrigtsen"
pos = 15
score = 832.1
time = "Wed 31 Dec 2003  3:11"

[[top]]
name = "Not Completed"
pos = 0
score = 0
time = "Wed 31 Dec 2003  3:11"

[[top]]
name = "Not Completed"
pos = 0
score = 0
time = "Wed 31 Dec 2003  3:11"

[[top]]
name = "Not Completed"
pos = 0
score = 0
time = "Wed 31 Dec 2003  3:11"

[[top]]
name = "Not Completed"
pos = 0
score = 0
time = "Wed 31 Dec 2003  3:11"

[[top]]
name = "Not Completed"
pos = 0
score = 0
time = "Wed 31 Dec 2003  3:11"

[[top]]
name = "Not Completed"
pos = 0
score = 0
time = "Wed 31 Dec 2003  3:11"
[hill_records]
"original:A" = { name = "Martin Höllwarth", len = 128.0, time = "Wed 31 Dec 2003  3:11" }
"original:B" = { name = "Janne Ahonen", len = 96.0, time = "Wed 31 Dec 2003  3:11" }
"original:C" = { name = "Adam Malysz", len = 186.0, time = "Wed 31 Dec 2003  3:11" }
"original:D" = { name = "Adam Malysz", len = 122.0, time = "Wed 31 Dec 2003  3:11" }
"original:E" = { name = "Janne Ahonen", len = 128.0, time = "Wed 31 Dec 2003  3:11" }
"original:F" = { name = "Sigurd Pettersen", len = 101.0, time = "Wed 31 Dec 2003  3:11" }
"original:G" = { name = "Sigurd Pettersen", len = 128.0, time = "Wed 31 Dec 2003  3:11" }
"original:H" = { name = "Sven Hannawald", len = 96.0, time = "Wed 31 Dec 2003  3:11" }
"original:I" = { name = "Matti Hautamäki", len = 122.0, time = "Wed 31 Dec 2003  3:11" }
"original:J" = { name = "Noriaki Kasai", len = 122.0, time = "Wed 31 Dec 2003  3:11" }
"original:K" = { name = "Noriaki Kasai", len = 117.0, time = "Wed 31 Dec 2003  3:11" }
"original:L" = { name = "Martin Höllwarth", len = 128.0, time = "Wed 31 Dec 2003  3:11" }
"original:M" = { name = "Matti Hautamäki", len = 191.0, time = "Wed 31 Dec 2003  3:11" }
"original:N" = { name = "Janne Ahonen", len = 119.0, time = "Wed 31 Dec 2003  3:11" }
"original:O" = { name = "Martin Höllwarth", len = 74.0, time = "Wed 31 Dec 2003  3:11" }
"original:P" = { name = "Sven Hannawald", len = 128.0, time = "Wed 31 Dec 2003  3:11" }
"original:Q" = { name = "Michael Uhrmann", len = 96.0, time = "Wed 31 Dec 2003  3:11" }
"original:R" = { name = "Martin Höllwarth", len = 128.0, time = "Wed 31 Dec 2003  3:11" }
"original:S" = { name = "Roar Ljøkelsøy", len = 197.0, time = "Wed 31 Dec 2003  3:11" }
"original:T" = { name = "Sven Hannawald", len = 123.0, time = "Wed 31 Dec 2003  3:11" }
