format_version = 1

[[top]]
name = "Roar Ljøkelsøyÿ"
pos = 1
score = 1515
time = "Wed 31 Dec 2003  3:11"

[[top]]
name = "Roar Ljøkelsøyÿ"
pos = 1
score = 1343
time = "Wed 31 Dec 2003  3:11"

[[top]]
name = "Sigurd Pettersenÿ"
pos = 2
score = 1212
time = "Wed 31 Dec 2003  3:11"

[[top]]
name = "Janne Ahonenÿ"
pos = 3
score = 1101
time = "Wed 31 Dec 2003  3:11"

[[top]]
name = "Adam Malyszÿ"
pos = 4
score = 999
time = "Wed 31 Dec 2003  3:11"

[[top]]
name = "Tami Kiuruÿ"
pos = 5
score = 888
time = "Wed 31 Dec 2003  3:11"

[[top]]
name = "Martin Höllwarthÿ"
pos = 6
score = 777
time = "Wed 31 Dec 2003  3:11"

[[top]]
name = "Sven Hannawaldÿ"
pos = 7
score = 665
time = "Wed 31 Dec 2003  3:11"

[[top]]
name = "Veli-Matti Lindströmÿ"
pos = 8
score = 555
time = "Wed 31 Dec 2003  3:11"

[[top]]
name = "Matti Hautamäkiÿ"
pos = 10
score = 494
time = "Wed 31 Dec 2003  3:11"

[[top]]
name = "Michael Uhrmannÿ"
pos = 12
score = 444
time = "Wed 31 Dec 2003  3:11"

[[top]]
name = "Thomas Morgensternÿ"
pos = 14
score = 383
time = "Wed 31 Dec 2003  3:11"

[[top]]
name = "Peter Zontaÿ"
pos = 16
score = 333
time = "Wed 31 Dec 2003  3:11"

[[top]]
name = "Maximilian Mechlerÿ"
pos = 18
score = 272
time = "Wed 31 Dec 2003  3:11"

[[top]]
name = "Andreas Goldbergerÿ"
pos = 20
score = 222
time = "Wed 31 Dec 2003  3:11"

[[top]]
name = "Rok Benkovicÿ"
pos = 22
score = 161
time = "Wed 31 Dec 2003  3:11"

[[top]]
name = "Martin Schmittÿ"
pos = 25
score = 111
time = "Wed 31 Dec 2003  3:11"

[[top]]
name = "Andreas Küttelÿ"
pos = 30
score = 77
time = "Wed 31 Dec 2003  3:11"

[[top]]
name = "Reinhard Schwarzenbergerÿ"
pos = 35
score = 33
time = "Wed 31 Dec 2003  3:11"

[[top]]
name = "Marcin Bachledaÿ"
pos = 40
score = 11
time = "Wed 31 Dec 2003  3:11"

[[top]]
name = "Germanyÿ"
pos = 1
score = 42
time = "Wed 31 Dec 2003  3:11"

[[top]]
name = "Austriaÿ"
pos = 2
score = 35
time = "Wed 31 Dec 2003  3:11"

[[top]]
name = "Finlandÿ"
pos = 3
score = 28
time = "Wed 31 Dec 2003  3:11"

[[top]]
name = "Japanÿ"
pos = 4
score = 21
time = "Wed 31 Dec 2003  3:11"

[[top]]
name = "Norwayÿ"
pos = 5
score = 17
time = "Wed 31 Dec 2003  3:11"

[[top]]
name = "Polandÿ"
pos = 6
score = 11
time = "Wed 31 Dec 2003  3:11"

[[top]]
name = "Sloveniaÿ"
pos = 7
score = 8
time = "Wed 31 Dec 2003  3:11"

[[top]]
name = "Switzerland/Czech Rep.ÿ"
pos = 8
score = 5
time = "Wed 31 Dec 2003  3:11"

[[top]]
name = "Russiaÿ"
pos = 9
score = 3
time = "Wed 31 Dec 2003  3:11"

[[top]]
name = "Finland IIÿ"
pos = 10
score = 1
time = "Wed 31 Dec 2003  3:11"

[[top]]
name = "Roar Ljøkelsøyÿ"
pos = 1
score = 10111
time = "Wed 31 Dec 2003  3:11"

[[top]]
name = "Janne Ahonenÿ"
pos = 3
score = 9876
time = "Wed 31 Dec 2003  3:11"

[[top]]
name = "Martin Höllwarthÿ"
pos = 6
score = 9449
time = "Wed 31 Dec 2003  3:11"

[[top]]
name = "Matti Hautamäkiÿ"
pos = 10
score = 9010
time = "Wed 31 Dec 2003  3:11"

[[top]]
name = "Tommy Ingebrigtsenÿ"
pos = 15
score = 8321
time = "Wed 31 Dec 2003  3:11"

[[top]]
name = "Not Completed"
pos = 0
score = 0
time = "Wed 31 Dec 2003  3:11"

[[top]]
name = "Not Completed"
pos = 0
score = 0
time = "Wed 31 Dec 2003  3:11"

[[top]]
name = "Not Completed"
pos = 0
score = 0
time = "Wed 31 Dec 2003  3:11"

[[top]]
name = "Not Completed"
pos = 0
score = 0
time = "Wed 31 Dec 2003  3:11"

[[top]]
name = "Not Completed"
pos = 0
score = 0
time = "Wed 31 Dec 2003  3:11"

[[top]]
name = "Not Completed"
pos = 0
score = 0
time = "Wed 31 Dec 2003  3:11"

[[hill_records]]
name = "Martin Höllwarthÿ"
len = 1280
time = "Wed 31 Dec 2003  3:11"

[[hill_records]]
name = "Janne Ahonenÿ"
len = 960
time = "Wed 31 Dec 2003  3:11"

[[hill_records]]
name = "Adam Malyszÿ"
len = 1860
time = "Wed 31 Dec 2003  3:11"

[[hill_records]]
name = "Adam Malyszÿ"
len = 1220
time = "Wed 31 Dec 2003  3:11"

[[hill_records]]
name = "Janne Ahonenÿ"
len = 1280
time = "Wed 31 Dec 2003  3:11"

[[hill_records]]
name = "Sigurd Pettersenÿ"
len = 1010
time = "Wed 31 Dec 2003  3:11"

[[hill_records]]
name = "Sigurd Pettersenÿ"
len = 1280
time = "Wed 31 Dec 2003  3:11"

[[hill_records]]
name = "Sven Hannawaldÿ"
len = 960
time = "Wed 31 Dec 2003  3:11"

[[hill_records]]
name = "Matti Hautamäkiÿ"
len = 1220
time = "Wed 31 Dec 2003  3:11"

[[hill_records]]
name = "Noriaki Kasaiÿ"
len = 1220
time = "Wed 31 Dec 2003  3:11"

[[hill_records]]
name = "Noriaki Kasaiÿ"
len = 1170
time = "Wed 31 Dec 2003  3:11"

[[hill_records]]
name = "Martin Höllwarthÿ"
len = 1280
time = "Wed 31 Dec 2003  3:11"

[[hill_records]]
name = "Matti Hautamäkiÿ"
len = 1910
time = "Wed 31 Dec 2003  3:11"

[[hill_records]]
name = "Janne Ahonenÿ"
len = 1190
time = "Wed 31 Dec 2003  3:11"

[[hill_records]]
name = "Martin Höllwarthÿ"
len = 740
time = "Wed 31 Dec 2003  3:11"

[[hill_records]]
name = "Sven Hannawaldÿ"
len = 1280
time = "Wed 31 Dec 2003  3:11"

[[hill_records]]
name = "Michael Uhrmannÿ"
len = 960
time = "Wed 31 Dec 2003  3:11"

[[hill_records]]
name = "Martin Höllwarthÿ"
len = 1280
time = "Wed 31 Dec 2003  3:11"

[[hill_records]]
name = "Roar Ljøkelsøyÿ"
len = 1970
time = "Wed 31 Dec 2003  3:11"

[[hill_records]]
name = "Sven Hannawaldÿ"
len = 1230
time = "Wed 31 Dec 2003  3:11"
