format_version = 1
active_order = [0]

[[profiles]]
name = "SKI JUMPER"
real_name = ""
suit_color = 0
ski_color = 0
replace = 0
coach_style = 1
skip_qualification = 2
total_jumps = 1
world_cups = 0
legs_won = 0
world_cups_won = 0
best_result = "0 (-)"
best_4h_result = "-"
best_wc_jump = 93.0
best_wc_hill_idx = 1
best_jump = 93.0
besthill_idx = 1
best_hill_file = "HILLBASE"
best_points = 0
best_4h_points = 0.0
koth_level = 0
