format_version = 1
active_order = [0, 1]

[[profiles]]
name = "SKI JUMPER"
real_name = ""
suit_color = 0
ski_color = 0
replace = 0
coach_style = 1
skip_quali = 2
total_jumps = 1
world_cups = 0
legs_won = 0
world_cups_won = 0
best_result = "0 (-)"
best_4h_result = "-"
best_wc_jump = 930
bestwchill = 1
best_jump = 930
besthill_idx = 1
besthillfile = "HILLBASE"
bestpoints = 0
best4points = 0
koth_level = 0

[[profiles]]
name = "SKI JUMPER 2"
real_name = ""
suit_color = 0
ski_color = 0
replace = 0
coach_style = 1
skip_quali = 0
total_jumps = 0
world_cups = 0
legs_won = 0
world_cups_won = 0
best_result = "-"
best_4h_result = "-"
best_wc_jump = 0
bestwchill = 0
best_jump = 0
besthill_idx = 0
besthillfile = ""
bestpoints = 0
best4points = 0
koth_level = 0
