id = "cesky"
name = "Cesky"

[strings]
1 = "Jedna"
2 = "Dve"
3 = "Tri"
4 = "Ctyri"
5 = "Pet"
6 = "Ano"
7 = "Ne"
8 = "z"
9 = "Zadny"
11 = "Registrovany"
12 = "Shareware"
13 = "Normalni"
14 = "Nizke"
15 = "Stiskni klavesu ..."
17 = "Hlavni Menu"
18 = "Nabidka skoku"
20 = "Skakej!"
21 = "Zapis skokany"
22 = "Nastaveni"
23 = "Hala slavy"
24 = "Rekordy mustku"
25 = "Zaznam"
26 = "Ukonci SJ3"
27 = "SJ3 Svetovy pohar"
28 = "Vlastni pohar"
29 = "Turne ctyr mustku"
30 = "Teamovy Pohar"
31 = "Kral mustku"
32 = "Trenink"
33 = "Zpet do hl. menu"
34 = "Skokani:"
35 = "Tato verze"
36 = "je registrovana:"
38 = "Toto je neregistrovana"
39 = "Verze SJ3."
40 = "Precti si Readme.txt"
41 = "Stan se nejvetsim frajerem !"
42 = "Zaregistruj se, clovece !"
43 = "Ziskej respekt svych pratel !"
44 = "Zaregistruj se, clovece !"
45 = "Tahle hra neni freeware"
46 = "Proto se rychle zaregistruj."
47 = "V neregistrovane verzi"
48 = "mohou hrat jenom dva hraci"
51 = "Trenink"
52 = "Treninkove kolo"
53 = "Kvalifikacni kolo"
54 = "Prvni kolo"
55 = "Druhe kolo"
56 = "Dalsi na mustku ..."
57 = "Skace pocitac..."
58 = "Startovni branka:"
59 = "Zmackni (N) pro nastaveni"
60 = "N"
61 = "Aktualne"
62 = "K vedeni"
63 = "K vitezstvi"
65 = "Rekord mustku"
67 = "Zbyva skokanu:"
68 = "Potrebujes prekonat:"
69 = "Zrovna posledni:"
70 = "Aktualni vysledky SP"
71 = "Aktualni vysledky TP"
75 = "Zranen na pristi"
76 = "Skoky"
77 = "Kolo"
78 = "Skok"
79 = "je diskvalifikovan!"
81 = "Vysledky - Skok"
82 = "Kvalifikace - Skok"
83 = "ze 4"
84 = "Turne Ctyr Mustku - Skok"
85 = "Konecne vysledky turne ctyr mustku"
86 = "(kompaktni seznam)"
87 = "Vysledky po skoku"
88 = "Skokan"
89 = "Stat. ze Sv. Poharu pro"
90 = "Konecne vysledky z"
91 = "Vysledky Team. Poharu pro skok"
92 = "Konecne vysledky Teamoveho Poharu"
93 = "Stat. z Team. Poharu pro"
94 = "KO system razeni"
95 = "Postaveni"
96 = "Kral mustku"
97 = "Skore"
98 = "SP"
99 = "4 Mustky:"
100 = "Kompletne:"
101 = "Vyrazen ze souteze:"
102 = "Nepostupujici:"
103 = "Neopstupujici skokane:"
104 = "V satnach:"
105 = "Uz nejsou mezi nami:"
106 = "Kde ?"
107 = "Team:"
108 = "Pos"
109 = "Bod"
110 = "TP"
111 = "Pripravte se na Teamovy Pohar"
112 = "Plan pro Teamovy Pohar:"
113 = "Prosim pojmenujte tym"
114 = "Tym"
115 = "Nejlepsi vysledky:"
116 = "Nacti \"Vybrane Mustky\""
117 = "Uloz \"Vybrane Mustky\""
118 = "Vyberte mustky pro vas svet. pohar"
119 = "Pouzij Sipky, ENTER:Zacni, ESC:Ukonci"
120 = "Skokani ovl. pocitacem:"
121 = "Zacni *Kral mustku*"
122 = "vyber uroven obtiznosti"
123 = "vyber protivniky"
124 = "Skakat v"
125 = "Vitr ?"
126 = "Kola ?"
127 = "Zpet do Hl. Menu"
128 = "Novy rekord pro \"Vybrane Mustky\""
129 = "Stary rekord:"
130 = "K.O.T.H Stupen obtiznosti"
131 = "Pro mistry sveta"
132 = "Jses dobry?"
133 = "Pro skoro dobre"
134 = "Pro slabe"
135 = "Domov duchodcu"
136 = "Pro male divenky"
137 = "Volitelny"
138 = "vyber si sve protivniky"
139 = "pouzij sipky k zvoleni obtiznosti"
140 = "ENTER - vyber, ESC - odejdi"
141 = "Jmeno"
142 = "Poradi"
143 = "Kral!"
145 = "Zapis skokany"
146 = "(Pouzij sipky, ENTER, DEL nebo ESC)"
147 = "*Pridej Hrace*"
148 = "Exit"
149 = "Vyber si barvu kombinezy"
150 = "(Pouzij sipky, ENTER nebo ESC)"
151 = "Kde"
152 = "chces skakat"
153 = "dnes ?"
154 = "Konec"
155 = "Nahodny mustek SP"
156 = "Vice mustku..."
157 = "Stranka"
158 = "Dalsi stranka"
159 = "Predchozi stranka"
160 = "Soutez Kral mustku"
161 = "Neni dokoncena"
162 = "Nejlepsi skoky ve \"Volitelnych Mustcich\""
163 = "Top 20 SJ3 Vysledku SP"
164 = "Top 10 Vysledku TP"
165 = "Top 5 Turne Ctyr Mustku"
166 = "Jmeno"
167 = "Pos"
168 = "Body"
169 = "Kdy?"
170 = "Rekord mustku"
171 = "Kdo?"
172 = "Kolik?"
173 = "Soubor"
174 = "Body"
175 = "Nastaveni"
176 = "Obecne nastaveni"
177 = "Nastaveni skoku"
178 = "Nastaveni Hiscore"
180 = "Oh, Ano"
181 = "jiste"
182 = "Ano Pane"
183 = "Jo"
184 = "Jasne"
185 = "Ale Ne"
186 = "Nikdy"
187 = "Negativni"
188 = "Ne"
189 = "Neeee"
190 = "Resetuj"
191 = "Vynuluj"
192 = "Highscore ?"
193 = "Jste si jist?"
194 = "Chystam se vymazat"
195 = "Opust nastaveni"
196 = "Obecne nastaveni"
197 = "Nastaveni skoku"
198 = "HiScore a moznosti nastaveni"
199 = "Nastaveni klaves"
200 = "Nastav cile pro rekordy mustku"
201 = "Editor mustku"
202 = "Manazer mustku"
203 = "Zpet to hlavniho menu"
204 = "Jazyk?"
205 = "Pipnuti?"
206 = "Graficky detail?"
207 = "Soubor se jmeny protivniku (NAMES?.SKI)?"
208 = "Sede polozky jsou dostupne"
209 = "pouze v registrovane verzi"
211 = "Zpet do hlavniho nastaveni"
212 = "Treninkova kola?"
213 = "Extra statistiky?"
214 = "Ukazovat vysledky s diferencemi ?"
215 = "Ukazovat vysledky SP s diferencemi ?"
216 = "Zuzena vysledkova listina?"
217 = "Neviditelne pozadi vysledku?"
218 = "Automaticky ukladat replaye rekordu?"
219 = "Ukaz cile mustku?"
220 = "Kolik protivniku chces sledovat?"
221 = "Urci misto pro Mereni vetru"
222 = "Pouzit KO system v Turne 4 Mustku?"
225 = "Opust Nastaveni Hiscore"
226 = "Maji se zapsat rekordy protivniku?"
227 = "Dovol vice totoznich jmen na seznamu"
228 = "Resetovat Hiscores"
229 = "Nulovovat Hiscores"
230 = "Vratit na zakladni nastaveni"
231 = "Nikdy"
232 = "Ne v T4M"
233 = "Vzdy"
235 = "Vedouci"
236 = "Nejlepsi 3"
237 = "Nejlepsich 5"
238 = "Nejlepsich 10"
239 = "Vsechny!"
240 = "Zadny"
242 = "Ukol"
243 = "Pouzij sipky, ESC:Ukonci"
245 = "Uz odchazis?"
246 = "PRED"
247 = "DALS"
248 = "UKON"
251 = "Takze odchazis..."
252 = "Opravdu chces odejit?"
253 = "Ale, odchazis takhle brzo?"
256 = "Jses si tim uplne jisty?"
257 = "Jses si absolutne jisty?"
258 = "Zmackni A pro konec."
261 = "Ahoj! Musis mit ctyri (4)"
262 = "nebo osm (8) prihlasenych hracu"
263 = "pred startem Teamoveho poharu"
264 = "Jdi rict svym pratelum"
265 = "nebo se proste ctyrikrat naklonuj"
270 = "SJ3 Tvorba Mustku"
271 = "(pouzij sipky, DEL,"
272 = " ENTER nebo ESC)"
273 = "Jmeno souboru"
274 = "Jmeno mustku"
275 = "*Pridej novy mustek*"
276 = "-Konec-"
277 = "-Start-"
278 = "Vyzkousej svuj mustek!"
280 = "Sipka Nahoru"
281 = "Sipka Doleva"
282 = "Sipka Doprava"
283 = "Sipka Dolu"
285 = "(N)ahrat"
286 = "(U)lozit"
287 = "N(A)hodny seznam"
288 = "(S)erad podle SP bodu"
289 = "(S)erad podle Celkovych bodu"
290 = "Nebyli nalezeny zadne zaznamy!"
291 = "Autor:"
292 = "Jmeno:"
293 = "Jmeno souboru:"
294 = "Mustek:"
295 = "Konec, neukladat"
296 = "Konec, a ulozit"
298 = "(U)loz zaznam"
300 = "Skokani"
301 = "Zvol skokany"
302 = "*Vytvor noveho skokana*"
304 = "Jmeno:"
305 = "Skutecne Jm."
306 = "Barva obleku:"
307 = "Barva lyzi:"
308 = "Vymen:"
309 = "Trener:"
310 = "Preskoc Q."
311 = "Resetuj skokana"
312 = "Konec"
313 = "Skoku celkove:"
314 = "Dokonceno Svetovych Poharu:"
315 = "Kol vyhrano:"
316 = "Svetovych vyhrano:"
317 = "Nej. vysledek SP:"
318 = "Nej. vysledek v T4M:"
319 = "Nejdelsi SP skok:"
320 = "Nejdelsi skok:"
321 = "KOTH uroven:"
322 = "(Pouzik sipky,"
323 = "ENTER upravi skokana,"
324 = "DEL odstrani z poradi)"
325 = "ENTER zapise,"
326 = "DEL vymaze skokana)"
328 = "Vymazani skokana"
329 = "Zresetovani skokana"
330 = "Nastaveni klaves"
331 = "Odraz"
332 = "Dopredu"
333 = "Dozadu"
334 = "Telemark"
335 = "Pristani na obe nohy"
336 = "Vratit zakladni nastaveni"
337 = "Odejit"
340 = "Cas skoku"
341 = "Delka skoku"
342 = "Rychlost:"
343 = "Volitelne"
345 = "jiz existuje."
346 = "Prepsat?"
350 = "Zaznam byl ulozen."
351 = "Zaznam nebyl ulozen."
352 = "Volitelne nastaveni bylo ulozeno."
353 = "Volitelne nastaveni nebylo ulozeno."
354 = "Extra mustek byl ulozen."
355 = "Extra mustek nebyl ulozen."
356 = "Nebyly nalezeny zadne volitelne nastaveni!"
360 = "Vitejte do SJ3 a sveta skoku na lyzich."
361 = "Toto je rychly uvod do hry."
362 = "Cilem tohoto sportu je doletet co"
363 = "nejdale a dobre pristat."
364 = "Vas skokan sedi na lavicce na zacatku"
365 = "najezdu. Pouzijte sipku Doprava na rozjezd."
366 = "Meric vetru je umisten na levem spodnim rohu obrazovky."
367 = "Protivitr je lepsi protoze zvysuje vztlak."
368 = "Klicem k dobremu skoku je vcas se odrazit."
369 = "To provedete sipkou Nahoru."
370 = "Ted by jste meli skokana natocit co nejvice doprava"
371 = "pro snizeni odporu vetru. Pouzijte sipku Doprava."
372 = "Nekdy se stane ze vas vzdusny vir vyhodi z"
373 = "rovnovahy. Na opravu pouzijte sipku Doleva."
374 = "Jak se zacne blizit zem bylo by moudre pripravit"
375 = "se na hladke pristani."
376 = "Klavesa T provede Telemark. Je pomalejsi a nebezpecny"
377 = "ale toto se vam vrati v bodech za styl."
378 = "Klavesa R provede doskok na obe nohy, je bezpecny a"
379 = "nejvice by se mel pouzivat u velmi dlouhych skoku."
380 = "A to je vsechno ! Navod si muzete znovu prohlednout"
381 = "z menu Zaznam. Manual je obsazen v souboru manual.txt."
390 = "Horni"
391 = "Stredni"
392 = "Dolni"
393 = "Levy"
394 = "Stredni"
395 = "Pravy"
396 = "Skokan"
400 = "Treneruv nazor:"
401 = "Profesional"
402 = "Jsi moc zakloneny."
403 = "Dobra letova pozice."
404 = "Moc se naklanis dopredu."
405 = "Priste prosimte pristan."
406 = "Zacni drive pristavat."
407 = "Aaale, to byl smula."
410 = "To je ale spatny skok."
411 = "Stale to jeste nevypada dobre."
412 = "Tenhle skok by uz docela sel."
413 = "Dobry skok."
414 = "Vyborny skok!"
415 = "Neuveritelne!  Kdes nechal plast?"
418 = "Odraz se daleko drive."
419 = "Moc pozde jsi se odrazil."
420 = "Hmm, stale se odrazis spatne."
421 = "Priste to lip nacasuj."
422 = "Skvele nacasovany odraz!"
423 = "Odrazil ses moc brzy."
424 = "Neodrazej se tak brzo."
425 = "Tak to je byl opravdu spatny odraz. Odraz se mnohem pozdeji."
428 = "Hmm, myslel jsem to o dost driv."
429 = "Tentokrat to bylo moc pozde."
430 = "Hmm, odraz uz byl skoro v poradku."
431 = "Odraz byl v poradku."
432 = "To by mohly byt slusne body za styl."
433 = "Na pristani jeste bylo dost casu."
434 = "Neboj se letet dal."
435 = "Priste stiskni 'T' nebo 'R', ok?."
441 = "Pohodar"
442 = "Ee, nepretacej se, chlape."
443 = "Letova pozice je v pohode."
444 = "Neboj se vic naklonit, synku."
445 = "Sakra to musi bolet, priste zkus pristat."
446 = "Porad pristavas na drzce, chlapce."
447 = "Sakra smula, chlape."
450 = "To bylo az moc pohodarsky."
451 = "Aby ses nezapotil."
452 = "Uz to zacina vypadat dobre."
453 = "Tak tomuhle ja rikam dobrej let."
454 = "Super, tohle zensky zerou!"
455 = "To je husty! Nepotkals tam Supermana?"
458 = "Pekne debilni odraz!"
459 = "Jestli chces letet, odraz se driv."
460 = "Nacasovani stoji pekne za backoru."
461 = "Tentokrat to byl dobrej odraz."
462 = "Hej, takovejhle odraz zeru!"
463 = "Ted ses odrazil jen o chvili driv nez mel."
464 = "Nespechej s tim odrazem."
465 = "Ooo, takhle si jednou rozbijes drzku."
468 = "Na tom pristani by si mel asi zamakat."
469 = "To se nebojis ze umres??."
470 = "No fuj, to pristani bylo dost na hrane."
471 = "Pristani - Stabilni jak skala."
472 = "Joo, Pan mekky dopad je tady nekde."
473 = "Jestes mel dost casu na pristani."
474 = "Priste se neposer a let dal."
475 = "Neboj se klavesnice, chlape."
481 = "Striktni"
482 = "Moc se naklanis, panaku."
483 = "To je slusna letova pozice."
484 = "Srabe! Skakej jako chlap!"
485 = "Muj boze! Kam se podelo pristani?"
486 = "Ale ne! Zacni pristavat vcas."
487 = "Zvedni prdel a zpatky do prace!"
490 = "Tohle je nejhorsi skok co jsem kdy videl."
491 = "Moje matka skace lip nez ty!"
492 = "Neco se stalo? Chces zpatky k mamince?"
493 = "Furt mas jeste rezervu."
494 = "Nektery trenery by s tim byli spokojeni."
495 = "Konecne skok jak jsem te ucil."
498 = "Strasny! Kde je ten zatracenej odraz?"
499 = "Zase ses spatne odrazil! 50 kliku!"
500 = "Stale mas spatne nacasovani! 25 kliku!"
501 = "Mohl by ses driv odrazit?"
502 = "Ted ses odrazil jak jsem chtel."
503 = "Moc brzo! Ty se to asi nikdy nenaucis?"
504 = "Katastrofalni odraz! 50 kliku!"
505 = "Jeste jsem nevidel horsi odraz. Radsi jdi domu."
508 = "To je to pristani tak tezke, mazanku?"
509 = "Ne! Zacni pristavat vcas!"
510 = "To bylo moc riskatni pristani."
511 = "To uz skoro vypadalo jako pristani."
512 = "Myslim si ze tohle pristani bylo v poradku."
513 = "Nespechej na to pristani."
514 = "Ceho se bojis? Let, xakru!"
515 = "Ses debilni? Let,nebo se vrat domu!"
520 = "Load Cup"
521 = "Save cup state?"
522 = "Current jump is lost."
523 = "No saved cups"
