id = "deutsch"
name = "Deutsch"

[strings]
1 = "Eins"
2 = "Zwei"
3 = "Drei"
4 = "Vier"
5 = "Fünf"
6 = "Ja"
7 = "Nein"
8 = "von"
9 = "Keine"
11 = "Registriert"
12 = "Shareware"
13 = "Normal"
14 = "Niedrig"
15 = "Taste drücken..."
17 = "Hauptmenu"
18 = "Wettkampf"
20 = "Auf geht's!"
21 = "Teilnehmer"
22 = "Einstellungen"
23 = "Ruhmeshalle"
24 = "Schanzenrekorde"
25 = "Aufzeichnungen"
26 = "SJ3 Beenden"
27 = "SJ3 Weltcup"
28 = "Eigener Weltcup"
29 = "4Schanzen Tournee"
30 = "Teamcup"
31 = "King of the Hill"
32 = "Üben"
33 = "Zum Hauptmenu"
34 = "Springer:"
35 = "Diese Version"
36 = "ist registriert von:"
38 = "Nicht registrierte"
39 = "Version von SJ3."
40 = "Lies jetzt Deutsch.Txt!"
41 = "Sei der cleverste Junge"
42 = "in der Nachbarschaft,"
43 = "Verschaffe dir Respekt"
44 = "Laß dich registrieren!"
45 = "Dieses Spiel ist keine FREEWARE."
46 = "Mach es richtig, bezahle deinen Spaß."
47 = "Nur zwei Spieler in der"
48 = "nicht registrierten Version"
51 = "Vorbereitung"
52 = "Training"
53 = "Qualifikation"
54 = "1. Durchgang"
55 = "2. Durchgang"
56 = "Nächster..."
57 = "Gegner Springen..."
58 = "Startgate:"
59 = "(E) für Einstellungen"
60 = "E"
61 = "Im Moment"
62 = "Zur Führung"
63 = "Zum Sieg"
65 = "Schanzenrekord"
67 = "Noch:"
68 = "Zu Schlagen:"
69 = "Letzter im Moment:"
70 = "WC Reihenfolge"
71 = "TC Reihenfolge"
75 = "Ausfall:"
76 = "Springen"
77 = "Durchgang"
78 = "Springen"
79 = "ist disqualifiziert!"
81 = "Ergebnis - Springen"
82 = "Quali - Springen"
83 = "von 4"
84 = "Tournee - Springen"
85 = "Endergebnis der Tournee"
86 = "(gekürzte Liste)"
87 = "Plazierung nach Durchgang"
88 = "Springer"
89 = "Weltcup Statistik von"
90 = "Endergebnis von"
91 = "Teamcup Ergebnis nach Springen"
92 = "Endergebnis Teamcup"
93 = "Teamcup Statistik für"
94 = "K.O.-Modus Paarungen"
95 = "Ergebnis"
96 = "King of the Hill"
97 = "Pkt"
98 = "WC"
99 = "Tour:"
100 = "Gesamt:"
101 = "Ausgeschieden:"
102 = "Nicht mehr dabei:"
103 = "Ausgeschiedene Springer:"
104 = "Bereits beim Duschen:"
105 = "Nicht mehr dabei:"
106 = "Wo?"
107 = "Team:"
108 = "Pos"
109 = "Pkt"
110 = "TC"
111 = "Auf zum Team Cup"
112 = "Team Cup Wettkämpfe:"
113 = "Team Name"
114 = "Team"
115 = "Bestes Ergebnis:"
116 = "Eigenen Weltcup laden"
117 = "Eigenen Weltcup speicher"
118 = "Wähle Schanzen für den eigenen Weltcup"
119 = "Pfeiltasten, EINGABE startet, ESC Ende"
120 = "Computer Springer:"
121 = "Start *King of the Hill*"
122 = "Wähle Wettbewerb"
123 = "Wähle Gegner"
124 = "Schanze?"
125 = "Wind?"
126 = "Runden?"
127 = "Zurück zum Hauptmenu"
128 = "Rekord für eigenen Weltcup!"
129 = "Alter Rekord:"
130 = "K.O.T.H Wettbewerbe"
131 = "ABSOLUTE WELTKLASSE"
132 = "DIE PROFIS"
133 = "TALENTSCHUPPEN"
134 = "HOBBYRUNDE"
135 = "SENIORENHEIM"
136 = "KINDERGARTEN"
137 = "Eigener Wettbewerb"
138 = "Wähle deine Gegner"
139 = "Benutze die Pfeiltasten"
140 = "EINGABE wählen, ESC beenden"
141 = "Name"
142 = "Rang"
143 = "Der King!"
146 = "(Pfeiltasten, EINGABE, ENTF oder ESC)"
150 = "(Pfeiltasten, EINGABE oder ESC)"
151 = "Wo willst"
152 = "du heute"
153 = "Springen?"
154 = "Ende"
155 = "Zufällig"
156 = "Mehr Schanzen..."
157 = "Seite"
158 = "Nächste Seite"
159 = "Vorherige Seite"
160 = "King of the Hill Wettbewerbe"
161 = "Noch nicht beendet"
162 = "Gespeicherte Bestenliste"
163 = "Top 20 SJ3 Weltcup Ergebnisse"
164 = "Top 10 Teamcup Ergebnisse"
165 = "Top 5 Tournee Punkte"
166 = "Name"
167 = "Pos"
168 = "Pkt"
169 = "Wann?"
170 = "Die Schanzenrekorde"
171 = "Wer?"
172 = "Wie weit?"
173 = "Datei"
174 = "Pkte"
175 = "Optionen Hauptmenu"
176 = "Allgemeine Optionen"
177 = "Wettkampf Optionen"
178 = "Bestenlisten Optionen"
180 = "Oh Ja"
181 = "Sicher"
182 = "Jawoll"
183 = "Ach Ja"
184 = "Na ja"
185 = "Oh Nein"
186 = "Niemals"
187 = "Nicht doch"
188 = "Ach Nein"
189 = "Nee"
190 = "Zurücksetzen"
191 = "Löschen"
192 = "der Bestenlisten?"
193 = "Bist du sicher?"
194 = "About to delete"
195 = "Optionen beenden"
196 = "Allgemeine Optionen"
197 = "Wettkampf Optionen"
198 = "Bestenlisten Optionen"
199 = "Tasten anpassen"
200 = "Setze Rekordziel"
201 = "Schanzen Editor"
203 = "Zum Optionen Hauptmenu"
204 = "Sprache?"
205 = "Töne?"
206 = "Grafik Detail?"
207 = "Computerspringer Namen (NAMES?.SKI)?"
208 = "Graue Optionen nur in"
209 = "der registrierten Version"
211 = "Zum Optionen Hauptmenu"
212 = "Trainingssprünge?"
213 = "Extra Statistiken?"
214 = "Ergebnisse als Differenzen?"
215 = "WC Ergebnisse als Differenzen?"
216 = "Gekürzte Ergebnisliste?"
217 = "Kein Ergebnislisten Hintergrundbild?"
218 = "Schanzenrekord automatisch aufzeichnen?"
219 = "Rekordziele anzeigen?"
220 = "Auswahl zu sehender Gegner"
221 = "Position Windmesser"
222 = "K.O.-Modus 4 Schanzen Tournee?"
225 = "Ende Bestenlisten Optionen"
226 = "Schanzenrekorde durch Computerspringer?"
227 = "Gleiche Namen mehrmals in der Bestenliste?"
228 = "Bestenlisten zurücksetzen"
229 = "Bestenlisten löschen"
230 = "Standard wiederherstellen"
231 = "Nie"
232 = "Tournee Nein"
233 = "Immer"
235 = "Führender"
236 = "Top 3"
237 = "Top 5"
238 = "Top 10"
239 = "Alle!"
240 = "Keiner"
242 = "Ziel"
243 = "Pfeiltasten, ESC Ende"
245 = "Schon aufhören?"
246 = "<-<-"
247 = "->->"
248 = "ENDE"
251 = "Da geht er hin..."
252 = "Willst du wirklich aufhören?"
253 = "Oh, jetzt schon aufhören?"
256 = "Möchtest du wirklich aufhören?"
257 = "Bist du wirklich sicher?"
258 = "Drücke J zum beenden."
261 = "Achtung! Du musst vier (4)"
262 = "oder acht (8) Teilnehmer haben"
263 = "um den Teamcup zu starten!"
264 = "Hole deine Freunde zum mitspielen"
265 = "oder starte selbst viermal."
270 = "SJ3 Schanzen Editor"
271 = "(Pfeiltasten, ENTF,"
272 = " EINGABE oder ESC)"
273 = "Dateiname"
274 = "Schanzenname"
275 = "*Neue Schanze*"
276 = "-Ende-"
277 = "-Start-"
278 = "Schanze testen!"
280 = "Pfeil Oben"
281 = "Pfeil Links"
282 = "Pfeil Rechts"
283 = "Pfeil Unten"
285 = "(L)ade"
286 = "(S)peichern"
287 = "(Z)ufalls"
288 = "S(O)rtiert n. WC Punkten"
289 = "S(O)rtiert n. Ges.Punkten"
290 = "Keine Aufzeichnungen!"
291 = "Autor:"
292 = "Name:"
293 = "Dateiname:"
294 = "Schanze:"
295 = "Ende, OHNE Speichern"
296 = "Ende und Speichern"
298 = "(S)peichern"
300 = "Springer"
301 = "Auswahl Springer"
302 = "*Neuer Springer*"
304 = "Name:"
305 = "Name real:"
306 = "Anzugsfarbe:"
307 = "Skifarbe:"
308 = "Ersetzt:"
309 = "Trainer:"
310 = "KeineQuali:"
311 = "Springer zurücksetzen"
312 = "Ende"
313 = "Anzahl Sprünge:"
314 = "Weltcups beendet:"
315 = "Siege:"
316 = "Weltcup Siege:"
317 = "Bester Weltcup:"
318 = "Beste 4Schanzen:"
319 = "Weitester WC Sprung:"
320 = "Weitester Sprung:"
321 = "K.O.T.H level:"
322 = "(Pfeiltasten,"
323 = "ENTER bearbeiten,"
324 = "ENTF entfernen)"
325 = "ENTER einsteigen,"
326 = "ENTF löschen)"
328 = "Springer löschen"
329 = "Springer zurücksetzen"
330 = "Tasten"
331 = "Abspringen"
332 = "Tiefer gehen"
333 = "Höher gehen"
334 = "Telemark Landung"
335 = "Haferl Landing"
336 = "Vorgabewerte"
337 = "Ende"
340 = "Hangtime"
341 = "Länge"
342 = "Geschwindigkeit:"
343 = "Custom"
345 = "bereits vorhanden"
346 = "überschreiben?"
350 = "Aufzeichnung gespeichert."
351 = "Aufzeichnung nicht gespeichert."
352 = "Eigene Auswahl gespeichert."
353 = "Eigene Auswahl nicht gespeichert."
354 = "Neue Schanze gespeichert."
355 = "Neue Schanze nicht gespeichert."
356 = "Keine eigene Auswahl!"
360 = "Willkommen zum Skispringen mit SJ3."
361 = "Sie sehen eine kurze Anleitung zum Spiel."
362 = "Die Idee beim Skispringen ist es, möglichst"
363 = "weit zu fliegen und dann ohne Sturz zu landen."
364 = "Zu Beginn des Versuchs sitzt ihr Springer auf"
365 = "dem Balken. Der Anlauf beginnt mit 'Pfeil rechts'."
366 = "Den Windmesser sehen sie unten links. Gegenwind (-)"
367 = "ist besser, da die Sprungkurve höher wird."
368 = "Der richtige Moment für den Absprung ist der"
369 = "Schlüssel zum Erfolg. Benutzen Sie 'Pfeil nach oben'."
370 = "Nun müssen sie mit 'Pfeil rechts' in die Vorlage gehen"
371 = " um den Luftwiderstand zu reduzieren."
372 = "Manchmal zwingen Windstösse zu Korrekturen der"
373 = "Vorlage mit 'Pfeil links' bzw. 'Pfeil rechts'."
374 = "Wenn der Boden näher kommt, ist es Zeit"
375 = "sich Gedanken über die Landung zu machen."
376 = "Die 'T'-Taste steht für die Telemarklandung. Sie ist"
377 = "schwieriger, bringt aber bessere Haltungsnoten."
378 = "Die 'R'-Taste beginnt die parallele Landung,"
379 = "die vor allem bei grossen Weiten sicherer ist."
380 = "Das wars! Diesen Sprung finden sie bei AUFZEICHNUNGEN."
381 = "Weitere Hinweise finden sie in MANUAL.TXT."
390 = "Oben"
391 = "Mitte"
392 = "Unten"
393 = "Links"
394 = "Mitte"
395 = "Rechts"
396 = "Springer"
400 = "Trainers Stimme:"
401 = "Professional"
402 = "Deine Flughaltung darf nicht zu flach werden."
403 = "Gute Haltung im Flug."
404 = "Deine Flughaltung ist zu aufrecht."
405 = "Versuche das nächste Mal zu landen."
406 = "Beginne die Landung früher."
407 = "Ah, das war diesmal Pech."
410 = "Das Sprung war schlecht."
411 = "Der Sprung war noch nicht gut."
412 = "Das war ein mässiger Sprung."
413 = "Das war ein guter Sprung."
414 = "Ein hervorragender Sprung!"
415 = "Unglaublich! Woher hattest du den Aufwind?"
418 = "Beginne den Absprung viel früher."
419 = "Der Absprung war zu spät."
420 = "Der Absprung war immer noch etwas spät."
421 = "Guter Absprung dieses Mal."
422 = "Ein perfekter Absprung!"
423 = "Ein bisschen zu früh im Absprung."
424 = "Beginne den Absprung etwas später."
425 = "Schlechter Absprung! Viel später."
428 = "Ich meine viel früher."
429 = "Die Landung war zu spät."
430 = "Die Landung war fast zu spät."
431 = "Gute Landung."
432 = "Sehr schön. Das gibt Punkte."
433 = "Die Landung war etwas früh."
434 = "Keine Angst weiter zu fliegen."
435 = "Bitte 'T' or 'R' Taste benutzen."
441 = "Locker"
442 = "Hei, du liegst auf dem Ski!"
443 = "Nur Fliegen ist schöner."
444 = "Keine Angst Junge, leg dich vor."
445 = "Landen! Sonst tut es weh."
446 = "Du landest ja immer noch auf der Nase."
447 = "Na ja, man kann nicht jeden landen."
450 = "Das war zu lasch."
451 = "Jetzt bist du fast ins Schwitzen gekommen."
452 = "Das sah schon wie Springen aus."
453 = "Ah, das nenne ich Springen."
454 = "So liebe ich das!"
455 = "Wahnsinn! Das war ja Superman!"
458 = "Ganz schön verschlafen, was..."
459 = "Zum Fliegen gehört ein Absprung."
460 = "Der Absprung war nicht der Beste."
461 = "Eh Mann, der kam gut vom Tisch."
462 = "Was ein Absprung!"
463 = "Einen Tick zu früh im Absprung."
464 = "Lass dir Zeit beim Absprung."
465 = "Oh, irgendwann verletzt du dich dabei."
468 = "Wir sollten an der Landung arbeiten."
469 = "Bist du lebensmüde?..."
470 = "Das war knapp bei der Landung."
471 = "Die Landung - Bombenfest."
472 = "Aber Hallo. Herr Telemark persönlich."
473 = "Landen kann man auch später noch..."
474 = "Probiere es doch mal mit Fliegen."
475 = "Keine Angst vor der Tastatur."
481 = "Streng"
482 = "Du bist zu flach, Mann."
483 = "Die Haltung war ganz nett."
484 = "Feigling, spring wie ein Mann."
485 = "Oh Gott! Wo war die Landung?"
486 = "Nein! Beginne die Landung rechtzeitig!"
487 = "Steh auf und mach dich von der Schanze!"
490 = "Ich sah nie einen schlechteren Sprung."
491 = "Meine Mutter springt besser."
492 = "Was ist los? Willst du nicht?"
493 = "Das kannst du besser."
494 = "Manche Trainer wären jetzt zufrieden."
495 = "Ja, so habe ich es dich gelehrt."
498 = "Schrecklich! Wo war der Absprung!"
499 = "Der Absprung ist zu spät. 50 Kniebeugen!"
500 = "Immer noch zu spät. 25 Kniebeugen!"
501 = "Kannst du nicht etwas besser abspringen?"
502 = "So will ich den Absprung sehen."
503 = "Zu früh! Lernst du das den nie?"
504 = "Katastrophal! 50 Kniebeugen!"
505 = "Die schlechteste Landung aller Zeiten."
508 = "Ist Landen zu schwer für dich?"
509 = "Lande rechtzeitig!"
510 = "Die Landung war zu riskant."
511 = "Das sah fast wie eine Landung aus."
512 = "Die Landung war in Ordnung."
513 = "Sie bei der Landung nicht so feige."
514 = "Wovor fürchtest du dich? Flieg endlich!"
515 = "Was soll das? Lande oder lass es!"
520 = "Load Cup"
521 = "Save cup state?"
522 = "Current jump is lost. (Y/N)"
523 = "No saved cups"
