id = "english"
name = "English"

[strings]
1 = "One"
2 = "Two"
3 = "Three"
4 = "Four"
5 = "Five"
6 = "Yes"
7 = "No"
8 = "of"
9 = "None"
11 = "Registered"
12 = "Shareware"
13 = "Normal"
14 = "Low"
15 = "Press a key..."
17 = "Main Menu"
18 = "Jump Menu"
20 = "Jump!"
21 = "Jumpers"
22 = "Setup Menu"
23 = "Hall of Fame"
24 = "Hill records"
25 = "Replays"
26 = "Exit SJ3"
27 = "SJ3 World Cup"
28 = "Custom World Cup"
29 = "Four Hills Tour"
30 = "Team Cup"
31 = "King of the Hill"
32 = "Practise"
33 = "Back to Main Menu"
34 = "Jumpers:"
35 = "This version"
36 = "is registered to:"
38 = "This is an Unregistered"
39 = "version of SJ3."
40 = "Read Register.Txt"
41 = "On how to be the coolest"
42 = "cat in your neighborhood,"
43 = "Want to gain respect among"
44 = "your friends?  Register, man!"
45 = "Support the cause."
46 = "Do the right thing, register."
47 = "Only Two Players allowed"
48 = "in this Unregistered version!"
51 = "Practise"
52 = "Training Round"
53 = "Qualifying Round"
54 = "Round 1"
55 = "Round 2"
56 = "Next Up..."
57 = "Computers Jumping..."
58 = "Startgate:"
59 = "Press (S) for Setup Menu"
60 = "S"
61 = "At The Moment"
62 = "Need for Lead"
63 = "Need for Win"
65 = "Hill record"
67 = "Jumpers Left:"
68 = "Need to Beat:"
69 = "Currently Last:"
70 = "Current WC Standings"
71 = "Current TC Standings"
75 = "Misses Next"
76 = "Legs"
77 = "Round"
78 = "Leg"
79 = "is Disqualified!"
81 = "Scoreboard - Leg"
82 = "Qualifying - Leg"
83 = "of 4"
84 = "Four Hills Tour - Leg"
85 = "Final Results of the Four Hills Tour"
86 = "(compact listing)"
87 = "Rankings after Leg"
88 = "Jumper"
89 = "World Cup Stats for"
90 = "Final Results of the"
91 = "Team Cup Standings after Leg"
92 = "Final Results of the Team Cup"
93 = "Team Cup Stats for"
94 = "Knock-out system pairs"
95 = "Standings"
96 = "King of the Hill"
97 = "Score"
98 = "WC"
99 = "4hills:"
100 = "Total:"
101 = "Out of the Competition:"
102 = "No Longer Jumping:"
103 = "Eliminated Jumpers:"
104 = "In the Locker Rooms:"
105 = "No Longer Among Us:"
106 = "Where?"
107 = "Team:"
108 = "Pos"
109 = "Pts"
110 = "TC"
111 = "Get Ready for the Team Cup"
112 = "Team Cup Schedule:"
113 = "Please Name Team"
114 = "Team"
115 = "Best Result:"
116 = "Load Custom Hill Set"
117 = "Save Custom Hill Set"
118 = "Select Hills for Your Custom World Cup"
119 = "Use Arrows, ENTER starts, ESC exits"
120 = "Computer Jumpers:"
121 = "Begin *King of the Hill*"
122 = "Select Challenge Level"
123 = "Choose Opponents"
124 = "Jumping at"
125 = "Wind?"
126 = "Rounds?"
127 = "Back To Main Menu"
128 = "New Custom Set Record!"
129 = "Old Record:"
130 = "K.O.T.H Challenge Level"
131 = "THE ULTIMATE CHALLENGE"
132 = "TOUGH COOKIES"
133 = "VARIATION OFFENSE"
134 = "TOTALLY BEATABLE"
135 = "THE OLD FOLKS HOME"
136 = "LITTLE GIRLS IN PINK DRESSES"
137 = "CUSTOM"
138 = "Select Your Opponents"
139 = "Use Arrows to Select Level"
140 = "ENTER chooses, ESC exits"
141 = "Name"
142 = "Rank"
143 = "Da King!"
146 = "(Use arrows, ENTER, DEL or ESC)"
150 = "(Use arrows, ENTER or ESC)"
151 = "Where Do You"
152 = "Want To Jump"
153 = "Today?"
154 = "Exit"
155 = "Random WC Hill"
156 = "More Hills..."
157 = "Page"
158 = "Next Page"
159 = "Previous Page"
160 = "King of the Hill Challenges"
161 = "Not Completed"
162 = "Saved Custom Hill Bests"
163 = "Top 20 SJ3 World Cup Results"
164 = "Top 10 Team Cup Results"
165 = "Top 5 4Hills Tour Scores"
166 = "Name"
167 = "Pos"
168 = "Points"
169 = "When?"
170 = "Da Hill recordz"
171 = "Who?"
172 = "How Much?"
173 = "File"
174 = "Pts"
175 = "Das Setup Main Menu"
176 = "These Are General Options"
177 = "Some Options Concerning Jumping"
178 = "Some Hiscoring Options"
180 = "Oh Yes"
181 = "Sure"
182 = "Yes Sir"
183 = "Yep"
184 = "Yea"
185 = "Oh No"
186 = "No Way"
187 = "Negative"
188 = "Nope"
189 = "Naah"
190 = "Reset"
191 = "Zero"
192 = "the Hiscores?"
193 = "Are You Sure?"
194 = "About to delete"
195 = "Exit Setup"
196 = "General Options"
197 = "Jumping Options"
198 = "Hiscore and Setup Options"
199 = "Customize Keys"
200 = "Set Hill Record Goals"
201 = "Hill Maker"
203 = "Back to Setup.Main"
204 = "Language?"
205 = "Beeps?"
206 = "Graphics Detail Level?"
207 = "Computer Opponent Nameset (NAMES?.SKI)?"
208 = "The items in gray are only"
209 = "available in the Registered version"
211 = "Return to Main Setup"
212 = "Training Rounds?"
213 = "Extra Statistics?"
214 = "Show Scoreboards with Differentials?"
215 = "Show WC Standings with Differentials?"
216 = "Compact Scoreboards?"
217 = "Invisible Scoreboard Backgrounds?"
218 = "Automatically Save Hill Record Replays?"
219 = "Draw Hill Record Goals?"
220 = "Select Viewed Computer Jumpers?"
221 = "Select Windmeter Place"
222 = "Use Knock-out-system in Four Hills?"
225 = "Exit Hiscore Setup"
226 = "Can Computer Jumpers Jump Hill Records?"
227 = "Allow Many Identical Names on the List"
228 = "Reset Hiscores"
229 = "Zero Hiscores"
230 = "Return Default Setup Values"
231 = "Never"
232 = "Not in 4H"
233 = "Always"
235 = "Leader"
236 = "Top 3"
237 = "Top 5"
238 = "Top 10"
239 = "All!"
240 = "None"
242 = "Goal"
243 = "Use arrows, ESC exits"
245 = "Leaving already?"
246 = "PREV"
247 = "NEXT"
248 = "DONE"
251 = "So you are leaving..."
252 = "Do you really want to quit?"
253 = "Oh, leaving this soon?"
256 = "Are you sure about this?"
257 = "Are you absolutely sure?"
258 = "Say Y to quit this now."
261 = "Ahoy! You must have four (4)"
262 = "or eight (8) players signed up"
263 = "before entering the Team Cup!"
264 = "Go and ask your friends to join"
265 = "or just clone yourself four times."
270 = "SJ3 Hill Maker"
271 = "(use arrows, DEL,"
272 = " ENTER or ESC)"
273 = "Filename"
274 = "Hillname"
275 = "*Add New Hill*"
276 = "-Exit-"
277 = "-Start-"
278 = "Test Your Hill!"
280 = "Arrow Up"
281 = "Arrow Left"
282 = "Arrow Right"
283 = "Arrow Down"
285 = "(L)oad set"
286 = "(S)ave set"
287 = "(R)andom set"
288 = "S(O)rt by WC Points"
289 = "S(O)rt by Total Points"
290 = "No Replays Found!"
291 = "Author:"
292 = "Name:"
293 = "Filename:"
294 = "Hill:"
295 = "Exit, Don't save"
296 = "Exit and Save"
298 = "(S)ave Replay"
300 = "Jumpers"
301 = "Select Jumpers"
302 = "*Create New Jumper*"
304 = "Name:"
305 = "Real name:"
306 = "Suit Color:"
307 = "Ski Color:"
308 = "Replace:"
309 = "Coach:"
310 = "Skip Quali:"
311 = "Reset Jumper"
312 = "Exit"
313 = "Total Jumps:"
314 = "World Cups Completed:"
315 = "Legs won:"
316 = "World Cups won:"
317 = "Best WC Result:"
318 = "Best 4Hills:"
319 = "Longest WC Jump:"
320 = "Longest Jump:"
321 = "KOTH level:"
322 = "(Use arrows,"
323 = "ENTER edits jumper,"
324 = "DEL removes from order)"
325 = "ENTER signs up,"
326 = "DEL deletes jumper)"
328 = "Delete jumper"
329 = "Resetting jumper"
330 = "Keymap"
331 = "Take-off"
332 = "Rotate forward"
333 = "Rotate backward"
334 = "Telemark landing"
335 = "Two-footed landing"
336 = "Return Defaults"
337 = "Exit"
340 = "Hangtime"
341 = "Length"
342 = "Speed:"
343 = "Custom"
345 = "already exists."
346 = "Write over?"
350 = "Replay file was saved ok."
351 = "Replay file wasn't saved."
352 = "Custom set was saved ok."
353 = "Custom set wasn't saved."
354 = "Extra hill saved ok."
355 = "Extra hill wasn't saved."
356 = "No Custom Sets Found!"
360 = "Welcome to SJ3 and the sport of ski jumping."
361 = "Here is a quick introduction to the game."
362 = "The idea in this sport is to fly as far"
363 = "as possible and perform a safe landing."
364 = "Your jumper sits on a beam at the beginning of"
365 = "the in-run.  Use Arrow Right to start sliding."
366 = "The wind meter is located at the bottom left. Head"
367 = "wind (negative) is better as it increases lift."
368 = "The key to a successful jump is the timing of the"
369 = "take-off.  Use Arrow Up to start the take-off."
370 = "Now you should rotate the jumper forward to"
371 = "decrease wind-resistance.  Use Arrow Right."
372 = "Sometimes a gust of wind might throw you out of"
373 = "balance.  Use Arrow Left to fix your position."
374 = "As the earth is approaching it would be wise to"
375 = "start thinking about landing your jumper safely."
376 = "The 'T' key begins the Telemark landing.  It's"
377 = "slower and more unsafe but rewarded in style points."
378 = "The 'R' key begins the safer Two-footed landing,"
379 = "it is safer and good for long jumps."
380 = "That's it! You can see this intro again from the"
381 = "Replays menu and for more info, read MANUAL.TXT."
390 = "Top"
391 = "Middle"
392 = "Bottom"
393 = "Left"
394 = "Center"
395 = "Right"
396 = "Jumper"
400 = "Coach's Corner:"
401 = "Professional"
402 = "Try not to let the flight position get that low."
403 = "Good position in flight."
404 = "Your flight position is too upright."
405 = "Make a landing next time."
406 = "Start the landing earlier."
407 = "Uuh, bad luck on that one."
410 = "That's lousy jumping."
411 = "It's still not looking great."
412 = "That's a fairly good jump."
413 = "Good jumping."
414 = "Excellent jump!"
415 = "Unbelievable!  Where's your cape?"
418 = "Start the take-off much earlier."
419 = "The take-off was too late."
420 = "The timing is still a bit late."
421 = "Better timing this time."
422 = "Perfect timing on the take-off!"
423 = "You we're a bit too early with the take-off."
424 = "Don't start the take-off that early."
425 = "That's an awful take-off. Start it a lot later."
428 = "I mean a lot earlier."
429 = "It was just too late this time."
430 = "The landing was barely in time."
431 = "Ok timing on the landing."
432 = "That should give good style points."
433 = "You could've waited more before landing."
434 = "Don't be afraid to fly longer."
435 = "Press the 'T' or 'R' key, please."
441 = "Relaxed"
442 = "Aw, don't over-rotate the jump, man."
443 = "That's a sweet flight position."
444 = "Don't be afraid to lean forward more, son."
445 = "Please land next time, that's painful."
446 = "You're still landing on your face, boy."
447 = "Well, you can't stand them all, u know."
450 = "That's too relaxed."
451 = "Yeah, try not to break a sweat."
452 = "That looks a bit more like it now."
453 = "Now that's what I call nice flying."
454 = "Oh yeah, the chicks are gonna love that!"
455 = "That's huge! I'd like you to meet Superman!"
458 = "What a lazy-ass take-off..."
459 = "If you want to fly, take-off earlier."
460 = "Your timing isn't all that great."
461 = "Pretty good timing off the table, man."
462 = "Hey, I just loved your take-off!"
463 = "The take-off was just a bit early."
464 = "Don't hurry with the take-off."
465 = "Ooh, you're gonna hurt yourself someday."
468 = "You should probably work on that landing."
469 = "Aren't you afraid you're gonna die?.."
470 = "Whew, that landing was just on the edge."
471 = "Landing - Solid as a Rok."
472 = "Ooh, Mr. Smooth Landing is in town."
473 = "Don't rush that landing feeling..."
474 = "Don't chicken out on the fly thing."
475 = "Don't fear the keyboard, dude."
481 = "Strict"
482 = "You're too forward in flight, dummy."
483 = "That's a decent flight position."
484 = "Wimp! Rotate the jump like a man."
485 = "Oh God! Where's your landing?"
486 = "No! Start the damn landing on time!"
487 = "Get off your ass and back to work!"
490 = "I've never seen worse jumping."
491 = "My mother jumps better than that."
492 = "What's wrong? Want to go home to Mommy?"
493 = "You can do a lot better."
494 = "Some coaches would be happy with that."
495 = "Now you're jumping like I told you."
498 = "Terrible! Where's the damn take-off!"
499 = "Take-off's late again. 50 push-ups!"
500 = "Your timing is still bad. 25 push-ups!"
501 = "Can't you take-off a bit earlier?"
502 = "Now the take-off was what I wanted."
503 = "Too early!  Can't you learn?"
504 = "Catastrofic take-off! Gimme 50 push-ups!"
505 = "I've never seen a worse take-off. Go home."
508 = "Is landing too hard, mama's boy?"
509 = "No! Start the damn landing in time!"
510 = "That landing is too risky."
511 = "That almost looked like a landing."
512 = "I guess that was an ok landing."
513 = "Don't wimp out on the landing."
514 = "What are you afraid of? Fly, damn it!"
515 = "Are you stupid? Land or go home!"
520 = "Load Cup"
521 = "Save cup state?"
522 = "Current jump is lost. (Y/N)"
523 = "No saved cups"
