id = "estonian"
name = "Estonian"

[strings]
1 = "üks"
2 = "Kaks"
3 = "Kolm"
4 = "Neli"
5 = "Viis"
6 = "Ja"
7 = "Ei"
8 = "-"
9 = "ei"
11 = "Registreeritud"
12 = "Vabavara"
13 = "Normaalne"
14 = "Madal"
15 = "Vajuta nuppu..."
17 = "Pea Menüü"
18 = "Hüppe Menüü"
20 = "Hüppa!"
21 = "Hüppajate nimed"
22 = "seaded"
23 = "Kuulsuste palee"
24 = "Mäegede rekordid"
25 = "Kordused"
26 = "Välju SJ3'st"
27 = "MK turnee"
28 = "Ise valitud MK"
29 = "4 Hüppemäe Turnee"
30 = "Meeskondlik MK"
31 = "Mägede Kuningas"
32 = "Harjutamine"
33 = "Tagasi"
34 = "Hüppajad:"
35 = "See versioon"
36 = "on registreeritud:"
38 = "See on registreerimata"
39 = "versioon!"
40 = "Loe Register.Txt'ti KOHE!"
41 = "Kuidas olla k6ige ägedam"
42 = "kass oma naabruskonnas,"
43 = "Kuidas saada endale tunnustust"
44 = "s6prade seas?  Registreeri, kutt!"
45 = "See ei ole vabavara mäng."
46 = "Tee 6ieti, registreeri."
47 = "Ainult kaks mängijat on lubatud"
48 = "registreerimata versioonis"
51 = "Harjuta"
52 = "Treening hüpe"
53 = "Qualifikatsiooni voor"
54 = "I voor"
55 = "II voor"
56 = "Valmistub..."
57 = "Arvuti hüpped..."
58 = "Stardipoom:"
59 = "Vajuta (S) Seadete menüü jaoks"
60 = "S"
61 = "Momendil"
62 = "vajad koha säilitamiseks"
63 = "vajad, et v6ita"
65 = "Mäerekord"
67 = "Hüppajaid jäänud:"
68 = "Vaja, et lüüa:"
69 = "Käesoleval hetkel viimane:"
70 = "Praegune MK seis"
71 = "Praegune Meeskondliku MK seis"
75 = "Jääb vahele järgmine"
76 = "etappi"
77 = "voor"
78 = "etapp"
79 = "diskvalifitseeritud!"
81 = "Punktitabel - etapp"
82 = "Qualifikatsioon - etapp"
83 = "neljast"
84 = "Nelja Hüppemäe Turnee - Etapp"
85 = "L6pp tulemused Nelja Hüppemäe Turneel"
86 = "(kompaktne nimekiri)"
87 = "Tulemused pärast eelmist etappi"
88 = "Hüppaja"
89 = "Maailmakarika turnee statistika"
90 = "L6pp tulemused"
91 = "meeskondlikud tulemused pärast etappi"
92 = "l6pptulemused meeskondlikus arvestuses"
93 = "meeskondlik statistika"
94 = "Knock-out system pairs"
95 = "järjestus"
96 = "Mäe kuningas"
97 = "Punkt"
98 = "MK"
99 = "4mäge:"
100 = "kokku:"
101 = "v6istlusetel väljas:"
102 = "enam ei hüppa:"
103 = "k6rbenud hüppajd:"
104 = "riietuvad:"
105 = "enam ei ole meiega:"
106 = "kus?"
107 = "meeskond:"
108 = "Pos"
109 = "Pun."
110 = "TC"
111 = "valmistuge v6istluseks"
112 = "turnee plaan:"
113 = "palun nimeta meeskond"
114 = "Meeskond"
115 = "Parim tulemus:"
116 = "Lae oma mägede järjestus"
117 = "salvesta oma mägede järjestus"
118 = "vali mäed alustamaks MK'd"
119 = "Kasuta nooli, ENTER alustab, ESC väljub"
120 = "vastased:"
121 = "Alusta *Mäe kuningat*"
122 = "Vali Raskus"
123 = "Vali Vastased"
124 = "Hüppamine:"
125 = "Tuul?"
126 = "Voorud?"
127 = "Tagasi"
128 = "Uus oma mägede järjestuse rekord!"
129 = "Vana Rekord:"
130 = "M.k raskus:"
131 = "Viimasepeal klemmid"
132 = "rasked küpsetised"
133 = "NOrmaalsed klemmid"
134 = "Täielikult löödavad"
135 = "vanadekodu"
136 = "väikesed tüdrukud"
137 = "tagasi"
138 = "vali oma vastased"
139 = "kasuta nooli, tainas!!!"
140 = "ENTER valib, ESC väljub"
141 = "Nimi"
142 = "Koht"
143 = "kunn!!!"
146 = "(Kasut. nooli, ENTER, DEL v6i ESC)"
150 = "(Use arrows, ENTER or ESC)"
151 = "Kus sa tahad"
152 = "hüpata"
153 = "Täna?"
154 = "Välju"
155 = "erinev MK"
156 = "Veel mägesid..."
157 = "leht"
158 = "Järgmine leht"
159 = "eelmine leht"
160 = "Mägede kuningas"
161 = "L6petamata"
162 = "Salvestatud Oma Mäe parimad"
163 = "Top 20 SJ3 MK tulemused"
164 = "Top 10 Meeskondlikud tulemused"
165 = "Top 5 4mäe punktid"
166 = "Nimi"
167 = "Pos"
168 = "Punkt."
169 = "millal?"
170 = "Mäerekordid"
171 = "Kes?"
172 = "Kui palju?"
173 = "Fail"
174 = "Pun"
175 = "seaded"
176 = "üldised seaded"
177 = "Hüpete seaded"
178 = "Rekordite seaded"
180 = "jah"
181 = "jah"
182 = "jah"
183 = "jah"
184 = "jah"
185 = "ei"
186 = "ei"
187 = "ei"
188 = "ei"
189 = "ei"
190 = "Tühista"
191 = "Nulli"
192 = "max punktid?"
193 = "oled kindel?"
194 = "About to delete"
195 = "lahku"
196 = "üldised seaded"
197 = "Hüpete seaded"
198 = "Rekordite seaded"
199 = "Personaliseeri nupud"
200 = "sea rekordite norm"
201 = "Mäe valmistaja"
203 = "tagasi"
204 = "Keel?"
205 = "hoiatus hääled?"
206 = "Graafilised detailid?"
207 = "vastaste nimede paigutamine (names?.ski)?"
208 = "Hallid asjad on  kättesaadavad"
209 = "registreeritud versioonis"
211 = "tagasi"
212 = "Treening voorud?"
213 = "Extra Statistika?"
214 = "punktitabelid kaotuse järgi?"
215 = "näita MK tulemusi kaotuse järgi?"
216 = "kompaksed tabelid?"
217 = "nähtamatu punktitabel taustaks?"
218 = "Automaatne rekordhüppe korduse salvestamine?"
219 = "näidata rekordite norme?"
220 = "vali näidatavad arvuti hüppajad?"
221 = "vali tuulelipu asukoht"
222 = "kasuta välja kukkumis süsteemi neljal mäel?"
225 = "lahku"
226 = "arvuti hüppab rekordeid?"
227 = "nimede kordamine lubatud?"
228 = "kustuta rekordid"
229 = "nulli rekordid"
230 = "taasta normaal tingimused"
231 = "mitte kunagi"
232 = "ei ole 4m"
233 = "Alati"
235 = "Liidrit"
236 = "Top 3'me"
237 = "Top 5'te"
238 = "Top 10'et"
239 = "k6iki!"
240 = "ühtegi"
242 = "eesmärk"
243 = "kasuta nooli, ESC väljub"
245 = "Lahkud juba?"
246 = "eelm"
247 = "järg"
248 = "k6ik"
251 = "no sa siis lahkud..."
252 = "kas t6esti tahad lahkuda?"
253 = "Oh, nii kiiresti lahkud?"
256 = "oled sa selles kindel?"
257 = "oled sa täiesti kindel?"
258 = "ütle jah kui lahkud."
261 = "Ahoi! sul peab olema neli (4)"
262 = "v6i kaheksa (8) mängijat"
263 = "enne meeskondliku v6istlust!"
264 = "mine kutsu s6pru ühinema sinuga"
265 = "v6i klooni ennast nelja korda."
270 = "SJ3 mäe valmistaja"
271 = "(kasut. nooli, DEL,"
272 = " ENTER v6i ESC)"
273 = "Failinimi"
274 = "mäenimi"
275 = "*lisa uus mägi*"
276 = "-lahku-"
277 = "-alusta-"
278 = "Testi oma mäge!"
280 = "Nool üles"
281 = "nool Vasakule"
282 = "nool paremale"
283 = "nool alla"
285 = "(L)oad set"
286 = "(S)ave set"
287 = "(R)andom set"
288 = "S(O)rteeri MK punktide järgi"
289 = "S(O)rteeri Kogu punktide järgi"
290 = "ühtegi kordust ei leitud!"
291 = "Autor:"
292 = "Nimi:"
293 = "Failinimi:"
294 = "Mägi:"
295 = "Välju, ära salvesta"
296 = "välju ja salvesta"
298 = "(S)alvesta kordus"
300 = "Hüpaja"
301 = "vali hüppajad"
302 = "*loo uus hüppaja*"
304 = "Nimi:"
305 = "Pärisnimi:"
306 = "kombe värv:"
307 = "Suuskade värv:"
308 = "asenda:"
309 = "treener:"
310 = "Jäta kvali:"
311 = "kustuta hüppaja"
312 = "välju"
313 = "kogusumma hüppeid:"
314 = "Mk-sid l6petanud:"
315 = "voore v6itnud:"
316 = "etappe v6itnud:"
317 = "Parim MK tulemus:"
318 = "parim 4hüppemäe turnee tulemus:"
319 = "pikim mk hüpe:"
320 = "pikim hüpe:"
321 = "KOTH tase:"
322 = "(kasuta nooli,"
323 = "ENTER muudab hüppajat,"
324 = "DEL kustutab järjekorrast)"
325 = "ENTER registreerib,"
326 = "DEL kustutab hüppaja)"
328 = "kustuta hüppaja"
329 = "taasta hüppaja"
330 = "NUPPUDE plaan"
331 = "ärat6uge"
332 = "keerab edasi"
333 = "keerab tagasi"
334 = "Telemark maandumine"
335 = "kahejalaga maandumine"
336 = "taasta orginaalid"
337 = "välju"
340 = "Hangtime"
341 = "pikkus"
342 = "kiirus:"
343 = "tavaline"
345 = "juba olemas."
346 = "ⁿle kirjutada?"
350 = "korduse fail salvestatud ok."
351 = "korduse faili ei salvestatud."
352 = "järjestus salvestatud."
353 = "järjestus salvestamata."
354 = "Extra mäe salvestamine OK."
355 = "Extra mäe salvestamine eba6nnestus."
356 = "järjestusi ei leitud!"
360 = "tere tulemast SJ3 ja suusahüpete maailma."
361 = "siin on kiire tutvustus mängule."
362 = "Selle spordi idee on lennata v6imalikult"
363 = "kaugele end vigastamata."
364 = "sinu hüppaja istub poomil enne hoov6ttu"
365 = "kasuta paremat noolt alustamaks hoov6ttu."
366 = "tuulelipp on alumises vasakus ekraani nurgas"
367 = "vastu tuul on parem kuna see lennutab kaugemale."
368 = "ideaalse hüppe v6ti on ärat6ukes."
369 = "kasuta üles noolt ärat6ukeks."
370 = "nüüd pead meest ette kallutama et"
371 = "vähendada tuule takistust.  kauta paremat noolt."
372 = "vahetevahel v6ib tuulepuhang sind tasakaalust"
373 = "välja viia.  kasuta vasakut noolt et parandada positsioon."
374 = "kui hakkad maale lähedale j6udma siis alusta"
375 = "m6tlemist sellele kuidas ohutult maanduda."
376 = "'T' nupp alustab telemark maandumist.  mis on"
377 = "aeglasem ja ohtlikum kuid stiili poolest kasulikum."
378 = "'R' nupp alustab ohutumat jalad koos maandumist,"
379 = "mis on kasulik pikkadel hüpetel."
380 = "See on k6ik! sissejuhatust saad vaadata uuesti"
381 = "Korduste menüü alt ja rohkem infot saad MANUAL.TXT lugedes."
390 = "ülemine"
391 = "keskmine"
392 = "alumine"
393 = "vasak"
394 = "keskel"
395 = "parem"
396 = "hüppaja"
400 = "Treeneri nurk:"
401 = "kutsealane"
402 = "ära lase lennu positsiooni nii alla."
403 = "hea positisoon lennus."
404 = "sinu lennu positsioon on liiga püstine."
405 = "Maandu ka järgmine kord!"
406 = "alusta maandumist varem."
407 = "kehvasti see kord."
410 = "See on väga vilets hüppamine."
411 = "See ei ole ikka veel hea."
412 = "See oli peaaegu hea hüpe."
413 = "Hea hüpe."
414 = "viimasepeal hüpe!"
415 = "Uskumatu! Kus on sinu maapind?"
418 = "Alusta t6uget varem."
419 = "T6uge oli liiga hilja."
420 = "Seekord oli parem kuid ikka hilja."
421 = "parem ajastus seekord."
422 = "ideaalne ajastus t6ukel!"
423 = "liiga varajane t6uge."
424 = "ära alusta t6uget nii vara."
425 = "see oli 6udne t6uge! alusta ikka palju varem!!!"
428 = "ma m6tlesin sitaks varem!"
429 = "sel korral oli see liiga hilja."
430 = "maandumine oli viimasel hetkel."
431 = "paras ajastus maandumisel."
432 = "see peaks andma sulle head punktid."
433 = "sa peaksid kauem ootama maandumisega."
434 = "ära karda lennata kauem."
435 = "maandumisel vajuta R-nuppu v6i t-nuppu!"
441 = "Vaba"
442 = "ära nüüd üle keera seda hüpet."
443 = "see on armas lennu positsioon."
444 = "pojake, ära karda ettepoole pisut n6jatuda ."
445 = "palun maandu järgmine kord, muidu on valus."
446 = "poiss, sa ikka maandud oma larfile."
447 = "okei sa ei suuda neid k6iki taluda."
450 = "see oli nüüd liiga vabaks lastud."
451 = "Jah, püüa mitte murda rasket tööd."
452 = "see paistab juba pisut hüüppe moodi."
453 = "vot see on hüpe mida ma kutsub lendamiseks."
454 = "oh jah! vot see juba beibedele meeldib!"
455 = "see oli vinge! ma tahaks tutvustada uut superman'i!"
458 = "milline paksperse, v6iks t6ugata ka..."
459 = "kui tulid siia lendama siis t6uka ka varem."
460 = "sinu ajastus ei ole kogu aeg nii hea."
461 = "hei! vot sellisne t6uge juba läheb!"
462 = "Hei, ma lihtsalt armastan sinu ärat6uget!"
463 = "t6uge oli natukene vara."
464 = "ära kiirusta t6ukega."
465 = "nii sa veel vigastad ennast kunagi."
468 = "sa peaksid rohkem töötama maandumise kallal."
469 = "kas sa ei karda surma???"
470 = "see maandumine oli küll äärepeal."
471 = "maandumine - Soliidne nagu rock."
472 = "Oh Mr.hea maanduja tuli linna."
473 = "ära kiirusta selle maandumise tunnetamisega"
474 = "ära karda hiljem maanduda"
475 = "ära karda klaviatuuri jobu!"
481 = "n6udlik"
482 = "saa oled lennu ajal liiga ees!"
483 = "see on juba viisaks asend."
484 = "pööra hüpet nagu mees!"
485 = "oi mu kallis saatan! kus on su maandumine?"
486 = "ei! alusta seda kuradi maandumist 6igel ajal!"
487 = "t6sta oma perse püsti ja mine tagasi tööle!"
490 = "ma pole iial näinud hullemat hüppajat, kui sina!"
491 = "mu ema hüppab ka paremini kui sina."
492 = "mis viga? tahad koju emme juurde, mis?"
493 = "sa suudad paremini kui see oli."
494 = "m6ned treenerid oleksid r66msad selle üle."
495 = "alles nüüd hüppad nagu ma sulle 6petasin."
498 = "6udne! kus on see kuradi t6uge!"
499 = "t6uge oli hilja jälle! 50 kättek6verdust!!!"
500 = "ajastus on ikka pask! 25 kättek6verdust!!!"
501 = "kas sa ei suuda siis varem t6ugata?"
502 = "nüüd oli see t6uge mida ma ootasin."
503 = "liiga vara!  kas sa ka kunagi ei 6pi?"
504 = "hull t6uge! 50 kättek6verdust!!!"
505 = "ma pole iial näinud hullemat t6uget. mine koju!!!"
508 = "kas maanumine on siis nii raske?"
509 = "ei! alusta seda kuradi maandumist 6igel ajal!"
510 = "see maandumine oli liiga riskantne."
511 = "see oli juba peaaegu maandumine."
512 = "ma arvan, et see oli päris hea maandumine."
513 = "oota pisut selle maandumisega."
514 = "mid sa kardad? lenda kurat v6taks!"
515 = "oled sa lollakas? maandu v6i mine koju!"
520 = "Load Cup"
521 = "Save cup state?"
522 = "Current jump is lost."
523 = "No saved cups"
524 = "MULTIPLAYER"
