id = "francais"
name = "Francais"

[strings]
1 = "Un"
2 = "Deux"
3 = "Trois"
4 = "Quatre"
5 = "Cinq"
6 = "Oui"
7 = "Non"
8 = "de"
9 = "Aucun"
11 = "Enregistre"
12 = "Shareware"
13 = "Normal"
14 = "Bas"
15 = "Appuyez sur une touche..."
17 = "Menu Principal"
18 = "Menu du saut"
20 = "Sauter!"
21 = "Noms des Sauteurs"
22 = "Configuration"
23 = "Records"
24 = "Records des sauts"
25 = "Ralentis"
26 = "Sortie SJ3"
27 = "Coupe du Monde"
28 = "C. du Monde Perso"
29 = "Tournee des 4 Tr."
30 = "Coupe par Equipe"
31 = "Roi du Tremplin"
32 = "Entrainement"
33 = "Retour"
34 = "Sauteurs:"
35 = "Cette version"
36 = "a ete enregistree par:"
38 = "Ceci est une version"
39 = "non enregistree de SJ3."
40 = "Lis Register.Txt !"
41 = "Comment etre le gars le plus cool"
42 = "du voisinage,"
43 = "Tu veux gagner le respect"
44 = "de tes amis?  Enregistre-toi, mec!"
45 = "Ceci n'est pas un jeu freeware."
46 = "Rentre dans le droit chemin, enregistre-toi."
47 = "2 Joueurs seulement !"
48 = "c'est une version non enregistree"
51 = "Essai"
52 = "Entrainements"
53 = "Qualifications"
54 = "Manche 1"
55 = "Manche 2"
56 = "Suivant..."
57 = "L'ordi saute..."
58 = "Depart:"
59 = "(S) pour configurer"
60 = "S"
61 = "Pour le moment"
62 = "Pour mener"
63 = "Pour gagner"
65 = "Record"
67 = "Sauteurs a venir:"
68 = "Pour passer devant:"
69 = "Actuellement dernier:"
70 = "Classement CM provisoire"
71 = "Classement CE provisoire"
75 = "Va rater"
76 = "Etapes"
77 = "La manche suivante"
78 = "L'Θtape suivante"
79 = "est disqualifie!"
81 = "Tableau des Scores - Etape"
82 = "Qualifications - Etape"
83 = "de 4"
84 = "Tournee des 4 Tremplins - Etape"
85 = "Resultats finaux de la Tournee des 4 Tremplins"
86 = "(liste compacte)"
87 = "Classement apres Etape"
88 = "Sauteur"
89 = "Stats de Coupe du Monde pour"
90 = "Resultats finaux de"
91 = "Classement de la Coupe par Equipe apres"
92 = "Resultats finaux de la Coupe par Equipe"
93 = "Stats de la Coupe par Equipe pour"
94 = "Systeme d'elimination directe"
95 = "Classement"
96 = "Roi du Tremplin"
97 = "Score"
98 = "CM"
99 = "4 Tremplins:"
100 = "Total:"
101 = "Elimine:"
102 = "Ne sautent plus:"
103 = "Sauteurs elimines:"
104 = "Deja aux vestiaires:"
105 = "Plus parmi nous:"
106 = "Ou ?"
107 = "Equipe:"
108 = "Pos"
109 = "Pts"
110 = "CE"
111 = "Pret pour la Coupe par Equipe"
112 = "Calendrier de la Coupe par Equipe:"
113 = "Nom de l'Equipe"
114 = "Equipe"
115 = "Meilleur resultat:"
116 = "Charger serie perso"
117 = "Sauver serie perso"
118 = "Selectionnez les tremplins:"
119 = "Utilise les fleches, ENTER commence, ESC sort"
120 = "Sauteurs de l'ordinateur:"
121 = "Commencer *Roi du Tremplin*"
122 = "Selectionner le niveau"
123 = "Choisir les adversaires"
124 = "Sauter a"
125 = "Vent ?"
126 = "Manches ?"
127 = "Retour"
128 = "Nouveau record pour cette CM perso!"
129 = "Ancien record:"
130 = "Niveau"
131 = "LE CHALLENGE ULTIME"
132 = "DUR A AVALER"
133 = "SERAS-TU A LA HAUTEUR ?"
134 = "SUREMENT BATTABLE"
135 = "POUR LES VIEUX"
136 = "PETITES FILLETTES"
137 = "PERSO"
138 = "Selectionne tes adversaires"
139 = "Utilise les fleches pour le niveau"
140 = "ENTER valide, ESC exit"
141 = "Nom"
142 = "Classement"
143 = "The King!"
146 = "(Utilise les fleches, ENTER, DEL ou ESC)"
150 = "(Utilise les fleches, ENTER ou ESC)"
151 = "Ou veux-tu"
152 = "Sauter"
153 = "Aujourd'hui?"
154 = "Sortir"
155 = "Hasard"
156 = "Plus de tremplins..."
157 = "Page"
158 = "Page suivante"
159 = "Page precedente"
160 = "Roi du tremplin"
161 = "Non reussi"
162 = "Records des CM perso sauvegardees"
163 = "Top 20, Resultats de la Coupe du Monde SJ3"
164 = "Top 10, Resultats de la Coupe par Equipe"
165 = "Top 5, Scores de la Tournee des 4 Tremplins"
166 = "Nom"
167 = "Pos"
168 = "Points"
169 = "Quand?"
170 = "Les Records"
171 = "Qui?"
172 = "Combien?"
173 = "Fichier"
174 = "Pts"
175 = "Configuration Generale"
176 = "Menu des Options Generales"
177 = "Quelques options pour le saut"
178 = "Quelques options pour les records"
180 = "Oh Oui"
181 = "Sur"
182 = "Oui Chef"
183 = "Yep"
184 = "Ouais"
185 = "Oh Non"
186 = "Pas Question"
187 = "Negatif"
188 = "Nope"
189 = "Naah"
190 = "Reset"
191 = "A Zero"
192 = "les Scores?"
193 = "Es-tu sur?"
194 = "About to delete"
195 = "Sortir"
196 = "Options generale"
197 = "Options de saut"
198 = "Options de configuration"
199 = "Changer les touches"
200 = "Changer le but du tremplin"
201 = "Editeur de tremplin"
203 = "Retour"
204 = "Langue ?"
205 = "Bips ?"
206 = "Niveau de detail ?"
207 = "Noms des adversaires (NAMES?.SKI)?"
208 = "Options grisees uniquement"
209 = "disponibles dans version Enregistree"
211 = "Retour"
212 = "Entrainements?"
213 = "Plus de Stats?"
214 = "Tableau des Scores en Difference?"
215 = "Montre les classements CM avec difference?"
216 = "Tableau des Scores Resumes?"
217 = "Arriere-plan Tableau des Scores Invisible?"
218 = "Auto sauvegarde ralentis des records de tremplin?"
219 = "Egale les buts des records du tremplin?"
220 = "Selectionne les sauteurs de l'ordi vus?"
221 = "Change la place de l'anemometre"
222 = "Utiliser elimination directe pour les 4T?"
225 = "Sortir"
226 = "L'ordi peut battre les records?"
227 = "Plusieurs noms identiques?"
228 = "Scores par Defaut"
229 = "Scores a Zero"
230 = "Retour vers valeurs par defaut"
231 = "Jamais"
232 = "Pas en 4T"
233 = "Toujours"
235 = "Leader"
236 = "Top 3"
237 = "Top 5"
238 = "Top 10"
239 = "Tous!"
240 = "Aucun"
242 = "But"
243 = "Utilise les fleches, ESC sort"
245 = "Tu pars deja?"
246 = "PREC"
247 = "SUIV"
248 = " OK"
251 = "Alors comme ca tu t'en vas..."
252 = "Tu veux vraiment partir?"
253 = "Oh, tu arretes deja?"
256 = "T'es sur de ca?"
257 = "T'es absolument sur?"
258 = "Tape O pour quitter."
261 = "Hola! Tu dois avoir (4)"
262 = "ou huit (8) joueurs"
263 = "avant de disputer la Coupe par Equipe!"
264 = "Demande a tes potes de jouer"
265 = "ou clone-toi 4 fois."
270 = "Editeur de tremplin"
271 = "(Utilise les fleches,"
272 = "DEL, ENTER or ESC)"
273 = "Nom de fichier"
274 = "Nom du tremplin"
275 = "*Ajouter nouveau tremplin*"
276 = "-Sortie-"
277 = "-Commencer-"
278 = "Teste ton tremplin!"
280 = "Haut"
281 = "Gauche"
282 = "Droite"
283 = "Bas"
285 = "(C)harger serie"
286 = "(S)auver serie"
287 = "(H)asard"
288 = "Trier par p(O)ints de championnat"
289 = "Trier par p(O)ints"
290 = "Pas de ralenti!"
291 = "Auteur:"
292 = "Nom:"
293 = "Nom du fichier:"
294 = "Tremplin:"
295 = "Sortir et ne pas enregistrer"
296 = "Sortir et enregistrer"
298 = "(S)auve le ralenti"
300 = "Sauteurs"
301 = "Selectionne Sauteurs"
302 = "*Creer Nouveau Sauteur*"
304 = "Nom:"
305 = "Noms reels:"
306 = "Couleur Combinaison:"
307 = "Couleur des Skis:"
308 = "Remplace:"
309 = "Coach:"
310 = "Passer Qlf:"
311 = "Reset Sauteur"
312 = "OK"
313 = "Nombre total de sauts:"
314 = "Participations en CM:"
315 = "Manches gagnees:"
316 = "Coupes du Monde gagnees:"
317 = "Meilleur resultat en CM:"
318 = "Meilleur resultat en 4T:"
319 = "Plus long saut de CM:"
320 = "Plus long saut:"
321 = "Niveau du RdT:"
322 = "(Utilise les fleches,"
323 = "ENTER pour editer,"
324 = "DEL annule)"
325 = "ENTER valide,"
326 = "DEL pour supprimer)"
328 = "Supprime le sauteur"
329 = "Change le sauteur"
330 = "Config clavier"
331 = "Decollage"
332 = "Penche en avant"
333 = "Penche en arriere"
334 = "Atterrissage en telemark"
335 = "Atterrissage pieds-joint"
336 = "Valeurs par defaut"
337 = "Sortie"
340 = "Temps de suspension"
341 = "Longueur"
342 = "Vitesse:"
343 = "Customise"
345 = "existe deja."
346 = "Remplacer?"
350 = "Sauvegarde ok."
351 = "Erreur de sauvegarde."
352 = "Sauvegarde ok."
353 = "Erreur de sauvegarde."
354 = "Sauvegarde ok."
355 = "Erreur de sauvegarde."
356 = "Pas de serie trouvee!"
360 = "Bienvenue dans SJ3 et le saut a ski."
361 = "Petite intro au jeu."
362 = "L'esprit de ce sport est de sauter aussi"
363 = "loin que possible et d'atterrir sans te blesser."
364 = "Le sauteur s'assied sur un banc en haut de la"
365 = "rampe.Appuie sur les fleches pour commencer a descendre."
366 = "L'anemometre est situe en haut a gauche de"
367 = "l'ecran. Il vaut mieux du vent de face qui te porte."
368 = "La cle d'un bon saut est l'impulsion."
369 = "Appuie sur haut pour decoller."
370 = "Tu dois maintenant te pencher en avant pour"
371 = "diminuer la resistance de l'air. Appuie sur droite."
372 = "Parfois,tu peux etre destabilise par une rafale de vent."
373 = "Appuie alors sur gauche pour rectifier ta position."
374 = "Quand la terre se rapproche, il serait prudent"
375 = "de penser a atterrir sans encombre."
376 = "'T' te fait atterrir en telemark.C'est plus lent et plus"
377 = "dangereux mais rapporte beaucoup de points en style."
378 = "'R' commence l'atterrisage pieds-joints,plus facile,"
379 = "ce qui est bien pour les sauts tres longs."
380 = "Ca y est! Tu peux revoir l'intro du"
381 = "menu des ralentis et d'autres infos, lis MANUAL.TXT."
390 = "Haut"
391 = "Milieu"
392 = "Bas"
393 = "Gauche"
394 = "Centre"
395 = "Droite"
396 = "Sauteur"
400 = "Coin de l'Entraineur:"
401 = "Professionnel"
402 = "Essaie de ne pas te laisser aller vers le bas en vol."
403 = "Bonne position en vol."
404 = "Position de vol trop verticale."
405 = "Atterris la prochaine fois."
406 = "Commence la reception plus tot."
407 = "Euh, pas de chance sur ce coup."
410 = "Ca c'est un saut de merde."
411 = "C'est encore pas tres beau a voir."
412 = "Honnetement, c'etait un joli saut."
413 = "Joli saut."
414 = "Excellent Saut!"
415 = "Incroyable!  Ou est-ce que tu as cache ta cape?"
418 = "Commence l'impulsion beaucoup plus tot."
419 = "Tu as decolle trop tard."
420 = "Le timing est encore un poil trop tard."
421 = "Meilleur timing la."
422 = "Super timing a l'impulsion!"
423 = "Tu as saute legerement trop tot."
424 = "Ne saute pas si tot."
425 = "Impulsion affreuse. Saute beaucoup plus tard."
428 = "Je veux dire beaucoup plus tot."
429 = "C'etait trop tard cette fois."
430 = "Tu as atterri a peine a temps."
431 = "OK pour le timing a la reception."
432 = "Ca devrait te donner pas mal de points pour le style."
433 = "Tu aurais pu attendre plus avant d'atterrir."
434 = "N'aie pas peur de voler plus longtemps."
435 = "Appuie sur 'R' ou 'T' s'il te plait."
441 = "Relax"
442 = "He, te couche pas sur tes skis, non plus."
443 = "Delicieuse position en vol."
444 = "N'aie pas peur de te pencher plus, gamin."
445 = "Atterris la prochaine fois, sinon ca fait mal."
446 = "Atterrir sur la tete c'est un peu chaud."
447 = "Eh bien, tu peux pas les rΘussir tous, tu sais."
450 = "C'est trop relax ca."
451 = "Ouais ben c'est pas encore ca."
452 = "Ca ressemble plus a quelque chose ca."
453 = "Ca c'est ce que j'appelle un bon saut."
454 = "Oh yeah, les nanas vont adorer ca!"
455 = "Enoorme! J'aimerais que tu rencontres Superman!"
458 = "Decollage de merde..."
459 = "Si tu veux voler, decolle plus tot."
460 = "Ton timing n'est pas au point."
461 = "Ma foi bon timing, mon gars."
462 = "Hey, J'ai adore l'impulsion!"
463 = "L'impulsion ? Juste un peu tot."
464 = "Ne precipite pas la reception."
465 = "Ooh, un jour tu vas te faire mal."
468 = "Tu devrais travailler un peu la reception."
469 = "T'as pas peur de mourir?.."
470 = "Whou, cette reception etait limite."
471 = "Telemark - Solide comme un Roc."
472 = "Ooh, M.Atterrissage-en-Douceur est en ville."
473 = "Ne precipite pas la reception...t'as le temps!"
474 = "Te degonfle pas pendant le vol."
475 = "N'aie pas peur du clavier, mec."
481 = "Strict"
482 = "T'es trop penche en vol, ducon."
483 = "Ouais pas mal la position en vol."
484 = "Putain! T'as un balai dans le cul en vol ou quoi??"
485 = "Oh mon Dieu! Ou qu'elle est cette impulsion?"
486 = "Non! Commence la reception a temps!"
487 = "Bouge ton cul et va bosser!"
490 = "Jamais vu pire saut."
491 = "Ma mere saute mieux que ca."
492 = "Qu'est-ce qui va pas? Tu veux rentrer chez maman?"
493 = "Tu peux faire beaucoup mieux."
494 = "Certains entraineurs se contenteraient de τa mais bon..."
495 = "La t'as saute comme j't'avais dit."
498 = "C'est pas vrai! Ou qu'elle est cette impulsion??"
499 = "Impulsion tardive. 50 pompes!"
500 = "Timing mauvais. 25 pompes!"
501 = "Tu peux pas decoller un peu plus tot, non??"
502 = "Cette impulsion c'etait ce que je voulais."
503 = "Trop tot!  Tu vas te le mettre dans le crane?"
504 = "Envol Catastrophique! 50 pompes!"
505 = "J'ai jamais vu une impulsion aussi nulle. Degage."
508 = "Atterrir c'est trop te demander, fils a papa??"
509 = "Non! Commence cette putain de reception plus tot!"
510 = "Trop risquee la reception."
511 = "Ca ressemblait presque a un telemark."
512 = "La reception est presque correcte."
513 = "T'enflamme pas a la reception."
514 = "T'as peur ou quoi? Vole, bon sang!"
515 = "T'es stupide? Atterris ou rentre chez toi!"
