id = "hrvatski"
name = "Hrvatski"

[strings]
1 = "Jedan"
2 = "Dva"
3 = "Tri"
4 = "Cetiri"
5 = "Pet"
6 = "Sest"
7 = "Ne"
8 = "od"
9 = "Nijedan"
11 = "Registriran"
12 = "Shareware"
13 = "Normalan"
14 = "Nizak"
15 = "Pritisni tipku..."
17 = "Glavni izbornik"
18 = "Izbornik skokova"
20 = "Skoci!"
21 = "Skakaci"
22 = "Postavke"
23 = "Kuca slavnih"
24 = "Rekordi skakaonica"
25 = "Snimka"
26 = "Izlaz iz SJ3"
27 = "SJ3 Svjetski kup"
28 = "Osobni Svjetski kup"
29 = "Turneja cetiri skakaonice"
30 = "Ekipni kup"
31 = "Kralj skakaonice"
32 = "Trening"
33 = "Povratak u glavni izbornik"
34 = "Skakaci:"
35 = "Ova verzija"
36 = "je registrirana za:"
38 = "Ovo je neregistrirana"
39 = "verzija SJ3."
40 = "Procitajte Register.Txt sada!"
41 = "o tome kako postati najveca"
42 = "faca u svojem susjedstvu,"
43 = "Zelite steci slavu medu"
44 = "svojim prijateljima? Registriraj se, covjece!"
45 = "Ovo nije freeware igra."
46 = "Ucini pravu stvar, registriraj se."
47 = "Samo su dva igraca dopustena"
48 = "u ovoj neregistriranoj verziji!"
51 = "Trening"
52 = "Zagrijavanje"
53 = "Kvalifikacijski skok"
54 = "Prvi skok"
55 = "Drugi skok"
56 = "Slijedeci..."
57 = "Kompjuterski skakaci..."
58 = "Startna vrata:"
59 = "Pritisni (S) za glavni izbornik"
60 = "S"
61 = "Upravo sada"
62 = "Za trenutno prvo mjesto"
63 = "Za pobjedu"
65 = "Rekord skakaonice"
67 = "Preostali skakaci:"
68 = "Potrebno pobijediti:"
69 = "Trenutno posljednji:"
70 = "Trenutni poredak u svj. kupu"
71 = "Trenutni poredak u ekipnom kupu"
75 = "Propusta slijedece"
76 = "skakaonice"
77 = "skok"
78 = "skakaonicu"
79 = "je diskvalificiran!"
81 = "Poredak - Skok"
82 = "Kvalifikacije - skok"
83 = "od cetiri"
84 = "Turneja cetiri skakaonice - Skok"
85 = "Konacni rezultati turneje cetiri skakaonice"
86 = "(kraca lista)"
87 = "Poredak poslije skoka"
88 = "Skakac"
89 = "Statistika svjetskog kupa za"
90 = "Konacni rezultati za"
91 = "Poredak ekipnog natjecanja nakon skoka"
92 = "Konacni poredak ekipnog natjecanja"
93 = "Statistika ekipnog natjecanja za"
94 = "knock-out sustav parova"
95 = "Poredak"
96 = "Kralj skakaonice"
97 = "Bodovi"
98 = "sK"
99 = "4 skakaonice:"
100 = "Ukupno:"
101 = "Izvan natjecanja:"
102 = "Vise ne skacu:"
103 = "Eliminirani skakaci:"
104 = "U svlacionici:"
105 = "Nisu vise medu nama:"
106 = "Gdje?"
107 = "Ekipa:"
108 = "Mje"
109 = "Bod"
110 = "EK"
111 = "Spremi se za ekipni kup"
112 = "Raspored ekipnog kupa:"
113 = "Upisite ime ekipe:"
114 = "Ekipa"
115 = "Najbolji rezultat:"
116 = "Ucitaj skakaonice osobnog kupa"
117 = "Spremi skakaonice osobnog kupa"
118 = "Odaberi skakaonice za svoj osobni kup"
119 = "Koristi strelice, ENTER start, ESC izlaz"
120 = "Kompjuterski skakaci:"
121 = "Zapocni *Kralja skakaonice*"
122 = "Odaberi razinu tezine"
123 = "Odaberi protivnike"
124 = "Skakanje u:"
125 = "Vjetar?"
126 = "Skokovi?"
127 = "Povratak u glavni izbornik"
128 = "Novi rekord osobnog kupa!"
129 = "Stari rekord:"
130 = "Razina tezine \"Kralja skakaonice\""
131 = "NAJTEZI IZAZOV"
132 = "TVRDI ORASI"
133 = "LAKSA VARIJANTA"
134 = "LAKO POBJEDIVI"
135 = "UMIROVLJENICI"
136 = "OBICNE CURICE"
137 = "OSOBNE POSTAVKE"
138 = "Odaberi protivnika"
139 = "Koristi strelice za odabir razine"
140 = "ENTER odabir, ESC izlaz"
141 = "Ime"
142 = "Mjesto"
143 = "Kraaaalj!"
146 = "(Koristi strelice, ENTER, DEL ili ESC)"
150 = "(Koristi strelice, ENTER ili ESC)"
151 = "Gdje"
152 = "zelis skakati"
153 = "danas?"
154 = "Izlaz"
155 = "Nasumicni izbor skakaonice SK"
156 = "Vise skakaonica..."
157 = "Stranica"
158 = "Slijedeca stranica"
159 = "Prosla stranica"
160 = "Izazovi kralja skakaonica"
161 = "Nije dovrseno"
162 = "Spremljeni najbolji rezultati osobnog kupa"
163 = "Top 20 SJ3 rezultata svjetskog kupa"
164 = "Top 10 rezultata ekipnog natjecanja"
165 = "Top 5 rezultata turneje cetiri skakaonice"
166 = "Ime"
167 = "Mje"
168 = "Bodovi"
169 = "Kada?"
170 = "Rekordi skakaonica"
171 = "Tko?"
172 = "Koliko?"
173 = "Dokument"
174 = "Bodovi"
175 = "Pregled glavnog izbornika"
176 = "Ovo su opcenite mogucnosti"
177 = "Neke mogucnosti skakanja"
178 = "Neke mogucnosti najboljih rezultata"
180 = "O, da"
181 = "Naravno"
182 = "Da, gospon"
183 = "Aha"
184 = "Kak ne"
185 = "o, ne"
186 = "Nema sanse"
187 = "Nikako"
188 = "A-a"
189 = "Nis"
190 = "Vratiti na pocetne vrijednosti"
191 = "Nula"
192 = "najbolje rezultate?"
193 = "Sigurno?"
194 = "ce biti obrisani"
195 = "Izlaz iz postavki"
196 = "Opcenite mogucnosti"
197 = "Mogucnosti skakanja"
198 = "Rekordi i mogucnosti skakanja"
199 = "Promijeni tipke"
200 = "Postavi cilj rekorda"
201 = "Sagradi skakaonicu"
203 = "Povratak u Setup.Main"
204 = "Jezik?"
205 = "Zvukovi?"
206 = "Razina grafike?"
207 = "Imena kompjuterskih skakaca (NAMES?.SKI)?"
208 = "Dijelovi otisnuti sivim su"
209 = "dostupni samo u registriranoj verziji"
211 = "Povratak u glavni izbornik"
212 = "Skokovi za trening?"
213 = "Dodatna statistika?"
214 = "Prikazi rezultate kao razliku?"
215 = "Prikazi poredak svj. kupa kao razliku?"
216 = "Kompaktni rezultati?"
217 = "Nevidljiva pozadina rezultata?"
218 = "Automatski sa?uvati snimke rekorda skakaonica?"
219 = "Pokazi trenutne rekorde skakaonica?"
220 = "Odaberi gledanje kompjuterskih skakaca?"
221 = "Odaberi mjesto mjeraca vjetra"
222 = "Koristi knock-out sustav u cetiri skakaonice?"
225 = "Izlaz iz izbornika najboljih rezultata"
226 = "Mogu li kompjuterski skakaci oboriti rekorde?"
227 = "Dozvoli vise istih imena na popisu"
228 = "Obrisi najbolje rezultate"
229 = "Najbolje rezultate stavi na nulu"
230 = "Vrati izvorne vrijednosti"
231 = "Nikada"
232 = "Ne u cetiri skakaonice"
233 = "Uvijek"
235 = "Vodeci"
236 = "Top 3"
237 = "Top 5"
238 = "Top 10"
239 = "Sve!"
240 = "Nikoga"
242 = "Cilj"
243 = "Koristi strelice, ESC izlaz"
245 = "Vec odlazis?"
246 = "PROS"
247 = "SLIJ"
248 = "GOTO"
251 = "Znaci ides..."
252 = "Stverno zelis otici?"
253 = "Odlazis ovako rano?"
256 = "Jesi li siguran za to?"
257 = "Jesi li sto posto siguran?"
258 = "Stisni D da izades."
261 = "Hej! Moras imati cetiri (4)"
262 = "ili osam (8) upisanih igraca"
263 = "prije ulaska u ekipni kup!"
264 = "idi pitaj prijatelje da ti pomognu"
265 = "ili se kloniraj cetiri puta."
270 = "SJ3 uredivac skakaonica"
271 = "(koristi strelice, DEL,"
272 = " ENTER ili ESC)"
273 = "Ime dokumenta"
274 = "Ime skakaonice"
275 = "*Dodaj novu skakaonicu*"
276 = "-Exit-"
277 = "-Start-"
278 = "Isprobaj svoju skakaonicu!"
280 = "Strelica gore"
281 = "Strelica lijevo"
282 = "Strelica desno"
283 = "Strelicu dolje"
285 = "(L)oad set"
286 = "(S)ave set"
287 = "(R)andom set"
288 = "P(O)redaj prema bodovima u Svj.kupu"
289 = "P(O)redaj prema ukupnim bodovima"
290 = "Nema snimke!"
291 = "Autor:"
292 = "Ime:"
293 = "Ime dokumenta:"
294 = "Skakaonica:"
295 = "Izadi, bez spremanja"
296 = "Izadi i spremi"
298 = "(S)acuvaj snimku"
300 = "Skakaci"
301 = "Odaberi skakace"
302 = "*Stvori novog skakaca*"
304 = "Ime:"
305 = "Pravo ime:"
306 = "Boja opreme:"
307 = "Boja skija:"
308 = "Zamijeni:"
309 = "Trener:"
310 = "Bez kval.:"
311 = "Resetiraj skakaca"
312 = "Izlaz"
313 = "Ukupno skokova:"
314 = "Zavrsenih svjetskih kupova:"
315 = "Pobjeda na skakaonicama:"
316 = "Svjetski prvak:"
317 = "Najbolje na svj. kupovima:"
318 = "Najbolje na 4 skakaonice:"
319 = "Najduzi skok u svj. kupu :"
320 = "Najduzi skok:"
321 = "Razina Kralja skakaonice:"
322 = "(Koristi strelice,"
323 = "ENTER ureduje skakaca,"
324 = "DEL brise iz poretka)"
325 = "ENTER upisuje,"
326 = "DEL brise skakaca)"
328 = "Brisati skakaca"
329 = "Resetirati skakaca"
330 = "Pregled tipki"
331 = "Odskok"
332 = "Nagni se prema naprijed"
333 = "Nagni se unatrag"
334 = "Telemark"
335 = "Dvonozni doskok"
336 = "Vrati izvorno"
337 = "Izlaz"
340 = "vrijeme u zraku"
341 = "Duzina"
342 = "Brzina:"
343 = "Osobno"
345 = "Vec postoji."
346 = "Prepisati preko?"
350 = "Dokument snimke je uredno spremljen ."
351 = "Dokument snimke nije spremljen."
352 = "Osobne promjene su uredno spremljene."
353 = "Osobne promjene nisu spremljene."
354 = "Dodatna skakaonica uredno spremljena."
355 = "Dodatna skakaonica nije spremljena."
356 = "Nije pronadena niti jedna osobna datoteka!"
360 = "Dobro dosli u SJ3 i svijet skijaskih skokova."
361 = "Evo kratkog uvoda u igru."
362 = "Osnovni cilj ovog sporta je letjeti sto"
363 = "je dalje moguce i izvesti siguran doskok."
364 = "Vas skakac sjedi na gredi na pocetku spustanja."
365 = "Koristite strelicu udesno za spustanje."
366 = "Mjerac vjetra smjesten je dolje lijevo."
367 = "Vjetar prema skakacu podize ga u letu."
368 = "Kljuc uspjeha dobrog skoka je pravovremeni"
369 = "odraz. Koristi strelicu gore za odraz."
370 = "Sada bi trebao nagnuti skakaca prema naprijed"
371 = "da smanjis otpor vjetra. Koristi strelicu desno."
372 = "Ponekad te nalet vjetra moze izbaciti iz"
373 = "ravnoteze. Koristi lijevu strelicu za vracanje."
374 = "Kako se tlo priblizava bilo bi mudro"
375 = "poceti misliti o sigurnom doskoku."
376 = "Tipka 'T' zapocinje telemark. Sporiji je"
377 = "i nesigurniji ali nosi vise bodova za stil."
378 = "Tipka 'R' zapocinje sigurniji dvonozni"
379 = "doskok, sigurniji za duze skokove."
380 = "To je to! Mozes ponovno vidjeti uvod u"
381 = "izbornikuk snimaka a za vise citaj MANUAL.TXT."
390 = "Vrh"
391 = "Sredina"
392 = "Dno"
393 = "Lijevo"
394 = "Srediste"
395 = "Desno"
396 = "Skakac"
400 = "Trenerovo videnje:"
401 = "Profesionalni"
402 = "Probaj ne dopustiti da ti je let tako nizak."
403 = "Dobra pozicija leta."
404 = "Previsok si u letu."
405 = "Napravi doskok slijedeci put."
406 = "Zapocni doskok ranije."
407 = "Uh, nije bilo srece."
410 = "Ovo je lose skakanje."
411 = "Jos uvijek ne izgleda dobro."
412 = "Ovo se jedva moze nazvati dobrim."
413 = "Dobar skok."
414 = "Izvrstan skok!"
415 = "Nevjerojatno! Gdje ti je kraj!"
418 = "Zapocni odskok mnogo ranije."
419 = "Odskok je bio prekasan."
420 = "Timing je jos uvijek prekasan."
421 = "Bolji timing ovaj put."
422 = "Izvrstan timing odskoka!"
423 = "Prerano si odskocio."
424 = "Nemoj tako rano raditi odskok."
425 = "Ovo je bio uzasan odskok. Puno kasnije ga radi."
428 = "Mislio sam - mnogo ranije odskoci."
429 = "Bilo je jednostavno prekasno ovaj put."
430 = "Doskok je bio jedva na vrijeme."
431 = "Ok timing kod doskoka."
432 = "Ovo bi trebalo dati dobre ocjene za stil."
433 = "Mogao si jos pricekati prije doskoka."
434 = "Ne boj se skakati dulje."
435 = "Pritisni tipku 'T' ili 'R', molim."
441 = "Opusten"
442 = "Hej, ne naginji se toliko u skoku."
443 = "Ovo je krasan polozaj u letu."
444 = "Ne boj se nagnuti mallo vise, sine."
445 = "Slijedeci put doskoci, ovo je bolno."
446 = "Jos uvijek prizemljujes na lice, decko."
447 = "Pa, ne mozes ih sve preletjeti, znas?"
450 = "Ovo je preopusteno."
451 = "Aha, ovo je bilo trapavo."
452 = "Ovo vec izgleda bolje."
453 = "Ovo ja nazivam dobrim letenjem."
454 = "O, da. Ovo koke vole!"
455 = "Ovo je famozno! Idi sredi Supermena!"
458 = "Dizi guzu na odskoku..."
459 = "Ako zelis letjeti, odskoci ranije."
460 = "Timing ti bas nije sjajan."
461 = "Odskok je bas na vrijeme, covjece."
462 = "Hej, volim ovakav odskok!"
463 = "Odskok je bio malo prerano."
464 = "Ne brzaj s odskokom."
465 = "Oh, ozlijedit ces se jednog dana."
468 = "Trebao bi malo poraditi na doskoku."
469 = "Zar se ne bojis da bi mogao umrijeti?.."
470 = "Uh, ovaj doskok je bio na rubu."
471 = "Doskok - siguran kao stijena."
472 = "Oho, gospodin Savrseni Doskok je u kvartu."
473 = "Ne prekidaj onaj osjecaj za doskok..."
474 = "Ne trtari u letu."
475 = "Ne boj se tipkovnice, covjece."
481 = "Strog"
482 = "Prenagnut si u letu, stoko."
483 = "Ovo je pristojna pozicija za let."
484 = "Slabicu! Nagni se kao muskarac."
485 = "O Boze! Gdje ti je doskok?"
486 = "Ne! Zapocni s vrazjim doskokom na vrijeme!"
487 = "Dizi guzicu i natrag na posao!"
490 = "Nikad nisam vidio losije skakanje."
491 = "Moja mama bolje skace od toga."
492 = "sto je bilo? Hoces doma mamici?"
493 = "Mozes ti puno bolje."
494 = "Neki treneri bi bili zadovoljni s tim."
495 = "Sad skaces onako kako sam ti rekao."
498 = "Grozno! Gdje je vrazji odskok!"
499 = "Opet kasnis s odskokom. 50 sklekova!"
500 = "Timing ti je i dalje grozan. 25 sklekova!"
501 = "Zar ne mozes odskociti ranije?"
502 = "Sad je bio odskok kakav sam zelio."
503 = "Prerano! Zar ne mozes nauciti?"
504 = "Katastrofa od odskoka! Odmah 50 sklekova!"
505 = "Nikad nisam vidio losiji odskok. Brisi doma!"
508 = "Je li doskok pretezak, mamina mazo?"
509 = "Ne! Zapocni s vrazjim doskokom ranije!"
510 = "Doskok ti je preriskantan."
511 = "Ovo je vec licilo na doskok."
512 = "Pretpostavljam da je ovo bio dobar doskok."
513 = "Nemoj se ustrtariti na doskoku."
514 = "cega se bojis? Leti, dovraga!"
515 = "Jesi li glup? Doskoci ili idi doma!"
520 = "Load Cup"
521 = "Save cup state?"
522 = "Current jump is lost."
523 = "No saved cups"
524 = "MULTIPLAYER"
