id = "italian"
name = "Italian"

[strings]
1 = "Uno"
2 = "Due"
3 = "Tre"
4 = "Quattro"
5 = "Cinque"
6 = "Si"
7 = "No"
8 = "di"
9 = "Nessuno"
11 = "Registrato"
12 = "Shareware"
13 = "Normale"
14 = "Basso"
15 = "Premere un tasto..."
17 = "Menu Principale"
18 = "Menu del Salto"
20 = "Salta!"
21 = "Saltatori"
22 = "Menu di setup"
23 = "I migliori"
24 = "Record della Collina"
25 = "Replay"
26 = "Esci SJ3"
27 = "SJ3 Coppa del Mondo"
28 = "Coppa del Mondo personalizzata"
29 = "Tour delle quattro Colline"
30 = "Coppa delle squadre"
31 = "Re della Collina"
32 = "Esercitazione"
33 = "Torna al Menu Principale"
34 = "Saltatori:"
35 = "Questa versione"
36 = "e' registrata a:"
38 = "Questa e' una versione"
39 = "non registrata di SJ3."
40 = "Leggi Register.Txt Adesso!"
41 = "Su come essere il gatto piu' figo"
42 = "del tuo vicinato,"
43 = "Vuoi guadagnarti il rispetto tra"
44 = "i tuoi amici?  Registrati!"
45 = "Questo non e' un game freeware."
46 = "Fai la cosa giusta, registrati."
47 = "Solo Due Giocatori ammessi"
48 = "in questa versione non registrata!"
51 = "Pratica"
52 = "Giro di Esercitazione"
53 = "Giro di Qualifica"
54 = "Giro 1"
55 = "Giro 2"
56 = "Prossimo Su..."
57 = "I Computer saltano..."
58 = "Cancello di Partenza:"
59 = "Premi (S) per Menu Setup"
60 = "S"
61 = "Adesso"
62 = "Bisogno di una Guida"
63 = "Bisogno di Vittoria"
65 = "Record della Collina"
67 = "Saltatori rimasti:"
68 = "Occorre Battere:"
69 = "Attualmente Ultimo:"
70 = "Attualmente Classifica WC"
71 = "Attualmente Classifica TC"
75 = "Mancati Prossimo"
76 = "Tratte"
77 = "Turno"
78 = "Tratta"
79 = "e' Squalificato!"
81 = "Tabellone - Tratta"
82 = "Qualifying - Tratta"
83 = "di 4"
84 = "Giro delle quattro Colline - Tratta"
85 = "Risultati finali del Giro delle Quattro Colline"
86 = "(lista compatta)"
87 = "Classifica dopo Tratta"
88 = "Saltatore"
89 = "Statistiche Coppa del Mondo per"
90 = "Risultati finali del"
91 = "Classifica Coppa a Squadre dopo Tratta"
92 = "Risultati Finali delle Coppa a Squadre"
93 = "Statistiche Coppa a Squadre per"
94 = "Accoppiamenti del sistema dell' espulsore"
95 = "Classifica"
96 = "Re della Collina"
97 = "Punteggio"
98 = "WC"
99 = "4colline:"
100 = "Totale:"
101 = "Fuori dalla Competizione:"
102 = "Fuori dai Salti:"
103 = "Saltatori Eliminati:"
104 = "Negli Spogliatoi:"
105 = "Non piu' tra di noi:"
106 = "Dove?"
107 = "Squadra:"
108 = "Pos"
109 = "Pti"
110 = "TC"
111 = "Preparati per la Coppa a Squadre"
112 = "Programma della Coppa a Squadre:"
113 = "Prego Immettere Nome Squadra"
114 = "Squadra"
115 = "Miglior Risultato:"
116 = "Carica Set di Collina Personalizzata"
117 = "Salva Set di Collina Personalizzata"
118 = "Seleziona Colline per la tua Coppa del Mondo Personalizzata"
119 = "Usa le frecce, ENTER inizia, ESC esce"
120 = "Saltatori del Computer:"
121 = "Inizia *Re della Collina*"
122 = "Seleziona Livello di Sfida"
123 = "Scegli Avversari"
124 = "Salto a"
125 = "Vento?"
126 = "Giro?"
127 = "Torna al Menu Principale"
128 = "Nuovo Record del Set Personalizzato!"
129 = "Vecchio Record:"
130 = "K.O.T.H Livello di Sfida"
131 = "LA SFIDA FINALE"
132 = "TIPI DURI"
133 = "INFRAZIONE DI VARIAZIONE"
134 = "COMPLETAMENTE BATTIBILE"
135 = "LA CASA DELLA VECCHIA GENTE"
136 = "PICCOLE DONNE IN ABITI ROSA"
137 = "PERSONALIZZATO"
138 = "Seleziona i tuoi Avversari"
139 = "Usa le frecce per Selezionare il Livello"
140 = "ENTER sceglie, ESC esce"
141 = "Nome"
142 = "Posizione"
143 = "Il Re!"
146 = "(Usa le frecce, ENTER, DEL o ESC)"
150 = "(Usa frecce, ENTER o ESC)"
151 = "Dove"
152 = "Vuoi Saltare"
153 = "Oggi?"
154 = "Uscita"
155 = "Collina WC Casuale"
156 = "Altre Colline..."
157 = "Pagina"
158 = "Pagina Successiva"
159 = "Pagina Precedente"
160 = "Sfide del Re della Collina"
161 = "Non Completato"
162 = "Migliori Salvati della Collina Personalizzata"
163 = "Risultati Top 20 Coppa del Mondo SJ3"
164 = "Risultati Top 10 Coppa a Squadra"
165 = "Punteggi Top 5 del Giro delle 4 Colline"
166 = "Nome"
167 = "Pos"
168 = "Punti"
169 = "Dove?"
170 = "Record della Collina"
171 = "Chi?"
172 = "Quanto?"
173 = "File"
174 = "Pti"
175 = "Menu Principale Setup"
176 = "Queste sono Opzioni Generali"
177 = "Alcune Opzioni sui Salti"
178 = "Alcune Opzioni sugli Alti Punteggi"
180 = "Oh Si"
181 = "Certo"
182 = "Sissignore"
183 = "Si"
184 = "Si"
185 = "Oh No"
186 = "Non esiste"
187 = "Negativo"
188 = "No"
189 = "Noo"
190 = "Resetta"
191 = "Zero"
192 = "Gli Alti Punteggi?"
193 = "Sei sicuro?"
194 = "Da Cancellare"
195 = "Uscita dal Setup"
196 = "Opzioni Generali"
197 = "Opzioni di Salto"
198 = "Alti Punteggi e Opzioni Setup"
199 = "Personalizza Tasti"
200 = "Stabilisci Obiettivo del Record della Collina"
201 = "Costruttore della Collina"
203 = "Torna al Setup Principale"
204 = "Lingua?"
205 = "Bip?"
206 = "Livello di Dettaglio della Grafica?"
207 = "Insieme Nomi degli Avversari del Computer (NOMI?.SCI)?"
208 = "Le voci in grigio sono"
209 = "disponibili solo nella versione Registrata"
211 = "Torna al Setup Principale"
212 = "Giri di Pratica?"
213 = "Statistiche Extra?"
214 = "Mostra Tabella Punteggi con Differenziali?"
215 = "Mostra Classifica della Coppa del Mondo con Differenziali?"
216 = "Tabella Punteggi Compatta?"
217 = "Sfondo Tabella Punteggi Invisible?"
218 = "Tenere Sempre Record della Collina?"
219 = "Formula Obiettivi del Record della Collina?"
220 = "Seleziona Saltatori del Computer Visti?"
221 = "Seleziona Posizione Segnavento"
222 = "Usare il KO-sistema in 4 colline?"
225 = "Esci Setup degli Alti Punteggi"
226 = "I Saltatori del Computer possono saltare i Record della Collina?"
227 = "Ammetti molti Nomi identici sulla Lista"
228 = "Resetta Alti Punteggi"
229 = "Azzera Alti Punteggi"
230 = "Torna ai Valori Predefiniti di Setup"
231 = "Mai"
232 = "Non in 4H"
233 = "Sempre"
235 = "Leader"
236 = "Top 3"
237 = "Top 5"
238 = "Top 10"
239 = "Tutti!"
240 = "Nessuno"
242 = "Obiettivo"
243 = "Usa le frecce, ESC uscita"
245 = "Te ne vai gia'?"
246 = "PREC"
247 = "SUCC"
248 = "FATTO"
251 = "Allora te ne vai..."
252 = "Vuoi veramente andartene?"
253 = "Oh, te ne vai cosi' presto?"
256 = "Sei sicuro di questo?"
257 = "Sei assolutamente certo?"
258 = "Di Y per uscire ora."
261 = "Ahoy! Devi avere quattro (4)"
262 = "oppure otto (8) giocatori registrati"
263 = "prima di entrare la Coppa a Squadre!"
264 = "Chiedi ai tuoi amici di partecipare"
265 = "oppure clona te stesso quattro volte."
270 = "SJ3 Costruttore della Collina"
271 = "(usa frecce, DEL,"
272 = " ENTER o ESC)"
273 = "Nome del File"
274 = "Nome della Collina"
275 = "*Aggiungi Nuova Collina*"
276 = "-Uscita-"
277 = "-Inizio-"
278 = "Prova la tua Collina!"
280 = "Freccia Su"
281 = "Freccia Sinistra"
282 = "Freccia Destra"
283 = "Freccia Giu"
285 = "(L)oad set"
286 = "(S)ave set"
287 = "(R)andom set"
288 = "S(O)rt by WC Points"
289 = "S(O)rt by Total Points"
290 = "Nessun Replay Trovato!"
291 = "Autore:"
292 = "Nome:"
293 = "Nome del File:"
294 = "Collina:"
295 = "Esci, non salvare"
296 = "Esci e salva"
298 = "(S)alva Replay"
300 = "Saltatori"
301 = "Seleziona Saltatori"
302 = "*Crea Nuovo Saltatore*"
304 = "Nome:"
305 = "Nome vero:"
306 = "Colore Divisa:"
307 = "Colore Sci:"
308 = "Riserva:"
309 = "Allenatore:"
310 = "Pass Elim.:"
311 = "Resetta Saltatori"
312 = "Uscita"
313 = "Totale Salti:"
314 = "Coppe del Mondo Completate:"
315 = "Frazioni vinte:"
316 = "Coppe del Mondo vinte:"
317 = "Migliori Risultati della Coppa del Mondo:"
318 = "Migliori delle 4 Colline:"
319 = "Salto piu' lungo della Coppa del Mondo:"
320 = "Salto piu' Lungo:"
321 = "Livello KOTH:"
322 = "(Usa frecce,"
323 = "ENTER edita saltatori,"
324 = "DEL rimuovi dall'ordine)"
325 = "ENTER registra,"
326 = "DEL cancella saltatori)"
328 = "Cancella saltatori"
329 = "Risettaggio saltatore"
330 = "Mappa tasti"
331 = "Decollo"
332 = "Ruota in avanti"
333 = "Ruota indietro"
334 = "Telemark atterraggio"
335 = "Atterraggio a 2 gambe"
336 = "Ritorna Default"
337 = "Esci"
340 = "Tempo in Sospensione"
341 = "Lunghezza"
342 = "Velocita':"
343 = "Personale"
345 = "Gia' esiste"
346 = "Sovrascrivere?"
350 = "Il Replay e' stato salvato."
351 = "Il Replay non e' stato salvato."
352 = "Il Set Personalizzato e' stato salvato."
353 = "Il Set Personalizzato non e' stato salvato."
354 = "La Collina Extra e' stata salvato."
355 = "La Collina Extra non e' stata salvato."
356 = "Nessun Set Personalizzato Trovato!"
360 = "Benvenuti in SJ3 e nello sport del Salto con gli Sci."
361 = "Qui c'e' una rapida introduzione al gioco."
362 = "L'idea in questo sport e' di volare il piu' lungo"
363 = "possibile e atterrare in modo sicuro."
364 = "Il tuo saltatore siede su una barra all'inizio"
365 = "del turno.  Usa Freccia Destra per iniziare a scivolare."
366 = "Il Segnavento e' situato in basso a sinistra. Vento"
367 = "contrario (negativo) e' migliore poiche' aumenta la spinta in alto."
368 = "Il segreto per un salto valido e' la scelta del tempo del"
369 = "decollo.  Usa Freccia Su per iniziare il decollo."
370 = "Ora dovresti ruotare il saltatore in avanti per"
371 = "diminuire la resistenza del vento.  Usa Freccia Destra."
372 = "A volte un colpo di vento potrebbe farti"
373 = "sbilanciare.  Usa Freccia Sinistra per ribilanciarti."
374 = "All'avvicinarsi della terra sarebbe saggio"
375 = "iniziare a pensare a far atterrare il tuo saltatore in modo sicuro."
376 = "Il tasto 'T' inizia l'atterraggio Telemark.  E'"
377 = "piu' lento e piu' insicuro ma premiato in punti per stile."
378 = "Il tasto 'R' inizia il piu' sicuro atterraggio a 2 piedi,"
379 = "e' piu' sicuro e buono per salti lunghi."
380 = "E' tutto! Puoi tornare a questa introduzione ancora dal"
381 = "menu Replay e per ulteriori informazioni, leggi MANUAL.TXT."
390 = "Alto"
391 = "Centro"
392 = "Basso"
393 = "Sinistra"
394 = "Centro"
395 = "Destra"
396 = "Saltatore"
400 = "Angolo dell'Allenatore:"
401 = "Professionale"
402 = "Prova a non permettere alla posizione di volo di essere cosi' bassa."
403 = "Buona posizione in volo."
404 = "La tua posizione di volo e' troppo eretta."
405 = "Fa un atterraggio la prossima volta."
406 = "Inizia l'atterraggio prima."
407 = "Uuh, sfortuna su quello."
410 = "Pessimo salto."
411 = "Non e' buono ancora."
412 = "Quello e' un salto abbastanza buono."
413 = "Buon salto."
414 = "Salto Eccellente!"
415 = "Incredibile!  Dov'e' il tuo mantello?"
418 = "Inizia il decollo molto prima."
419 = "Il decollo era troppo tardi."
420 = "Tempismo e' ancora un po' in ritardo."
421 = "Tempismo migliore questa volta."
422 = "Tempismo perfetto per il decollo!"
423 = "Eri un po' troppo in anticipo sul decollo."
424 = "Non iniziare il decollo cosi' presto."
425 = "Decollo orribile. Inizialo molto piu' tardi."
428 = "Intendo molto piu' presto."
429 = "Questa volta era troppo in ritardo."
430 = "L'atterraggio era a mala pena in tempo."
431 = "Tempismo ok in atterraggio."
432 = "Quello dovrebbe dare buoni punti per lo stile."
433 = "Avresti potuto aspettare di piu' prima di atterrare."
434 = "Non aver paura di volare piu' lungo."
435 = "Premi 'T' o 'R', prego."
441 = "Rilassato"
442 = "Aw, non ruotare troppo il salto, amico."
443 = "Quella e' una posizione di volo carina."
444 = "Non aver paura di inclinarti in avanti di piu', figliolo."
445 = "Per favore atterra la prossima volta, quello fa male."
446 = "Stai ancora atterrando di faccia, ragazzo."
447 = "Be', non puoi sopportarli tutti, sai."
450 = "Quello e' troppo rilassato."
451 = "Be', prova a non esercitarti."
452 = "Quello sembra un po' piu' corretto."
453 = "Ora quello e' cio' che chiamo un buon volo."
454 = "Oh si, alle ragazze piacera' quello!"
455 = "Grande! Vorrei che tu incontrassi Superman!"
458 = "Che decollo da culo pigro..."
459 = "Se vuoi volare, decolla prima."
460 = "Il tuo tempismo non e' buono."
461 = "Tempismo abbastanza buono fuori tabella, amico."
462 = "Hey, Mi e' piaciuto il tuo decollo!"
463 = "Il decollo era appena in anticipo."
464 = "Non aver fretta col decollo."
465 = "Ooh, ti farai male qualche giorno."
468 = "Dovresti probabilmente lavorare sull' atterraggio"
469 = "Non hai paura di morire?.."
470 = "Whew, quell'atterraggio era proprio al bordo."
471 = "Atterraggio - Solido come una Roccia."
472 = "Ooh, Signor Atterraggio Morbido e' in Citta'."
473 = "Non affrettare quella sensazione di atterraggio..."
474 = "Non aver fifa sul volo."
475 = "Non aver paura della tastiera, amico."
481 = "Severo"
482 = "Sei troppo in avanti nel volo, ciuccio."
483 = "Posizione di volo decente."
484 = "Buono a nulla! Ruota il salto da uomo."
485 = "Oh Dio! Dove e' l'atterraggio?"
486 = "No! Inizia il maledetto atterraggio in tempo!"
487 = "Alza il culo e torna al lavoro!"
490 = "Non ho mai visto un salto peggiore."
491 = "Mia madre salta meglio."
492 = "Che c'e'? Vuoi andare a casa dalla mamma?"
493 = "Puoi fare molto meglio."
494 = "Alcuni allenatori sarebbero contenti con quello."
495 = "Ora stai saltando come ti ho detto."
498 = "Orribile! Dov'e' il dannato decollo!"
499 = "Decollo ancora in ritardo. 50 flessioni!"
500 = "Il tuo tempismo e' ancora pessimo. 25 flessioni!"
501 = "Non puoi decollare un po' prima?"
502 = "Ora il decollo era cio' che volevo."
503 = "Troppo presto!  Non puoi imparare?"
504 = "Decollo Catastrofico! Dammi 50 flessioni!"
505 = "Non ho mai visto un decollo peggiore. Vai a casa."
508 = "L'atterraggio e' troppo duro, cocco di mamma?"
509 = "No! Inizia il dannato atterraggio in tempo!"
510 = "Quell'atterraggio e' troppo rischioso."
511 = "Quello sembrava quasi un atterraggio."
512 = "Suppongo che era un atterraggio ok."
513 = "Non ti imbranare nell'atterraggio."
514 = "Di cosa hai paura? Vola, dannazione!"
515 = "Sei stupido? Atterra o vai a casa!"
520 = "Load Cup"
521 = "Save cup state?"
522 = "Current jump is lost."
523 = "No saved cups"
524 = "MULTIPLAYER"
