id = "norsk"
name = "Norsk"

[strings]
1 = "En"
2 = "To"
3 = "Tre"
4 = "Fire"
5 = "Fem"
6 = "Ja"
7 = "Nei"
8 = "av"
9 = "Ingen"
11 = "Registrert"
12 = "Shareware"
13 = "Normal"
14 = "Lav"
15 = "Press a key..."
17 = "Hoved Meny"
18 = "Hopp Meny"
20 = "Hopp!"
21 = "Skriv inn Navn"
22 = "Innstillinger"
23 = "Rekorder"
24 = "Bakkerekorder"
25 = "Repriser"
26 = "Avslutt SJ3"
27 = "SJ3 Verdens Cup"
28 = "Egen Verdens Cup"
29 = "Tysk/¥st. Hoppuka"
30 = "Laghopping"
31 = "Kongen av Bakken"
32 = "Trening"
33 = "Til Hoved Menyen"
34 = "Hoppere:"
35 = "Denne versjonen"
36 = "er registrert til:"
38 = "Dette er en uregistrert"
39 = "versjon av SJ3."
40 = "Les Register.Txt Nå!"
41 = "Hvordan du kan bli den kuleste"
42 = "personen i gata,"
43 = "Vil du ha mer respekt fra"
44 = "vennene dine?  Registrer SJ3!"
45 = "Dette er ikke et gratis spill."
46 = "Gj¥r det rette, register."
47 = "Bare To Spillere Tillat"
48 = "i denne Uregistrerte versjonen"
51 = "Trening"
52 = "Pr¢ve Omgang"
53 = "Kvalifiserings Runde"
54 = "F¢rste Omgang"
55 = "Andre Omgang"
56 = "Nestemann ut..."
57 = "Datastyrte hoppere..."
58 = "Avsats:"
59 = "Trykk (I) for innstillinger"
60 = "I"
61 = "For ¢yeblikket"
62 = "Trenger for å lede"
63 = "Trenger for å vinne"
65 = "Bakkerekord"
67 = "Hoppere Igjen:"
68 = "Trenger for å slå:"
69 = "På Sisteplass for ¢yeblikket:"
70 = "Current WC Standings"
71 = "Current TC Standings"
75 = "Mister Neste"
76 = "Konkurranser"
77 = "Runde"
78 = "Konkurranse"
79 = "er diskvalifisert!"
81 = "Resultat - Bakke"
82 = "Kvalifisering - Bakke"
83 = "av 4"
84 = "Den Tysk/¥st. Hoppuka - Bakke"
85 = "Resultater etter den Tysk/¥st. Hoppuka"
86 = "(begrenset liste)"
87 = "Stillingen etter Bakke"
88 = "Hopper"
89 = "Verdens Cup Statistikk for"
90 = "Sluttresultat av"
91 = "Resultater etter Lagkonkurranse Bakke"
92 = "Sluttresultat etter Lagkonkurransen"
93 = "Lagkonkurranse Statistikk for"
94 = "Knock-out system parene"
95 = "Stillingen"
96 = "Kongen av Bakken"
97 = "Poeng"
98 = "VC"
99 = "Tysk/¥sterriske:"
100 = "Totalt:"
101 = "Ut av Konkurransen:"
102 = "Hopper ikke lenger:"
103 = "Eliminerte Hoppere:"
104 = "I garderoben:"
105 = "Ikke sammen med oss lenger:"
106 = "Hvor?"
107 = "Lag:"
108 = "Stl"
109 = "Poeng"
110 = "TC"
111 = "Gj¢r deg klar til Lagkonkurransen"
112 = "Program for Lagkonkurransen:"
113 = "Skriv inn navn på laget"
114 = "Lag"
115 = "Beste Resultat:"
116 = "Åpne Custom Hill Set"
117 = "Lagre Custom Hill Set"
118 = "Velg bakker for din egen Verdens Cup"
119 = "Bruk piltaster, ENTER starter, ESC Exit"
120 = "Datahoppere:"
121 = "Start *Kongen av Bakken*"
122 = "Velg Vansklighetsgrad"
123 = "Velg Motstandere"
124 = "Hopper i"
125 = "Vind?"
126 = "Runder?"
127 = "Tilbake Til Hovud Meny"
128 = "Ny Custom Set Rekord!"
129 = "Gammel Rekord:"
130 = "Vansklighetsgrad"
131 = "DEN ULTIMATE UTFORDRING"
132 = "VANSKLIG OPPGAVE"
133 = "VARIERT MOTSTAND"
134 = "IKKE FOR VANSKELIG"
135 = "GAMLEHJEMMET"
136 = "SMÅ JENTER"
137 = "CUSTOM"
138 = "Velg dine Motstandere"
139 = "Bruk Pilene for å velge Vansklighetsgrad"
140 = "ENTER velger, ESC avslutter"
141 = "Navn"
142 = "Rangering"
143 = "Kongen!"
146 = "(Bruk pilene, ENTER, DEL or ESC)"
150 = "(Bruk pilene, ENTER or ESC)"
151 = "Hvor Vil Du"
152 = "Hoppe"
153 = "I Dag?"
154 = "Avslutt"
155 = "Tilfeldig VC Bakke"
156 = "Flere Bakker..."
157 = "Side"
158 = "Neste Side"
159 = "Forrige Side"
160 = "Kongen av Bakken Utfordringer"
161 = "Ikke fullf¥rt"
162 = "Saved Custom Hill Bests"
163 = "Topp 20 SJ3 Verdens Cup Resultat"
164 = "Topp 10 Lagkonkurranse Resultat"
165 = "Topp 5 Tysk/¥sterriske Hoppuka Resultat"
166 = "Navn"
167 = "Pos"
168 = "Poeng"
169 = "Når?"
170 = "Bakkerekordene"
171 = "Hvem?"
172 = "Hvor mye?"
173 = "File"
174 = "Pts"
175 = "Innstillinger"
176 = "Hovedinnstillinger"
177 = "Hoppinnstillinger"
178 = "Noen Innstillinger Vedr¢rende Rekorder"
180 = "Jaja!"
181 = "Såklart"
182 = "Ja"
183 = "Jepp!"
184 = "Ja"
185 = "Nei"
186 = "Ikke på tale!"
187 = "Nei"
188 = "Nei"
189 = "Nei"
190 = "Tilbakesktill"
191 = "Nullstill"
192 = "Bakkerekordene?"
193 = "Er Du Sikker"
194 = "Slette?"
195 = "Avslutt innstillingene"
196 = "Hovedinnstillingene"
197 = "Hoppinnstillingene"
198 = "¥vrige innstillinger"
199 = "Tilpass taster"
200 = "Sett mål for bakkerekorder"
201 = "Lag en ny bakke"
203 = "Tilbake til innstillingene"
204 = "Språk?"
205 = "PC lyd?"
206 = "Grafikknivå?"
207 = "Motstandere (NAMES?.SKI)?"
208 = "Det i grått er bare"
209 = "tilgjenglig når du registrerer SJ3"
211 = "Tilbake til Hovedinnstillingene"
212 = "Trenings Runde?"
213 = "Ekstra Statistikk?"
214 = "Vis Resultattavlen med forskjeller?"
215 = "Vis VC liste med forskjeller?"
216 = "Kompakt Resultattavle?"
217 = "Usynlig Resultattavle Bakgrunn?"
218 = "Lagre repriser på bakkerekorder automatisk?"
219 = "Sett opp bakkerekord mål?"
220 = "Ser hvor mange datastyrte hoppere?"
221 = "Velg plassering av vindmåler"
222 = "Bruk knock-out systemet i hoppuken?"
225 = "Tilbake Til innstillingene"
226 = "Kan Datahoppere Sette Bakkerekorder?"
227 = "La Det Vere Flere Like Navn på Listen?"
228 = "Tilbakestill Rekorder"
229 = "Slett Rekorder"
230 = "Tilbakestill Innstillingene"
231 = "Aldri"
232 = "Ikke i hoppuken"
233 = "Alltid"
235 = "Lederen"
236 = "Topp3"
237 = "Topp5"
238 = "Topp10"
239 = "Alle!"
240 = "Ingen"
242 = "Mål"
243 = "Bruk piltaster, ESC exit"
245 = "Drar du allerede?"
246 = "FORG"
247 = "NEST"
248 = "FRDG"
251 = "Så du drar..."
252 = "Vil du avslutt SJ3?"
253 = "Åh, drar du så tidlig?"
256 = "Er du sikker på det her?"
257 = "Er du helt sikker?"
258 = "Skriv J for å avslutt no!"
261 = "Hey! Du må ha fire (4)"
262 = "eller åtte (8) hoppere skrevet opp"
263 = "f¢r du starter Lagkonkurransen!"
264 = "Gå å sp¢r noen av vennene dine om de vil vere med"
265 = "eller bare klon deg selv flere ganger!"
270 = "SJ3 Bakkelager"
271 = "(bruk pilene, DEL,"
272 = " ENTER eller ESC)"
273 = "Filnavn"
274 = "Bakkenavn"
275 = "*Lag Ny Bakke*"
276 = "-Avslutt-"
277 = "-Start-"
278 = "Test Bakken Din!"
280 = "Piltast Frem"
281 = "Piltast Venstre"
282 = "Piltast H¢gre"
283 = "Piltast Ned"
285 = "(L)oad set"
286 = "(S)ave set"
287 = "(R)andom set"
288 = "S(o)rter etter WC poeng"
289 = "S(o)rter etter Total poengsum"
290 = "Ingen repriser funnet!"
291 = "Hopper:"
292 = "Navn:"
293 = "Filenavn:"
294 = "Bakke:"
295 = "Gå ut, Ikke lagre"
296 = "Gå ut og lagre"
298 = "(L)agre Reprise"
300 = "Hoppere"
301 = "Velg Hoppere"
302 = "*Lag ny hopper*"
304 = "Navn:"
305 = "Ekte Navn:"
306 = "Dress farge:"
307 = "Ski farge:"
308 = "Erstatt:"
309 = "Trener:"
310 = "Hopp over kvali?"
311 = "Nullstill hopper"
312 = "Tilbake"
313 = "Totalt antall hopp:"
314 = "Verdenscuper gjennomf¥rt:"
315 = "Renn vunnet:"
316 = "Verdenscuper vunnet:"
317 = "Beste VC Resultat:"
318 = "Beste Hoppuke:"
319 = "Lengste VC hopp:"
320 = "Lengste hopp:"
321 = "KAB Nivσ:"
322 = "(Bruk piltaster,"
323 = "ENTER editer hopper,"
324 = "DEL sletter fra listen)"
325 = "ENTER för opp,"
326 = "DEL slett hopper)"
328 = "Slett hopper"
329 = "Resetting jumper"
330 = "Keymap"
331 = "Take-off"
332 = "Roter framover"
333 = "Roter bakover"
334 = "Telemark landing"
335 = "To-fots landing"
336 = "Returner til defaults"
337 = "Exit"
340 = "Tid i lufta"
341 = "Lengde"
342 = "Fart:"
343 = "Custom"
345 = "Eksisterer allerede."
346 = "Lagre Over?"
350 = "Reprisen er lagret."
351 = "Reprisen er ikke lagret."
352 = "Custom set er lagret."
353 = "Custom set er ikke lagret."
354 = "Ekstra bakke lagret."
355 = "Ekstra bakke er ikke lagret."
356 = "Ingen Custom Sets Funnet!"
360 = "Velkommen til SJ3 og skihopping."
361 = "Her er ein rask introduksjon av spillet."
362 = "Poenget med skihopping er å hoppe så langt"
363 = "som mulig og lande uten å skade seg."
364 = "Hopperen din sitter på bommen på toppen"
365 = "av bakken.  Bruk h¢gre piltast for å starte."
366 = "Vindmåleren er nede I venstre hj¢rne av"
367 = "skjermen. Vind I mot er best for det ¢ker l¢ftet."
368 = "N¢kkelen til et suksessfult hopp er timingen av"
369 = "take-off.  Bruk piltast opp for å starte take-off."
370 = "Du skal nå rotere hopperen framover for å"
371 = "minske luftmotstanden.  Bruk h¢gre piltast."
372 = "Av og til kan vinden kaste deg ut av balanse."
373 = "Bruk venstre piltast for å fikse posisjonen."
374 = "Når bakken nermer seg vil det vere fornuftig å"
375 = "tenke på å lande hopperen trygt."
376 = "'T' tasten starter telemark landing. Det tar lengre"
377 = "tid og er mer utrygt men gir bedre stilkarakterer."
378 = "'R' tasten starter den trygge  to-fots landingen,"
379 = "som er bra for lange hopp."
380 = "Det var det! Du kan se denne introen igjen fra"
381 = "Reprise menyen og for mer info, les MANUAL.TXT."
390 = "Toppen"
391 = "Midten"
392 = "Bunnen"
393 = "Venstre"
394 = "Midten"
395 = "H°gre"
396 = "Hopper"
400 = "Trenern:"
401 = "Profesjonell"
402 = "Pr¢v å ikke la flygestillingen bli så lav."
403 = "Bra Flygestilling i Lufta."
404 = "Flygestillingen din er for oppreist!"
405 = "Land neste gang da."
406 = "Start landingen tidligere."
407 = "Uuh, uflaks."
410 = "Det var et dårlig hopp."
411 = "Det ser fortsatt ikke bra ut."
412 = "Det var et brukbart hopp."
413 = "Bra hopping."
414 = "Nydelig hopp!"
415 = "Utrolig! Er du Supermann?"
418 = "Ta av fra hoppkanten mye tidligere."
419 = "Du tok av for seint."
420 = "Timingen er fortsatt ikke bra."
421 = "Bedre timing denne gangen."
422 = "Perfekt timing på hoppkanten!"
423 = "Du tok av litt for tidlig på hoppkanten."
424 = "Ikke ta av så tidlig."
425 = "Det var et forferdelig hopp. Ta av tidligere."
428 = "Jeg mener mye tidligere."
429 = "Det var akkurat for sent denne gangen."
430 = "Landingen var akkurat i tide."
431 = "Bra timing på landingen."
432 = "Det vil gi deg gode stilpoeng."
433 = "Du kunne ikke ventet lengre f¢r du landet."
434 = "Ikke v'r redd for å fly lengre."
435 = "Trykk 'T' eller 'R'!!!"
441 = "Avslappet"
442 = "Åhh, du kan ikke lene deg så mye bakover, kompis."
443 = "Fin flygeposition."
444 = "Ikke v'r redd for å lene deg lenger framover."
445 = "V'r så snill å land neste gang da, det må jo v're vondt."
446 = "Du lander fortsatt på ansiktet, gutt."
447 = "Jaja, du kan ikke lande på alle hoppene, veit du."
450 = "Der var du litt for avslappet."
451 = "Bra landing."
452 = "Nå ser det bedre ut."
453 = "Det er hva jeg kaller fin flyging."
454 = "Jada, damene kommer til å like det hoppet!"
455 = "Det var nydelig! Jeg vil at du skal m¢te Superman!"
458 = "Der bommet du totalt på hoppkanten."
459 = "Hvis du vil fly, må du ta av tidligere."
460 = "Timingen din er ikke helt perfekt."
461 = "Ganske bra timing ut i fra hoppet."
462 = "Hey, Der traff du perfekt!"
463 = "Du tok av litt for seint der."
464 = "Ikke ha det travelt på hoppkanten."
465 = "Ooh, du kommer til å skade deg en dag."
468 = "Du må nok jobbe litt mer med landingen."
469 = "Er du ikke redd for å d¢?.."
470 = "Wow, den landingen var på kanten."
471 = "Landingen satt som en stein."
472 = "Ooh, Hr. Perfekt landing."
473 = "Den landingen var i siste sekund."
474 = "Ikke v'r redd for å fly lengre."
475 = "Tastaturet biter ikke."
481 = "Streng"
482 = "Du lener deg for langt frem, tosk."
483 = "Det er en brukbar flygestilling."
484 = "Pingle! Roter forover som en mann."
485 = "Herre Gud! Hvor er landingen da?"
486 = "Nei! Start den forbanna landingen i tide!"
487 = "Du kan nå fors¢ke å hoppe da!!!"
490 = "Jeg har aldri i mitt liv sett et dårligere hopp."
491 = "Moren min hopper bedre enn det!."
492 = "Hva er feil? Vil du hjem til Mamma?"
493 = "Du kan hoppe mye bedre enn det."
494 = "Enkelte trenere ville blitt glade for det."
495 = "Nå hopper du som jeg har l'rt deg."
498 = "Forferdelig! Når tok du av fra hoppkanten?!"
499 = "Du tok av for sent. 50 armhevinger!"
500 = "Timingen er fortsatt dårlig. 25 armhevinger!"
501 = "Kan du ikke ta av litt fortere da?"
502 = "Nå traff du slik jeg vil at du skal gj¢re."
503 = "For tidlig!  Kan du ikke l're?"
504 = "Katastrofalt på hoppkanten! Gi meg 50 armhevinger!"
505 = "Jeg har aldri sett noen bomme slik på hoppkanten som du gj¢r. Gå hjem."
508 = "Er landingen for vansklig, mammadalt?"
509 = "Nei! Start landingen i tide!"
510 = "Den landingen er for farlig."
511 = "Det så nesten ut som en landing."
512 = "Det var en ok landing."
513 = "Ikke v'r redd når du skal lande."
514 = "Hva er du redd for?, fly da!"
515 = "Er du dum? Land eller gå hjem!"
520 = "Load Cup"
521 = "Save cup state?"
522 = "Current jump is lost. (Y/N)"
523 = "No saved cups"
