id = "polski"
name = "Polski"

[strings]
1 = "Jeden"
2 = "Dwa"
3 = "Trzy"
4 = "Cztery"
5 = "Piec"
6 = "Tak"
7 = "Nie"
8 = "z"
9 = "Zaden"
11 = "Zarejestrowana"
12 = "Shareware"
13 = "Normalny"
14 = "Niski"
15 = "Nacisnij jakis klawisz..."
17 = "Menu Glowne"
18 = "Menu skokow"
20 = "Skacz!"
21 = "Wpisz skoczkow"
22 = "Opcje"
23 = "Najlepsze wyniki"
24 = "Rekordy skoczni"
25 = "Powtorki"
26 = "Wyjscie z SJ3"
27 = "Puchar Swiata SJ3"
28 = "Wlasny Puchar"
29 = "Turniej 4 skoczni"
30 = "Konkurs Druzynowy"
31 = "Krol skoczni"
32 = "Praktyka"
33 = "Powrot do Menu"
34 = "Skoczkowie:"
35 = "Ta wersja SJ3"
36 = "jest zarejestrowana dla:"
38 = "To jest niezarejestrowana"
39 = "wersja SJ3."
40 = "Przeczytaj Register.Txt!"
41 = "Badz nalpeszym gosciem"
42 = "w okolicy. Zarejestruj!!!"
43 = "Chcesz byc szanowany przez kumpli?"
44 = "Zarejestruj!!!"
45 = "To nie jest darmowa gra."
46 = "Zrob to co powinienes - zarejestruj."
47 = "Tylko do dwoch graczy!!!"
48 = "Zarejestruj SJ3!!!"
51 = "Praktyka"
52 = "Trening"
53 = "Kwalifikacje"
54 = "Runda 1"
55 = "Runda 2"
56 = "Nastepny..."
57 = "Skoczkowie komputerowi..."
58 = "Belka startowa:"
59 = "Nacisnij (O) aby ustawic Opcje"
60 = "O"
61 = "Aktualnie"
62 = "Do prowadzenia"
63 = "Do wygrania"
65 = "Rekord skoczni"
67 = "Pozostalo Skoczkow:"
68 = "Do Prowadzenia:"
69 = "Aktualnie Ostatni:"
70 = "Aktualna klasyfikacja PS"
71 = "Aktualna klasyfikacja PD"
75 = "Opuszczasz"
76 = "Konkursy"
77 = "Runde"
78 = "Konkurs"
79 = "jest Zdyskwalifikowany!"
81 = "Tabela - Konkurs"
82 = "Kwalifikacje - Konkurs"
83 = "z 4"
84 = "Turniej 4 skoczni - Konkurs"
85 = "Koncowe Wyniki Turnieju Czterech Skoczni"
86 = "Lista..."
87 = "Wyniki po:"
88 = "Skoczek"
89 = "Statystyki Pucharu Swiata:"
90 = "Koncowe wyniki"
91 = "Wyniki druzynowego PS po:"
92 = "Koncowe wyniki konkursu druzynowego"
93 = "Statystyki druzynowe"
94 = "System Nokautu par"
95 = "Klasyfikacja"
96 = "Krol skoczni"
97 = "Wynik"
98 = "PS"
99 = "TCS:"
100 = "Razem:"
101 = "Po za Zawodami:"
102 = "Nie skacza:"
103 = "Wyeliminowani:"
104 = "W szatni:"
105 = "Nie obchodza nas:"
106 = "Gdzie?"
107 = "Druzyna:"
108 = "Poz"
109 = "Pkt"
110 = "PD"
111 = "Przygotuj sie do Konkursu"
112 = "Sklad druzyny:"
113 = "Nazwij druzyne"
114 = "Druzyna"
115 = "Najlepszy wynik"
116 = "Wczytaj zestaw skoczni"
117 = "Zapisz zestaw skoczni"
118 = "Wybierz skocznie do twojego Pucharu"
119 = "Uzyj strzalek, ENTER wybiera, ESC wychodzi"
120 = "Komputerowi skoczkowie:"
121 = "Rozpocznij *Krola skoczni*"
122 = "Poziom Trudnosci"
123 = "Wybierz Przeciwnikow"
124 = "Skaczesz na"
125 = "Wiatr?"
126 = "Runda?"
127 = "Wroc Menu"
128 = "Nowy rekord zestawu skoczni!"
129 = "Stary rekord:"
130 = "K.S. Poziom trudnosci"
131 = "DLA MISTRZOW SWIATA"
132 = "JESTES DOBRY?"
133 = "DLA NIEZLYCH SKOCZKOW"
134 = "SLABEUSZE"
135 = "BULKA Z MASLEM"
136 = "DLA MALYCH DZIEWCZYNEK"
137 = "WLASNY"
138 = "Wybierz swoich przeciwnikow"
139 = "uzywaj strzalek by wybrac poziom"
140 = "ENTER wybiera, ESC wychodzi"
141 = "Imie"
142 = "Miejsce"
143 = "Krol!"
146 = "(Strzalki, ENTER, DEL lub ESC)"
150 = "(Strzalki, ENTER lub ESC)"
151 = "Gdzie"
152 = "chcesz dzisiaj"
153 = "skakac?"
154 = "Wyjscie"
155 = "Losowa skocznia"
156 = "Wiecej skoczni..."
157 = "Strona"
158 = "Nastepna strona"
159 = "Poprzednia strona"
160 = "Krol Skoczni"
161 = "Nie ukonczyl"
162 = "Zapisano najlepsze wyniki zestawu"
163 = "Najlepsze 20 wynikow PS"
164 = "Najlepsze 20 wynikow PD"
165 = "Najlepsze wyniki konkursu 4 skoczni"
166 = "Imie"
167 = "Poz"
168 = "Punkty"
169 = "Kiedy?"
170 = "Rekordy skoczni"
171 = "Kto?"
172 = "Ile?"
173 = "Plik"
174 = "Pkt"
175 = "To jest menu glowne"
176 = "To sa glowne opcje"
177 = "Kilka opcji skakania"
178 = "Kilka opcji wynikow"
180 = "O Tak"
181 = "Jasne"
182 = "Tak jest"
183 = "Spoko"
184 = "Tak"
185 = "O nie"
186 = "Nigdy"
187 = "Nie"
188 = "Nie"
189 = "Nieee"
190 = "Resetuj"
191 = "Zeruj"
192 = "Najlepsze wyniki?"
193 = "Jestes pewien?"
194 = "Zaraz skasujesz"
195 = "Wyjscie z opcji"
196 = "Opcje glowne"
197 = "Opcje skakania"
198 = "Wyniki i setup"
199 = "Ustaw klawiszologie"
200 = "Ustaw rekordy skoczni-Twoje cele"
201 = "Generator skoczni"
203 = "Wroc do opcji"
204 = "Jezyk?"
205 = "Beepniecia?"
206 = "Poziom grafiki?"
207 = "Imiona przeciwnikow (NAMES?.SKI)?"
208 = "Opcje w szarym kolorze"
209 = "Sa dostepne po rejestracji"
211 = "Powrot do Opcji"
212 = "Rundy Treningowe?"
213 = "Ekstra Statystyki?"
214 = "Pokaz tabele z roznicami?"
215 = "Pokaz klasyfikacje PS z roznicami?"
216 = "Skrocona wersja tablic z wynikami?"
217 = "Niewidoczne tlo tabeli?"
218 = "Automatycznie zapisuj powtorki rekordow?"
219 = "Pokazywac Twoje docelowe rekordy skoczni?"
220 = "Wybierz ogladanych skoczkow komputerowych?"
221 = "Wybierz polozenie wiatromierza"
222 = "Uzyj System Nokautu w Konkursie 4 Skoczni"
225 = "Wyjdz z opcji wynikow"
226 = "Czy komputer moze ustanowic rekord skoczni?"
227 = "Dopuszczaj takie same imiona"
228 = "Resetuj Wyniki"
229 = "Wyzeruj wyniki"
230 = "Przywroc standardowe opcje."
231 = "Nigdy"
232 = "Nie w 4 s"
233 = "Zawsze"
235 = "Lider"
236 = "Najlepsza 3"
237 = "Najlepsza 5"
238 = "Najlepsza 10"
239 = "Wszystkich!"
240 = "Zaden"
242 = "Cel"
243 = "Uzyj strzalek, ESC wychodzi"
245 = "Juz wychodzisz?"
246 = "POPR"
247 = "NAST"
248 = "O.K."
251 = "Wiec wychodzisz..."
252 = "Naprawde chcesz wyjsc?"
253 = "Tak szybko wychodzisz ?"
256 = "Jestes pewien?"
257 = "Jestes pewny na 100%?"
258 = "Nacisnij T zeby wyjsc."
261 = "HEJ! Musisz miec (4)"
262 = "lub (8) wpisanych graczy"
263 = "by zagrac konkurs druzynowy!"
264 = "Idz zalatw paru kumpli"
265 = "lub sklonuj samego siebie."
270 = "Generator skoczni"
271 = "(Strzalki, DEL,"
272 = " ENTER lub ESC)"
273 = "Nazwa pliku"
274 = "Nazwa skoczni"
275 = "*Dodaj nowa skocznie*"
276 = "-Wyjscie-"
277 = "-Start-"
278 = "Przetestuj swoja skocznie!"
280 = "Arrow Up"
281 = "Arrow Left"
282 = "Arrow Right"
283 = "Arrow Down"
285 = "(W)czytaj zestaw"
286 = "(Z)apisz zestaw"
287 = "(L)osowy zestaw"
288 = "S(O)rtuj wg punktow Pucharu Swiata"
289 = "S(O)rtuj wg punktow lacznych"
290 = "Nie znaleziono zadnych powtorek!"
291 = "Autor:"
292 = "Nazwa:"
293 = "Nazwa pliku:"
294 = "Skocznia:"
295 = "Wyjdz nie zapisuj"
296 = "Zapisz i wyjdz"
298 = "(Z)apisz powtorke"
300 = "Skoczkowie"
301 = "Wybierz skoczkow"
302 = "*Stworz nowego skoczka*"
304 = "Imie:"
305 = "Pr. imie:"
306 = "Kolor kombinezonu:"
307 = "Kolo nart:"
308 = "Zamien:"
309 = "Trener:"
310 = "Bez kwalif.:"
311 = "Zresetuj skoczka"
312 = "Wyjscie"
313 = "Skokow w sumie:"
314 = "Ukonczone Puchary Swiata:"
315 = "Wygrane Konkursy:"
316 = "Wygrane Puchary Swiata:"
317 = "Najlepszy wynik w PS:"
318 = "Najlepszy wynik w TCS"
319 = "Najdluzszy skok w PS:"
320 = "Najdluzszy skok:"
321 = "KOTH level:"
322 = "(Uzyj strzalek,"
323 = "ENTER edytuje skoczka,"
324 = "DEL usuwa go z kolejnosci)"
325 = "ENTER aby wybrac,"
326 = "DEL aby skasowac skoczka)"
328 = "Usun Skoczka"
329 = "Resetowanie skoczka"
330 = "Klawiszologia"
331 = "Wybicie"
332 = "Do przodu"
333 = "Do tylu"
334 = "Ladowanie z telemarkiem"
335 = "Ladowanie na obie nogi"
336 = "Przywroc domyslne"
337 = "Wyjscie"
340 = "Czas lotu"
341 = "Odleglosc"
342 = "Predkosc:"
343 = "Wlasny"
345 = "Juz istnieje"
346 = "Pisac ponad?"
350 = "Powtorka zostala pomyslnie zapisana."
351 = "Powtorka nie zostala zapisana."
352 = "Wlasny zestaw zostal zapisany."
353 = "Wlasny zestaw nie zostal zapisany."
354 = "Dodatkowa skocznia zostala zapisana."
355 = "Dodatkowa skocznia nie zostala zapisana."
356 = "Nie znaleziono wlasnych zestawow!"
360 = "Witaj w SJ3 i swiecie skokow narciarskich."
361 = "Oto krotki wstep do gry."
362 = "Istota tego sportu jest latac tak daleko"
363 = "jak tylko to mozliwe i ladowac bezpiecznie."
364 = "Twoj skoczek siedzi na belce na poczatku"
365 = "najazdu. Uzyj strzalki w prawo aby zaczac zjezdzac."
366 = "Wiatromierz jest usytulowany w lewym dolnym rogu."
367 = "Wiatr czolowy jest lepszy, gdyz daje wieksza nosnosc."
368 = "Kluczem do sukcesu w skokach jest dokladne"
369 = "wybicie. Aby sie wybic, nacisnij strzalke w gore."
370 = "Teraz powinienes nadac skoczkowi odpowiednia pozycje,"
371 = "aby zmniejszyc opor powietrza, uzyj strzalki w prawo."
372 = "Czasami, nagly powiew wiatru moze zaburzyc twoja"
373 = "pozycje w locie. Da sie to naprawic strzalka w lewo."
374 = "W miare zblizania sie do ziemi, powinnienes pomyslec"
375 = "o tym jak bezpiecznie wyladowac."
376 = "Klawisz 'T' rozpoczyna ladowanie telemarkiem. Jest"
377 = "wolniejsze i mniej bezpieczne, ale daje wyzsze noty."
378 = "Klawisz 'R' rozpoczyna pewniejsze ladowanie na 2 nogi,"
379 = "ktore przydaje sie szczegolnie w dalekich skokach."
380 = "I to  wszystko! Mozesz ponownie obejrzec to intro,"
381 = "wybieraj▌c je z 'Powtorek'. Wiecej o SJ3 w MANUAL.TXT."
390 = "Gora"
391 = "Srodek"
392 = "Dol"
393 = "Lewo"
394 = "Srodek"
395 = "Prawo"
396 = "Skoczek"
400 = "Trener:"
401 = "Profesjonalny"
402 = "Staraj sie tak nie wychylac."
403 = "Dobra sylwetka w locie."
404 = "Twoja pozycja w locie jest za wysoka."
405 = "Nastepnym razem wyladuj."
406 = "Zacznij ladawac wczesniej."
407 = "Uuu, miales pecha."
410 = "To byl kiepski skok."
411 = "Ciagle kiepsko to wyglada."
412 = "To calkiem dobry skok."
413 = "Dobry skok."
414 = "Swietny skok!"
415 = "Niewiarygodne? Gdzie ty ladujesz?"
418 = "Wyjdz z progu znacznie wczesniej."
419 = "Wybicie bylo za pozno."
420 = "Wybicie jest ciagle troche za pozno."
421 = "Tym razem lepsze wybicie."
422 = "Idealne wyjscie z progu!"
423 = "Troszke spozniles wybicie."
424 = "Nie wybijaj sie tak szybko."
425 = "To fatalne wyjscie z progu."
428 = "Mialem na mysli znacznie wczesniej."
429 = "Tym raze za pozno."
430 = "Ladowanie nie w tej chwili."
431 = "OK, dobre ladowanie."
432 = "Za to powinny byc dobre noty."
433 = "Moglbys poczekac troche z ladowaniem."
434 = "Nie boj sie leciec dalej."
435 = "Nacisnij 'T' lub 'R', prosze."
441 = "Zrelaksowany"
442 = "Nie wykladaj sie tak."
443 = "Pieknie leciales."
444 = "Nie boj siΩ wylozyc."
445 = "Sprobuj wyladowac nastepnym razem, to pomocne."
446 = "Caly czas ladujesz na pysku."
447 = "Nie mozesz ustac ich wszystkich."
450 = "To zbyt relaksujace."
451 = "Co to sa za skoki."
452 = "Rewelacyjne to nie bylo."
453 = "No, to jest ladny skok."
454 = "O tak, laski to pokochaja!"
455 = "To bylo wielkie!"
458 = "Co za beznadziejne wybicie..."
459 = "Chcesz poleciec? Wyjdz z progu szybciej."
460 = "Twoje wybicie jest kiepskie."
461 = "Niezle wybicie."
462 = "Wlasnie pokochalem cie za twoje wybicie!"
463 = "To wybicie bylo troche zawczesnie."
464 = "Nie spiesz sie z tym wybiciem."
465 = "Kiedys sie zabijesz."
468 = "Powinienes popracowac nad ladowaniem."
469 = "Nie boisz sie, ze sie zabijesz?.."
470 = "To bylo na krawedzi ryzyka."
471 = "Solidne ladowanie."
472 = "Ooo, Pan miekie ladowanie jest w okolicy."
473 = "Nie peniaj ladowac..."
474 = "Nie cykaj."
475 = "Nie boj sie klawiatury koles."
481 = "Surowy"
482 = "Jestes za bardzo wychylony glupku."
483 = "Swietna pozycja w locie, mistrzu."
484 = "Wychylaj sie jak facet."
485 = "Boze! Gdzie ladowanie?"
486 = "Nie! Rozpocznij pieprzone ladowanie!"
487 = "Bierz swoj tylek i idz popracuj!"
490 = "Nigdy nie widzialem gorszego skakania."
491 = "Moja matka skacze lepiej."
492 = "Co jest? Chcesz do mamusi?"
493 = "Mozesz to zrobic lepiej."
494 = "Kilku trenerow byloby z tego zadowolonych."
495 = "Teraz skaczesz jak kazalem."
498 = "Okropnie! Co to za wybicie!"
499 = "Wybicie bylo spoznione!"
500 = "Jeszcze troche opoznione wybicie!"
501 = "Nie mozesz wybic sie wczesniej?"
502 = "Teraz bylo tak jak chcialem."
503 = "Za wczesnie! Nie mozesz sie nauczyc?"
504 = "Katastrofalne wybicie!"
505 = "Nigdy nie widzialem gorszego wybicia. Idz do domu."
508 = "Ladowanie jest za trudne, palancie?"
509 = "Nie! Zacznij ladowac!"
510 = "Takie ladowanie jest za ryzykowne."
511 = "To prawie wygladalo jak ladowanie."
512 = "Mysle, ze to bylo niezle ladowanie."
513 = "Nie cykaj sie ladowac!"
514 = "Czego sie boisz! Lec do cholery"
515 = "Jestes glupi? Laduj, albo do domu!"
520 = "Wczytaj puchar"
521 = "Zapisac stan pucharu?"
522 = "Obecny skok przepada."
523 = "Brak zapisanych pucharow"
524 = "MULTIPLAYER"
