id = "savo"
name = "Savo"

[strings]
1 = "Yks"
2 = "Kaks"
3 = "Kolome"
4 = "Neljä"
5 = "Viis"
6 = "Juu"
7 = "Ee"
8 = "/"
9 = "Ee alakuunkaa"
11 = "Rekisteröety"
12 = "Seöveö"
13 = "Tavalline"
14 = "Nysä"
15 = "Polokase nappija..."
17 = "Piävalikko"
18 = "Hyppyytysvalikko"
20 = "Hyppeemään!"
21 = "Ilimota Hyppeejät"
22 = "Siätele"
23 = "Kunnijataolut"
24 = "Mäk ennätykset"
25 = "Vilimit"
26 = "Herkijä SJ3"
27 = "SJ3 Mualimankuppi"
28 = "Tie-Ihe-Kuppiisj"
29 = "Mäkviikko"
30 = "Joukkuvemäk-kuppi"
31 = "Piällysmiesj"
32 = "Ryllee huvikseesj"
33 = "Piävalikkoon"
34 = "Hyppeejät:"
35 = "Tään SJ3:n ylypee"
36 = "omistaja onnii:"
38 = "Tääpäs onnii rekisteröemätön"
39 = "versio SJ3:sta."
40 = "Luve Register.Txt JUSTIISA!"
41 = "Haluvatko olla kyläsj"
42 = "lupsakin patu?,"
43 = "Kaepootko lissee ietiä"
44 = "ryyppysakissa?"
45 = "SJ3 ee ou semmone ilimanep pelj."
46 = "Ou mies, rekisteröe."
47 = "Rekisteröemätön versio"
48 = "antaa vuan kaks pelloojoo."
51 = "Harjotukset"
52 = "Harjotuskiekaos"
53 = "Karsintakiekaos"
54 = "Ensmäne kieppi"
55 = "Toene kieppi"
56 = "Seoroovana..."
57 = "Syyporit hyppee..."
58 = "Riman holli:"
59 = "ässästä siätölöehin"
60 = "S"
61 = "Justiisa"
62 = "Johtoo riittää"
63 = "Voettoon riittää"
65 = "Mäk ennätysj"
67 = "Hyppeejiä jälellä:"
68 = "Jatkoo riittää:"
69 = "Viimene:"
70 = "Mualimankuppi tilanne"
71 = "Nykyne tilanne kupissa"
75 = "Poessa"
76 = "kilipaelua"
77 = "seor. kiekaokse"
78 = "seor. kilipaelun"
79 = "onnii hylätty!"
81 = "Rätinkiluvettelo - Kilipailu"
82 = "Karsinta - Kilipailu"
83 = "/ 4"
84 = "Mäkviikko - Kilipailu"
85 = "Mäkviikon lopputulokset"
86 = "(tihheempi luvettelo)"
87 = "Tilanne - Kilipailu"
88 = "Hyppeejä"
89 = "Mualimankuppirätingit:"
90 = "Lopputulokset"
91 = "Joukkuvemäktilanne - Kilpailu"
92 = "Joukkuvemäkkupin lopputulokset"
93 = "Joukkuvemäin rätingit - Joukkuve:"
94 = "puotussysteemiparit"
95 = "Tulokset"
96 = "Piällysmiesj"
97 = "Tulosj"
98 = "MK"
99 = "Mviikko:"
100 = "Yhteesä:"
101 = "Lähtennä hilippassemmaan:"
102 = "Kilipaelusta poekessa:"
103 = "Nuapurin puolele rytkähtänneet:"
104 = "Ryllyytysluvala pyyhitty...:"
105 = "Männä saonommaan:"
106 = "Missee?"
107 = "Joukkuve:"
108 = "Sij"
109 = "Pst"
110 = "JM"
111 = "Valamistaavu Joukkuvemäkkeen"
112 = "Joukkuvemäen aekataolu:"
113 = "Nimmee joukkuvvesj"
114 = "Joukkuve"
115 = "Paras tulos:"
116 = "Lattoo omat mäit"
117 = "Paa omat mäit talteen"
118 = "Valihe mäit Tie-Ihe-Kuppiisj"
119 = "Nuolila liikkuu, ENTER alottaa, ESC poestuu"
120 = "Tietokonehyppeejät:"
121 = "Ryllyytä *Piällysmiesj*"
122 = "Valihe Huastetaso"
123 = "Valihe Muut"
124 = "Ryllee:"
125 = "Tuulj?"
126 = "Usseesti?"
127 = "Palloo Piävalikkoon"
128 = "Uus ommiin mäkkiin ennΣtys!"
129 = "IjΣikkuine ennΣtys:"
130 = "P.M. Huastetaso"
131 = "Helevetin Vaekee"
132 = "Melekosen Vaekee"
133 = "Vaekeen Syräkkä"
134 = "Vasemmala Käelä"
135 = "Nuapurin Sokkee Kaoko"
136 = "Hohhoh"
137 = "Tie-Ihe"
138 = "Valihe Vastustajjaesj"
139 = "Valihe nuolila taso"
140 = "ENTER hyväksynnee, ESC poestuu"
141 = "Nimi"
142 = "Taso"
143 = "Eto Epelj!"
146 = "(Kursorit, ENTER, DEL ja ESC)"
150 = "(Kursorit, ENTER ja ESC)"
151 = "Missee Sie"
152 = "Halluut Tännään"
153 = "Ryllyyttee?"
154 = "Poestu"
155 = "Kuha häntä"
156 = "Lisee Mäkijä..."
157 = "Sivu"
158 = "Seoroova sivu"
159 = "Eelline sivu"
160 = "Piällysmiesj Huasteet"
161 = "Selevittämäti"
162 = "Parraat kustomitulokset tallessa"
163 = "20 Parraenta SJ3 Mualimankuppitulosta"
164 = "10 Parraenta Joukkuvemäktulosta"
165 = "5 Parraenta Mäkviikon pistesualista"
166 = "Nimi"
167 = "Sij"
168 = "Pisteet"
169 = "Millonka?"
170 = "Mäk ennätykset"
171 = "Kuka?"
172 = "Paljoka?"
173 = "Vile"
174 = "Pts"
175 = "Siätölöehin Piävalikko"
176 = "Ylleissumplingit"
177 = "Ryllyytyssumpingit"
178 = "Kunnijataoluasetukset"
180 = "Selevä"
181 = "Passoo"
182 = "Voe Tokkiisa"
183 = "No vot"
184 = "Juu"
185 = "Eläppäsj"
186 = "Ee Passoo"
187 = "Ee"
188 = "Elä Turhoo"
189 = "Elä"
190 = "Alusta"
191 = "Nolloo"
192 = "Kunnijataolut?"
193 = "Oottako justiin vissi?"
194 = "Meinootko poestoo"
195 = "Poestu Siätölöestä"
196 = "Ylleiset siävöt"
197 = "Ryllyytyssiävöt"
198 = "Kunnijataoluhin siävöt"
199 = "Miumaumukkaa näppylät"
200 = "Paa mäkennätystavotteet"
201 = "Mäkkiin hallinta"
203 = "Palluu siätölöeihin piävalikkoon"
204 = "Kielj?"
205 = "Iänjmerkit?"
206 = "Yljmiärässiin piirrusuksiin taso?"
207 = "Vastustajjiin nimitiijot (NAMES?.SKI)?"
208 = "Harmoot kohat pelloovat"
209 = "vuan rekisteröejyssä pelissä"
211 = "Palloo Piäsiätövalikkoon"
212 = "Harjotuskiekaoksia?"
213 = "Lissee rätingit?"
214 = "Näätä tulosrätingit erona?"
215 = "Näätä mualimankuppirätingit erona?"
216 = "Tiheemmät tuloslistat?"
217 = "Läpnäkyvät listohin taostat?"
218 = "Tallennettaanko mäk'ennätykset itestään?"
219 = "Näätä ennätystavote?"
220 = "Valakkoo kahottavat konehyppejät?"
221 = "Valihe tuuljhyrrykän paekka"
222 = "käätä puotussysteemijä mäkviikola?"
225 = "Mää takasij"
226 = "Tietokonneen tekemät mäk ennätykset?"
227 = "Suapko listala olla samoja nimijä?"
228 = "Alusta Kunnijataolut"
229 = "Nolloo Kunnijataolut"
230 = "Paa asetukssiij alakuarvot takasij"
231 = "ee ikänä"
232 = "Ee mäkviikola"
233 = "Aena"
235 = "Kymppi"
236 = "Kolomen Piä"
237 = "Viijen Piä"
238 = "Kymmene Piä"
239 = "Kaekki!"
240 = "Ee kettään"
242 = "Tavote"
243 = "Nuolila liikkuu, ESC poestaa"
245 = "Lähössä poes?"
246 = "EELL"
247 = "SEOR"
248 = "VALM"
251 = "Lähet sitte mänemmään..."
252 = "Haluvatko toellae poes?"
253 = "Elä nyt vielä karkoo."
256 = "Oottako työ justiin vissi?"
257 = "Toenperrään?"
258 = "Lykkee jiitä jos poes meinnoot."
261 = "Toppuuta! Siula pittää olla neljä (4)"
262 = "tae kaheksan (8) pelloojoo, jotta"
263 = "voet pittee joukkuvekinkerit!"
264 = "Pyyvä parj tuttuva pelloomaan tae"
265 = "paa oma nimmeisj usseempaa kertaa..."
270 = "SJ3 Mäkkiin Vässyy"
271 = "(käätä nuolija,"
272 = " ENTERiä tae ESCiä)"
273 = "Vile"
274 = "Mäk"
275 = "*Lisee Uusj*"
276 = "-Poestu-"
277 = "-Ryllyytä-"
278 = "Kokkeele!"
280 = "Nuolj yl÷s"
281 = "Nuolj vasemmale"
282 = "Nuolj oekeele"
283 = "Nuolj alas"
285 = "(L)attoo satsi"
286 = "(P)aa taltee"
287 = "(M)ikälie"
288 = "(J)ärjestele Mualimankuppi-pisteehin perusteela?"
289 = "(J)ärjestele kaekkiin pisteehin perusteela?"
290 = "Eepä löötynä vilimijä!"
291 = "Väsyri:"
292 = "Nimi:"
293 = "Vilenimi:"
294 = "Mäk:"
295 = "Poes, ee taltee"
296 = "Poes ja taltee"
298 = "(P)aa taltee"
300 = "Hyppeejät"
301 = "Valakkoo hyppeejät"
302 = "*Uus hyppeejä*"
304 = "Nimi:"
305 = "Oekee nimesj:"
306 = "Lyyssin värj:"
307 = "Suksiin värj:"
308 = "Vaeha:"
309 = "Valamentaja:"
310 = "Ee karsintoo:"
311 = "Nolloo hyppeejä"
312 = "Poekkeen"
313 = "Hyppyjä yhteesä:"
314 = "Mualimankupit:"
315 = "Kisoja voetettu:"
316 = "Mualimankupit voetetut:"
317 = "Paras mualimankuppi:"
318 = "Parraat 4mäkkee:"
319 = "Hirmusin MK hyppy:"
320 = "Hirmusin hyppy:"
321 = "Piällysmies:"
322 = "(Nuolila liikkuu,"
323 = "ENTER mulukkoo,"
324 = "DEL poestaa rivistä)"
325 = "ENTER merkkoo,"
326 = "DEL poestaa kokonnaa)"
328 = "Poesta hyppejä"
329 = "Nolloo hyppeejä"
330 = "Näppylät"
331 = "Päkistä"
332 = "Kenota"
333 = "Kellistä"
334 = "Telemarkki"
335 = "Tasajalakoo alas"
336 = "Alakupeäset siävöt"
337 = "Huit nevadaan"
340 = "Lentoaeka:"
341 = "Pittuus:"
342 = "Vaohti:"
343 = "Kustomi"
345 = "on jo olemassaan."
346 = "Kirjota piΣle?"
350 = "Vilimi mänj taltee."
351 = "Vilimijä ee pantu taltee."
352 = "Oma satsi tallessa."
353 = "Ommoo satsijä ee pantu taltee."
354 = "Ylmiäräne mäk tallessa."
355 = "Ylmiärästä mäkkee ee pantu taltee."
356 = "Omija satsija ee läätynnä!"
360 = "Tervetulloo pelloomaan mäkhyppyvä."
361 = "Tiijossa on rivakka vilikasu pelliin."
362 = "Mäkhypyssä oes tarkotus lentee nii pitkäle"
363 = "ku piäsöö ja lasseetuva jalolleen."
364 = "Siun hyppeejä nakottaa riuvulla ylämäin"
365 = "piälä.  Hipase oekeeta nuolta ja ukko lähtöö."
366 = "Tuuljhyrrykkä mollottaa vasemmassa alakulumassa."
367 = "Vastatuulj lennätää jonniiverrap paremmi."
368 = "Hyvvään hyppyy pittää polokasun sattuva"
369 = "justii kohallee.  Nuolj ylös taetaa olla se nappi."
370 = "Sitte pitäsj piästä hypyn piäle jotta tuulijaene"
371 = "ee paenas ukkova rinteesee. Oekeela nuolela se hoetuu."
372 = "Suattaa se tuulijaene räpöstellä sitä ukkova,"
373 = "mutta vasemmala nuolela keno korjaatuu."
374 = "Ku se Muaemo ruppee lähentelemmään voep tulla"
375 = "lasseentumine mielee hyvinnii herkästi."
376 = "Ylleesä 'T' -nappi ruppee tekemään telemarrkkija."
377 = "Oha se hijas ja kostikas, mutta tuomarit tykkee."
378 = "Sitte on 'R' -nappi, jolla suap tasajalaka-alastulon."
379 = "Se on makija varsinnii pitemmissä leiskaotuksissa."
380 = "Eepä tässä sen kummempia. tään voep kahtoo uuvestaa"
381 = "Vilimit-valikossa. Muile ko savolaesile on MANUAL.TXT."
390 = "Yllää"
391 = "Keskee"
392 = "Allaa"
393 = "Vase"
394 = "Keskee"
395 = "Oekee"
396 = "Hyppeejä"
400 = "Valamentaja hupattaa:"
401 = "Lupsakka"
402 = "Elä kaho ota liikoo etukennoo."
403 = "Tuo olj justii passelj keno."
404 = "Elä pelekee, kahtele vuan ietillee alaspäen."
405 = "Rutale, tie nyt ies jonniimoene lopsaotus."
406 = "Siehä tuut turvallee alas."
407 = "Ohhoh, olj vähä paskoo tuurija."
410 = "No tuo nyt olj iha persiistä."
411 = "Koeta nyt pikkuse ies räpiköejä."
412 = "No jokkii roti, naeset kahtoo."
413 = "No sepäsj mänj rapsakkaa."
414 = "HojoHojo! Sepäsj mänj vihmerästi."
415 = "Perskules! Siehä lennät ko Leväne!"
418 = "Siehä päkistät ko pytylä."
419 = "Polokase aekasemmi."
420 = "Vieläkkii loevansyräkkä päkistys."
421 = "Ruppee tuo polokasu olemmaa kohillaa."
422 = "No se mänj justiisa nappiij."
423 = "Eläppäs hötkyvä."
424 = "Minnekäsj siula o hoppu?"
425 = "Tuoha männöö iha mitem puuttujjaa."
428 = "Suattasim pähkäellä tuota lasseetumista."
429 = "Elä hyppee tuollee. Männöö turpa murole."
430 = "Mänjpä aeka hilikule tuo siun lopsaotus."
431 = "Lupsakkaan lopsaotit."
432 = "Kahonniätsen, olpas huljakka lopsaotus."
433 = "Melekolaela hätässeen rupesit allaa tulemmaa."
434 = "No mikämikä? Suap sitä lenteenni."
435 = "Elä pelekee tökkijä niitä rämpyttimijä."
441 = "Lupsakka"
442 = "Elä kaho ota liikoo etukennoo."
443 = "Tuo olj justii passelj keno."
444 = "Elä pelekee, kahtele vuan ietillee alaspäen."
445 = "Rutale, tie nyt ies jonniimoene lopsaotus."
446 = "Siehä tuut turvallee alas."
447 = "Ohhoh, olj vähä paskoo tuurija."
450 = "No tuo nyt olj iha persiistä."
451 = "Koeta nyt pikkuse ies räpiköejä."
452 = "No jokkii roti, naeset kahtoo."
453 = "No sepäsj mänj rapsakkaa."
454 = "HojoHojo! Sepäsj mänj vihmerästi."
455 = "Perskules! Siehä lennät ko Leväne!"
458 = "Siehä päkistät ko pytylä."
459 = "Polokase aekasemmi."
460 = "Vieläkkii loevansyräkkä päkistys."
461 = "Ruppee tuo polokasu olemmaa kohillaa."
462 = "No se mänj justiisa nappiij."
463 = "Eläppäs hötkyvä."
464 = "Minnekäsj siula o hoppu?"
465 = "Tuoha männöö iha mitem puuttujjaa."
468 = "Suattasim pähkäellä tuota lasseetumista."
469 = "Elä hyppee tuollee. Männöö turpa murole."
470 = "Mänjpä aeka hilikule tuo siun lopsaotus."
471 = "Lupsakkaan lopsaotit."
472 = "Kahonniätsen, olpas huljakka lopsaotus."
473 = "Melekolaela hätässeen rupesit allaa tulemmaa."
474 = "No mikämikä? Suap sitä lenteenni."
475 = "Elä pelekee tökkijä niitä rämpyttimijä."
481 = "Lupsakka"
482 = "Elä kaho ota liikoo etukennoo."
483 = "Tuo olj justii passelj keno."
484 = "Elä pelekee, kahtele vuan ietillee alaspäen."
485 = "Rutale, tie nyt ies jonniimoene lopsaotus."
486 = "Siehä tuut turvallee alas."
487 = "Ohhoh, olj vähä paskoo tuurija."
490 = "No tuo nyt olj iha persiistä."
491 = "Koeta nyt pikkuse ies räpiköejä."
492 = "No jokkii roti, naeset kahtoo."
493 = "No sepäsj mänj rapsakkaa."
494 = "HojoHojo! Sepäsj mänj vihmerästi."
495 = "Perskules! Siehä lennät ko Leväne!"
498 = "Siehä päkistät ko pytylä."
499 = "Polokase aekasemmi."
500 = "Vieläkkii loevansyräkkä päkistys."
501 = "Ruppee tuo polokasu olemmaa kohillaa."
502 = "No se mänj justiisa nappiij."
503 = "Eläppäs hötkyvä."
504 = "Minnekäsj siula o hoppu?"
505 = "Tuoha männöö iha mitem puuttujjaa."
508 = "Suattasim pähkäellä tuota lasseetumista."
509 = "Elä hyppee tuollee. Männöö turpa murole."
510 = "Mänjpä aeka hilikule tuo siun lopsaotus."
511 = "Lupsakkaan lopsaotit."
512 = "Kahonniätsen, olpas huljakka lopsaotus."
513 = "Melekolaela hätässeen rupesit allaa tulemmaa."
514 = "No mikämikä? Suap sitä lenteenni."
515 = "Elä pelekee tökkijä niitä rämpyttimijä."
520 = "Load Cup"
521 = "Save cup state?"
522 = "Current jump is lost."
523 = "No saved cups"
