id = "slovenski"
name = "Slovenski"

[strings]
1 = "Ena"
2 = "Dva"
3 = "Tri"
4 = "Stiri"
5 = "Pet"
6 = "Da"
7 = "Ne"
8 = "od"
9 = "Brez"
11 = "Registriran"
12 = "Shareware"
13 = "Normalno"
14 = "Nizko"
15 = "Pritisni tipko"
17 = "Glavni Menu"
18 = "Skakalni Menu"
20 = "Skoci!"
21 = "Vpisi Skakalce"
22 = "Setup Menu"
23 = "Zid Slave"
24 = "Rekordi"
25 = "Posnetki"
26 = "Zapri SJ3"
27 = "SJ3 SP"
28 = "SP Po Meri"
29 = "Turneja 4ih Skakalnic"
30 = "Mostveni Pokal"
31 = "Kralj Skakalnice"
32 = "Treniraj"
33 = "Nazaj v Glavni Menu"
34 = "Skakalci:"
35 = "Ta verzija SJ3"
36 = "je Registrirana na:"
38 = "To je Neregistrirana"
39 = "verzija SJ3."
40 = "Preberi Register.Txt Takoj!"
41 = "Kako biti najbolj Cool"
42 = "v svoji druzbi,"
43 = "Zelis dobiti malo Spostovanja"
44 = "Od prijateljev? Registriraj SJ3!"
45 = "Ta igra ni Zastonj."
46 = "Bodi cool in Registriraj."
47 = "Samo dva Igralca dovoljena"
48 = "v Neregistrirani verziji."
51 = "Treniraj"
52 = "Preiskusni Skok"
53 = "Kvalifikacijski Skok"
54 = "Prvi Skok"
55 = "Drugi Skok"
56 = "Naslednji..."
57 = "Racunalniski skakalci..."
58 = "Startno mesto:"
59 = "Pritisni (S) za Setup Menu"
60 = "S"
61 = "Trenutno"
62 = "Potrebno za Vodstvo"
63 = "Potrebno za Zmago"
65 = "Rekord Skakalnice"
67 = "Ostali Skakalci:"
68 = "Potrebno Premagati:"
69 = "Trenutno Zadnji:"
70 = "Trenutni vrstni red SP"
71 = "Trenutni vrstni red MP"
75 = "Zamudi naslednje"
76 = "Runde"
77 = "Runda"
78 = "Runda"
79 = "je Diskvalificiran!"
81 = "Razvrstitev - Runda"
82 = "Kvalifikacije - Runda"
83 = "od 4ih"
84 = "Turneja Stirih Skakalnic - Runda"
85 = "Koncni Razultati Turneje Stirih Skakalnic"
86 = "(krajsa lista)"
87 = "Razultati Po Rundi"
88 = "Skakalec"
89 = "Statistika Svetovnega Pokala za"
90 = "Konci Razultat od"
91 = "Mostveni Razultati po Rundi"
92 = "Koncni Razultati za Mostveni Pokal"
93 = "Statistika Mosvenega Pokala za"
94 = "Knock-out sistem pari"
95 = "Razvrstitev"
96 = "Kralj Skakalnice"
97 = "Razultati"
98 = "SP"
99 = "stiri skakalnice:"
100 = "Totalno:"
101 = "Izven Tekmovanja:"
102 = "Nic vec ne Skacejo:"
103 = "Izpadli Skakalci:"
104 = "V garderobi:"
105 = "Nic vec med nami:"
106 = "Kje?"
107 = "Mostvo:"
108 = "Poz"
109 = "Toc"
110 = "MP"
111 = "Pripravi se za Mostveni Pokal"
112 = "Koledar Mostvenega Pokala:"
113 = "Imenuje Mostvo"
114 = "Mostvo"
115 = "Najboljsi razultat:"
116 = "Nalozi Skakalnice po meri"
117 = "Shrani Skakalnice po meri"
118 = "Izberi Skakalnice za Svetovni Pokal po meri"
119 = "Uporabi puscice, ENTER start, ESC izhod"
120 = "Racunalniski Skakalci:"
121 = "Zacni *Kralja Skakalnice*"
122 = "Izberi Tezavnostno Stopnjo"
123 = "Izberi Nasprotnike"
124 = "Skakati v"
125 = "Veter?"
126 = "Skokov?"
127 = "Nazaj v Glavni Menu"
128 = "Novi rekord skakalnic po meri!"
129 = "Stari rekord:"
130 = "Kralj S. Tezavnostna Stopnja"
131 = "NAJVECJI IZIV"
132 = "TEZKI PISKOTKI"
133 = "LAHKA VARIANTA"
134 = "LAHKO PREMAGAJOCI"
135 = "UPOKOJENCI"
136 = "MAJHNE PUNCKE V ROZA OBLEKCAH"
137 = "PO MERI"
138 = "Izberi Nasprotnike"
139 = "Uporabi puscice pri izbiri Tezavnosti"
140 = "ENTER izbere, ESC zapre"
141 = "Ime"
142 = "Cin"
143 = "Kralj!"
146 = "(Uporabi Puscice, ENTER, DEL ali ESC)"
150 = "(Uporabi Puscice, ENTER ali ESC)"
151 = "Kje"
152 = "Zelis Skakati"
153 = "Danes?"
154 = "Zapri"
155 = "Nakljucnje Skakalnice SP"
156 = "Vec Skakalnic..."
157 = "Stran"
158 = "Naslednja Stran"
159 = "Prejsna Stran"
160 = "Kralj skakalnice"
161 = "Ni koncano"
162 = "Shranjeni najboljsi razultati skakalnic po meri"
163 = "Razultati najboljsih 20 SJ3 v Svetovnem pokalu"
164 = "Razultati najboljsih 10 v Mostvenem pokalu"
165 = "Razultati najboljsih 5 v turneje stirih skakalnic"
166 = "Ime"
167 = "Poz"
168 = "Tocke"
169 = "Kdaj?"
170 = "Rekordi"
171 = "Kdo?"
172 = "Koliko?"
173 = "File"
174 = "Pts"
175 = "Setup Glavni Menu"
176 = "To so Generalne Nastavitve"
177 = "Nekaj Nastavitev glede Skakanja"
178 = "Nekaj Nastavitev o Razultatih"
180 = "Oh Da"
181 = "Seveda"
182 = "Da!"
183 = "Aha!"
184 = "Ja"
185 = "Oh Ne"
186 = "Niti Slucajno"
187 = "Ne"
188 = "Nope"
189 = "Nah"
190 = "Resetiraj"
191 = "Nic"
192 = "Najboljsi Razultati?"
193 = "Preprican?"
194 = "Pred brisanjem"
195 = "Zapri Setup"
196 = "Generalne Nastavitve"
197 = "Skakalne Nastavite"
198 = "Razultati in Setup Nastavitve"
199 = "Tipke po meri"
200 = "Nastavi cilje za rekorde"
201 = "Naredi Skakalnico"
203 = "Nazaj v Setup.Main"
204 = "Jezik?"
205 = "Pisk?"
206 = "Kvaliteta Grafike?"
207 = "Imena Racunalniskih Skakalcev (NAMES?.SKI)?"
208 = "Stvari v sivem"
209 = "so na voljo samo v Registrirani verziji."
211 = "Nazaj v Main Setup"
212 = "Preiskusni Skok?"
213 = "Dodatna Statistika?"
214 = "Pokazi razliko razultatov?"
215 = "Pokazi razverstitev v SP po razlikah?"
216 = "Kompaktni razultati?"
217 = "Nevidni razultati?"
218 = "Avtomaticno Shrani Posnetek Rekordnega Skoka?"
219 = "Pokazi cilje rekordov skakalnic?"
220 = "Izberi gledane racunalniske skakalce?"
221 = "Izberi mesto vetromera"
222 = "Uporabi Knock-out-sistem v 4H?"
225 = "Zapusti Setup Najboljsih Razultatov"
226 = "Ali Lahko Racunalniski Skakalec Skoci Rekord?"
227 = "Dovoli Vec Istih Imen"
228 = "Resetiraj Najboljse Razultate"
229 = "Najboljsi Razultati na Nic"
230 = "Vrni Navadne Nastavitve"
231 = "Nikoli"
232 = "Ne v 4H"
233 = "Vedno"
235 = "Vodilni"
236 = "Prvi 3je"
237 = "Prvih 5"
238 = "Prvih 10"
239 = "Vsi!"
240 = "Nobenega"
242 = "Cilj"
243 = "Uporabljaj puscice, ESC zapre"
245 = "Ze Odhajas?"
246 = "<--"
247 = "-->"
248 = "OK"
251 = "Ze odhajas..."
252 = "Ali res zelis oditi?"
253 = "Oh, kam hitis?"
256 = "Si preprican?"
257 = "Si cisto preprican?"
258 = "Pritisni D ce zelis oditi."
261 = "Ahoy! Imeti moras stiri(4)"
262 = "ali osem (8) igralcev prijavljenih"
263 = "predno greste igrat Mostveni Pokal!"
264 = "Pojdi poklicat prijatelje"
265 = "ali pa se kloniraj 4-krat."
270 = "SJ3 Urednik Skakalnic"
271 = "(Uporabi puscice, DEL,"
272 = " ENTER ali ESC)"
273 = "Ime Datoteke"
274 = "Ime Skakalnice"
275 = "*Dodaj novo skakalnico*"
276 = "-Exit-"
277 = "-Start-"
278 = "Testiraj skakalnico!"
280 = "Puscica Gor"
281 = "Puscica Levo"
282 = "Puscica Desno"
283 = "Puscica Dol"
285 = "(L)oad set"
286 = "(S)ave set"
287 = "(R)andom set"
288 = "Uredi po T(O)ckah SP"
289 = "Uredi po Skupnih T(O)ckah"
290 = "Ne najde posnetkov!"
291 = "Avtor:"
292 = "Ime:"
293 = "Ime datoteke:"
294 = "Skakalnica:"
295 = "Zapri, ne shrani"
296 = "Zapri in shrani"
298 = "(S)hrani posnetke"
300 = "Skakalci"
301 = "Izberi skakalce"
302 = "*Nov igralec*"
304 = "Ime:"
305 = "Pravo Ime:"
306 = "Barva Dresa:"
307 = "Barva Smuci:"
308 = "Zamenjaj:"
309 = "Trener:"
310 = "Preskoci Kvali:"
311 = "Resetiraj Skakalca"
312 = "Zapri"
313 = "Skupaj Skokov:"
314 = "Svetovnih Prvenstev:"
315 = "Zmag:"
316 = "Svetovni Prvak:"
317 = "Najboljsi na SP:"
318 = "Najboljsi na 4ih Skakalnicah:"
319 = "Najdaljsi Skok na SP:"
320 = "Najdaljsi Skok:"
321 = "KOTH tezavnost:"
322 = "(Uporabljaj puscice,"
323 = "ENTER nastavi skakalca,"
324 = "DEL izbrise iz seznama)"
325 = "ENTER prijavi,"
326 = "DEL izbrise skakalca)"
328 = "Izbrisi Skakalca"
329 = "Resetirajanje Skakalca"
330 = "Keymap"
331 = "Odskok"
332 = "Nagni naprej"
333 = "Nagni nazaj"
334 = "Telemark"
335 = "Navaden pristanek"
336 = "Vrni orig. nastavitve"
337 = "Zapri"
340 = "Cas v zraku"
341 = "Dolzina"
342 = "Hitrost:"
343 = "Po meri"
345 = "ze obstaja."
346 = "Prepisem?"
350 = "Posnetek je bil shranjen."
351 = "Posnetek ni bil shranjen."
352 = "Custom set je bil shranjen."
353 = "Custom set ni bil shranjen."
354 = "Ekstra skakalnica shranjena."
355 = "Ekstra skakalnica ni shranjena."
356 = "Ni nasel Custom Sets!"
360 = "Dobrodosli v SJ3 in v Skakalnem sportu."
361 = "Tukaj je hitra predstavitev te igre."
362 = "Ideja tega sporta je leteti cim dlje"
363 = "je mozno in pristati brez poskodb."
364 = "Skakalec sedi na vrhu skakalnice."
365 = "Z pritiskom na puscico DESNO se spusti proti odskocni mizi."
366 = "Merilec vetra je postavljen v spodnji levi kot zaslona."
367 = "Veter obrnjen proti skakalcu poveca silo vzgona."
368 = "Kljuc do uspesnega skoka je timing odskoka in pristanka"
369 = "S puscico GOR se odrinete."
370 = "Sedaj morata nagniti skakalca naprej da zmanjsate"
371 = "zracni upor.  To naredite z puscico LEVO."
372 = "Vcasih vas sunek vetra vrze iz pravilne pozicije"
373 = "v zraku.  Uporabite puscico LEVO da to popravite."
374 = "Ko se priblizujete zemlji je dobro pomisliti"
375 = "na varen pristanek brez poskodb."
376 = "Tipka 'T' sprozi telemark pristanek.  Je"
377 = "pocasnejsi in nevarnejsi, vendar se pozna pri tockah za slog."
378 = "Tipka 'R' sprozi navaden pristanek,"
379 = "ki je najbolj uporaben pri daljsih skokih."
380 = "To je to! Lahko si tudi ogledate posnetek"
381 = "za vec informacij pa si preberite MANUAL.TXT."
390 = "Vrh"
391 = "Sredina"
392 = "Dno"
393 = "Levo"
394 = "Center"
395 = "Desno"
396 = "Skakalec"
400 = "Trenerjev Kot:"
401 = "Profesionalni"
402 = "Ne nagni se tako nizko."
403 = "Dobra pozicija letenja."
404 = "Nagni se bolj med smuci."
405 = "Probaj pristati brez padca."
406 = "Prej zacni pristajati."
407 = "Uhh, kaksna smola, skoda!"
410 = "To je slabo skakanje!"
411 = "Se vedno ne zgleda dobro."
412 = "To je kar solidno."
413 = "Dober skok, bravo."
414 = "Odlicnoooo!"
415 = "Neverjetno!  Kje je pravzaprav tvoja meja?"
418 = "Na mizi zacni prej."
419 = "Odskok je bil prepozen."
420 = "Timing na mizi je se vedno prepozen!"
421 = "Tokrat je bilo bolje."
422 = "Perfekten odskok!"
423 = "Na mizi si bil rahlo prezgoden."
424 = "Ne zacenjaj tako zgodaj."
425 = "To je bilo prezgodaj ."
428 = "To pomeni ZELO prezgodaj."
429 = "Tokrat je bilo pac prepozno."
430 = "Komaj si se ujel pristanek."
431 = "V redu timing na pristanku."
432 = "To bi moralo dati dobre ocene."
433 = "Ne zacenjaj pristajati tako zgodaj."
434 = "Ne se bati leteti dalec."
435 = "Prosim pritisni 'T' ali 'R'."
441 = "Sprosceno"
442 = "Aw, ne nagni se prevec."
443 = "Prelepa pozicija v zraku."
444 = "Ne se bati nagniti nekoliko bolj, sine."
445 = "Prosim pristani naslednjic, to je boli."
446 = "Spet si pristal na glavo, misko."
447 = "Ves kaj, vse pa tud ne moras pristat."
450 = "To je prevec sprosceno."
451 = "To je... hmm, zanic."
452 = "To zgleda bolje."
453 = "Temu se rece lepo skakanje."
454 = "Ohh Jaaa, bejbe te ljubijo!"
455 = "To je bilo dalec, Superman!"
458 = "Kako len odskok..."
459 = "Ce zelis leteti, odskoci prej."
460 = "Timing ni prav blestec."
461 = "Kar dober timing, misko."
462 = "Jaa, ljubim tvoj odskok!"
463 = "Odskok je bil rahlo prekmalu."
464 = "Ne hiti z odskokom."
465 = "Ooh, nekega dne se bos se ubil."
468 = "Vec treninga na pristanku."
469 = "A se ne bojis da se bos ubil?.."
470 = "Uff, pristanek je bil na meji."
471 = "Pristanek - trd kot skala."
472 = "Ooh, Dr. Lep Pristanek."
473 = "Ne hiti z pristansko..."
474 = "Ne se bati pri pristanku."
475 = "Ne se bat tipkovnice."
481 = "Strogo"
482 = "Prevec si nagnjen, bebec."
483 = "V redu letna pozicija."
484 = "Cura! Nagnji se kot moski."
485 = "Oh Bog! Kje je pristanek, cepec?"
486 = "Ne Ne Ne! Zacni preklet pristanek pravocasno!"
487 = "Zmigaj to debelo rit in pojdi na delo!"
490 = "Nikoli nisem videl slabsega pristanka, pizda zresen se mal!"
491 = "Moja praprababica skoci bolje kot ti!"
492 = "Kaj je narobe? Hoces domov k svoji mamici v narocje?"
493 = "To lahko naredis veliko bolje."
494 = "Nekateri trenerji bi bili zadovljni s tem."
495 = "Sedaj si skocil, kot sem ti rekel, cas je ze bil!"
498 = "Zanic! Kje je preklet odskok!"
499 = "Odskok je spet pozen. 50 sklec!"
500 = "Timing je zanic. 25 sklec!"
501 = "Ali ne mores odskociti nekoliko prej?"
502 = "Koncno sem zadovoljen z odskokom."
503 = "Prekmalu!  Se ne mores nauciti?"
504 = "Katastroficen odskok! 50 sklec!!"
505 = "Nisem se videl slabsega odskoka. Pejd domov!"
508 = "Je pristanek pretezek, mamin sinko?"
509 = "Ne! Zacni preklet pristanek pravocasno!"
510 = "Pristanek je riskiran."
511 = "To je priblizno zgledalo kot pristanek."
512 = "Pomoje je tole bil kar dober pristanek."
513 = "Ne se usrat pri pristanku."
514 = "Cesa se bojis? Vleci, vleci!"
515 = "Ali si prfuknen? Pristani ali pa pejd domov!"
