id = "slovensky"
name = "Slovensky"

[strings]
1 = "Jeden"
2 = "Dva"
3 = "Tri"
4 = "Styri"
5 = "Pat"
6 = "Sest"
7 = "Nie"
8 = "z"
9 = "Ziadny"
11 = "Registrovany"
12 = "Shareware"
13 = "Normalny"
14 = "Nizky"
15 = "Stlac klavesu..."
17 = "Hlavne Menu"
18 = "Skokanske Menu"
20 = "Skac!"
21 = "Skokani"
22 = "Nastavenia"
23 = "Sien slavy"
24 = "Rekordy mostikov"
25 = "Opakovacky"
26 = "Opusti SJ3"
27 = "SJ3 Svetovy pohar"
28 = "Vlastny SP"
29 = "Turne 4 mostikov"
30 = "Timovy pohar"
31 = "Kral mostika"
32 = "Trening"
33 = "Spat do Hl. menu"
34 = "Skokani:"
35 = "Tato verzia"
36 = "je registrovana na:"
38 = "Toto je neregistrovana"
39 = "verzia SJ3."
40 = "Precitaj si Register.Txt!"
41 = "Na to, ako byt najvacsi"
42 = "boss vo svojom okoli."
43 = "Chces ziskat respekt medzi"
44 = "svojimi priatelmi? Zaregistruj sa."
45 = "Tato hra nie je freeware."
46 = "Urob spravnu vec, zaregistruj sa."
47 = " Maximalne dvaja hraci"
48 = "v neregistrovanej verzii!"
51 = "Trening"
52 = "Treningove kolo"
53 = "Kvalifikacia"
54 = "1. kolo"
55 = "2. kolo"
56 = "Nasleduje..."
57 = "Skace pocitac..."
58 = "Najazd:"
59 = "Stlac (S) na Nastavenia"
60 = "S"
61 = "V tejto chvili"
62 = "Na vedenie"
63 = "Na vitazstvo"
65 = "Rekord mostika"
67 = "Zostavajuci skokani:"
68 = "Potrebujes prekonat:"
69 = "Momentalne posledny:"
70 = "Aktalne poradie SP"
71 = "Aktualne poradie TP"
75 = "Chybas nasledujuce"
76 = "Preteky"
77 = "Kolo"
78 = "Pretek"
79 = "je diskvalifikovany!"
81 = "Vysledkova listina - Pretek"
82 = "Kvalifikacia - Pretek"
83 = "zo 4"
84 = "Turne styroch mostikov - Pretek"
85 = "Konecne vysledky turne styroch mostikov"
86 = "(skratene vysledky)"
87 = "Poradie po Preteku"
88 = "Skokan"
89 = "Statistiky Svetoveho Pohara pre"
90 = "Konecne vysledky"
91 = "Poradie Timoveho Pohara po"
92 = "Konecne vysledky Timoveho Pohara"
93 = "Poradie timoveho pohara"
94 = "Dvojice v knock - out systeme"
95 = "Poradie"
96 = "Kral mostika"
97 = "Vysledok"
98 = "SP"
99 = "4 mostiky:"
100 = "Celkom:"
101 = "Mimo sutaze:"
102 = "Uz neskacu:"
103 = "Eliminovany skokani:"
104 = "V satniach:"
105 = "Uz viac nie medzi nami:"
106 = "Kde?"
107 = "Tim:"
108 = "Poz"
109 = "Bod"
110 = "TP"
111 = "Priprav sa na Timovy pohar"
112 = "Kalendar timoveho pohara:"
113 = "Prosim pomenuj tim"
114 = "Tim"
115 = "Najlepsi vysledok:"
116 = "Nacitaj subor mostikov"
117 = "Uloz subor mostikov"
118 = "Vyber si mostiky pre tvoj SP"
119 = "Pouzi sipky, ENTER vyber, ESC skonci"
120 = "Skokani (pocitac):"
121 = "Zacni *Kral mostika*"
122 = "Vyber si level"
123 = "Vyber si protivnikov"
124 = "Skakat v"
125 = "Vietor?"
126 = "Kola?"
127 = "Spat do menu"
128 = "Novy rekord pre subor mostikov!"
129 = "Stary rekord:"
130 = "K.O.T.H Level"
131 = "Pre fakt dobrych"
132 = "Pre dobrych"
133 = "Pre skoro dobrych"
134 = "Pre supakov"
135 = "Pre dochodcov"
136 = "Pre tehotne zeny"
137 = "Volitelny"
138 = "Vyber si superov"
139 = "Pre zmenu levela pouzi sipky"
140 = "ENTER vyber, ESC skonci"
141 = "Meno"
142 = "Poradie"
143 = "Kral!!"
146 = "(Pouzi sipky, ENTER, DEL alebo ESC)"
150 = "(Pouzi sipky, ENTER alebo ESC)"
151 = "Kde"
152 = "chces dnes"
153 = "skakat?"
154 = "Koniec"
155 = "Nahodny mostik SP"
156 = "Viac mostikov..."
157 = "Stranka"
158 = "Dalsia stranka"
159 = "Predosla stranka"
160 = "Kral mostika"
161 = "nie je dokoncena"
162 = "Naj skoky na volitelnych mostikov"
163 = "Top 20 SJ3 Vysledkov SP"
164 = "Top 10 Vysledkov TP"
165 = "Top 5 Turne Styroch Mostikov"
166 = "Meno"
167 = "Pos"
168 = "Body"
169 = "Kedy?"
170 = "Rekordy mostikov"
171 = "Kto?"
172 = "Kolko?"
173 = "Subor"
174 = "Body"
175 = "Nastavenia"
176 = "Zakladne nastavenia"
177 = "Nastavenia skoku"
178 = "Hiscore nastavenia"
180 = "Asi ze"
181 = "Jasne"
182 = "Ano"
183 = "Hej"
184 = "Suhlas"
185 = "To nie"
186 = "Nie"
187 = "Nieee"
188 = "Fakt nie"
189 = "Nesuhlas"
190 = "Reset"
191 = "Vynuluj"
192 = "Hiscore?"
193 = "Si si isty?"
194 = "Idem vymazat"
195 = "Opust nastavenia"
196 = "Zakladne nastavenia"
197 = "Nastavenia skoku"
198 = "Nastavenia Hiscore a moznosti"
199 = "Nastavenia tlacidiel"
200 = "Nastav ciele pre rekordy mostikov"
201 = "Editor mostikov"
203 = "Spat do hl. menu"
204 = "Jazyk?"
205 = "Pipanie?"
206 = "Detaily?"
207 = "Mena protivnikov (NAMES.SKI)?"
208 = "Sede moznosti su dostupne"
209 = "len v registrovanej verzii"
211 = "Spat do hlavnych nastaveni"
212 = "Treningove kola?"
213 = "Extra Statistiky?"
214 = "Ukazovat vysledky s rozdielmi?"
215 = "Ukazovat vysledky SP s rozdielmi?"
216 = "Zuzena vysledkova listina?"
217 = "Neviditelne pozadie vysledkov?"
218 = "Automaticky ukladat rekordy (replay)?"
219 = "Ukazat ciele mostikov?"
220 = "Pocet sledovanych protivnikov?"
221 = "Vyber miesto pre merac vetra"
222 = "Pouzit KO system v T4M?"
225 = "Opusti nastavenia Hiscore"
226 = "Zaznamenat rekordy skocene pocitacom?"
227 = "Povolit viacej rovnakych mien"
228 = "Resetovat Hiscore"
229 = "Vynulovat Hiscore"
230 = "Spat do zakladnych nastaveni"
231 = "Nikdy"
232 = "Nie v T4M"
233 = "Vzdy"
235 = "Lider"
236 = "Top 3"
237 = "Top 5"
238 = "Top 10"
239 = "Vsetkych!"
240 = "Ziadnych"
242 = "Ciel"
243 = "Pouzi sipky, ESC ukonci"
245 = "Uz odchadzas?"
246 = "PRED"
247 = "DALS"
248 = "UKON"
251 = "Aha, tak odchadzas..."
252 = "Urcite chces odist?"
253 = "Vzdavas to tak skoro?"
256 = "Si si tym isty?"
257 = "Si si tym uplne isty?"
258 = "Stukni A pre koniec."
261 = "Nazdar! Musis mat styroch (4)"
262 = "alebo osmych (8) prihlasenych hracov"
263 = "pred zacatim Timoveho Pohara!"
264 = "Zozen si kamosov alebo"
265 = "sa 4krat nakopiruj."
270 = "SJ3 Vyroba mostikov"
271 = "(pouzi sipky, DEL,"
272 = " ENTER alebo ESC)"
273 = "Meno suboru"
274 = "Meno mostika"
275 = "*Pridaj novy mostik*"
276 = "-Koniec-"
277 = "-Start-"
278 = "Vyskusaj si svoj mostik!"
280 = "Sipka hore"
281 = "Sipka dolava"
282 = "Sipka doprava"
283 = "Sipka dole"
285 = "(N)ahraj"
286 = "(U)loz"
287 = "(L)ubovolny zoznam"
288 = "Z(O)rad podla bodov SP"
289 = "Z(O)rad podla celkovych bodov"
290 = "Ziadne zaznamy!"
291 = "Autor:"
292 = "Meno:"
293 = "Meno suboru:"
294 = "Mostik:"
295 = "Ukonci a neuloz"
296 = "Ukonci a uloz"
298 = "(U)loz zaber"
300 = "Skokani"
301 = "Vyber skokanov"
302 = "*Vytvor noveho skokana*"
304 = "Meno:"
305 = "Skut. meno:"
306 = "Farba kombinezy:"
307 = "Farba lyzi:"
308 = "Vymen:"
309 = "Trener:"
310 = "Preskoc kval.:"
311 = "Resetuj skokana"
312 = "Koniec"
313 = "Celkovo skokov:"
314 = "Skoncenych SP:"
315 = "Vyhranych kol:"
316 = "Vyhranych SP:"
317 = "Naj SP:"
318 = "Naj T4M:"
319 = "Najdlhsi SP skok:"
320 = "najdlhsi skok:"
321 = "KOTH level:"
322 = "(Pouzi sipky,"
323 = "ENTER upravi jumper,"
324 = "DEL odstrani z poradia)"
325 = "ENTER zapise,"
326 = "DEL vymaze skokana)"
328 = "Vymaz skokana"
329 = "Resetuj skokana"
330 = "Nastavenia klaves"
331 = "Odraz"
332 = "Dopredu"
333 = "Dozadu"
334 = "Telemark"
335 = "Na obe nohy"
336 = "Povodne nastavenia"
337 = "Koniec"
340 = "Cas skoku"
341 = "Dlzka skoku"
342 = "Rachlost:"
343 = "Vlastne"
345 = "uz existuje."
346 = "Prepisat?"
350 = "Opakovany zaber bol ulozeny."
351 = "Opakovany zaber sa neulozil."
352 = "Volitelne nastavenie bolo ulozene."
353 = "Volitelne nastavenie sa neulozilo."
354 = "Extra mostik bol ulozeny"
355 = "Extra mostik nebol ulozeny."
356 = "Neboli najdene ziadne vlastne nastavenia."
360 = "Vitajte v SJ3 a vo svete skokov na lyziach"
361 = "Tu je rychle uvedenie do hry."
362 = "Podstata tohto sportu je letiet tak daleko"
363 = "ako sa da a predviest bezpecne pristatie."
364 = "Vas skokan sedi na lavici na zaciatku"
365 = "najazdu. Pouzite sipku Doprava na spustenie sa ."
366 = "Ukazovatel vetra je v lavom dolnom rohu obrazovky."
367 = "Protivietor je lepsi pretoze zvysuje vztlak."
368 = "Klucom k uspechu je spravne nacasovanie"
369 = "odrazu.  Stlacte sipku Hore pre odraz."
370 = "Teraz mozete naklonit skokana dopredu pre"
371 = "znizenie odporu vzduchu.  Stlacte sipku Vpravo."
372 = "Niekedy sa stane, ze vas vietor vyvedie z rovnovahy."
373 = "Stlacte sipku dolava, aby ste napravili svoju poziciu."
374 = "Ako sa blizite k zemi, bolo by dobre"
375 = "zacat premyslat o bezpecnom dopade."
376 = "Tlacitkom ┤T┤ zacnete pristatie do telemarku. Je"
377 = "pomalsie a riskantnejsie, ale lepsie bodovo hodnotene."
378 = "Klavesou ┤R┤ zacnete dopad na obe nohy,"
379 = "ktory je bezpecnejsi a vhodny pre dlhe skoky."
380 = "To je vsetko! Toto intro si mozete znovu pozriet v"
381 = "ponuke ┤Opakovacky┤ pre viac info si pozrite README.TXT"
390 = "Horny"
391 = "Stredny"
392 = "Dolny"
393 = "Lavy"
394 = "Stredny"
395 = "Pravy"
396 = "Skokan"
400 = "Okienko trenera:"
401 = "Profesional"
402 = "Nebud v lete tak zakloneny."
403 = "Dobra letova pozicia."
404 = "Nebud tak vzpriameny."
405 = "Nabuduce skus pristat."
406 = "Zacni skor s pristavanim."
407 = "Ach, co uz, to bola smola."
410 = "To je hrozny skok."
411 = "Stale to bohvieako nevyzera."
412 = "To je vcelku dobry skok."
413 = "Dobry skok."
414 = "Perfektny skok!"
415 = "Neuveritelne! Kde mas plast?"
418 = "Nabuduce sa odraz omnoho skor."
419 = "Odraz bol velmi oneskoreny."
420 = "Nacasovanie je stale trochu oneskorene."
421 = "Nacasovanie bolo tentokrat lepsie."
422 = "Perfektna presnost na odraze!"
423 = "Prilis skoro si sa odrazil."
424 = "Neodrazaj sa tak skoro."
425 = "To je hrozny odraz. Zacni s tym omnoho skor."
428 = "Myslel som tym este skor."
429 = "Tentokrat to proste bolo prilis neskoro."
430 = "Ten dopad bol sotva nacas ."
431 = "Dobre nacasovane pristatie."
432 = "Z toho by mohli byt dobre body za styl."
433 = "Nemusel si tak skoro pristavat."
434 = "Neboj sa natiahnut let."
435 = "Stlac ┤T┤ alebo ┤R┤, prosim."
441 = "Pohodak"
442 = "Ach, nepretacaj ten skok, chlape."
443 = "Lahodna letova pozicia."
444 = "Neboj sa viac nalahnut, synu."
445 = "To muselo boliet. Nabuduce skus pristat."
446 = "Stale pristavas na ksicht, chlapce."
447 = "Ved  vies, vsetko nemozes ustat."
450 = "To bolo prilis lezerne."
451 = "Aby si sa nepretrhol."
452 = "Uz to zacina vyzerat tak, ako by malo."
453 = "Tomuto ja hovorim dobry skok."
454 = "O ano, na toto budu pipky letiet!"
455 = "To je parada! Rad by som ta zoznamil so Supermanom!"
458 = "Pohni s tou prdelou na odraze..."
459 = "Ak chces letiet, odraz sa skor."
460 = "Tvoj odraz nie je prave najslavnejsi."
461 = "Perfektny odraz, chlape."
462 = "Tento odraz zerem!"
463 = "Odraz bol stale kus priskoro."
464 = "Neponahlaj sa tak s odrazom."
465 = "Oh, takto sa raz dolames."
468 = "Asi by si mal zapracovat na dopade."
469 = "Nebojis sa, ze raz sa zabijes?.."
470 = "Wow, to pristatie bolo len tak - tak."
471 = "Pristatie - Pevne ako Skala."
472 = "Ooh,mame tu pana Jemny Dopad."
473 = "Neponahlaj sa s tym pristatim..."
474 = "Nabud poondiaty letiet dalej."
475 = "Neboj sa klavesnice, chlape"
481 = "Striktny"
482 = "Prilis sa naklanas, hlupacik."
483 = "To je slusna letova pozicia."
484 = "Slaboch, skac ako chlap."
485 = "Oh Boze! A kde je pristatie?"
486 = "Nie! Zacni s tym sprostym pristatim nacas!"
487 = "Pohni zadkom a spat do prace!"
490 = "Horsi skok som este nevidel."
491 = "To moja mama skace lepsie ako ty."
492 = "Co zase? Chces ist domov za maminkou?"
493 = "Vies to este omnoho lepsie."
494 = "Ini treneri by s tym boli spokojni."
495 = "Teraz skaces, ako som ti kazal."
498 = "Otrasne! Kde je ten sprosty odraz!"
499 = "Zase si sa neskoro odrazil. 50 klikov!"
500 = "Odraz je stale na nic. 25 klikov!"
501 = "Mohol by si sa odrazit trochu skor?"
502 = "Konecne odraz, aky som chcel."
503 = "Neskoro!  Co sa to nikdy nenaucis?"
504 = "Katastrofalny odraz! 50 klikov, podme!"
505 = "Horsi odraz som este nevidel. Chod domov."
508 = "Je to pristatie take tazke, mamickin maznacik?"
509 = "Nie! Zacni s tym pristatim nacas!"
510 = "To pristatie je prilis riskantne."
511 = "To uz takmer vyzeralo ako dopad."
512 = "Myslim, ze dopad bol v poriadku."
513 = "Nebud pri tom pristati taky poondiaty."
514 = "Coho sa bojis? Let, do frasa!"
515 = "Co si sprosty? Pristan alebo chod domov!"
520 = "Load Cup"
521 = "Save cup state?"
522 = "Current jump is lost."
523 = "No saved cups"
