id = "srpski"
name = "Srpski"

[strings]
1 = "Jedna"
2 = "Dve"
3 = "Tri"
4 = "Cetiri"
5 = "Pet"
6 = "Da"
7 = "Ne"
8 = "od"
9 = "Nista"
11 = "Registrovana"
12 = "Shareware"
13 = "Normalan"
14 = "Slab"
15 = "Pritisni taster..."
17 = "Glavni Meni"
18 = "Skakacki Meni"
20 = "Skaci!"
21 = "Skakaci"
22 = "Setup Meni"
23 = "Hol Slavnih"
24 = "Rekordi skakaonica"
25 = "Snimci"
26 = "Izadji iz SJ3"
27 = "SJ3 Svetski Kup"
28 = "Custom Kup"
29 = "Turneja 4 Skakaonice"
30 = "Timski Kup"
31 = "Kralj Skakaonice"
32 = "Trening"
33 = "Vrati se u Glavni Meni"
34 = "Skakaci:"
35 = "Ova verzija je"
36 = "registrovana na ime:"
38 = "Ovo je neregistrovana"
39 = "verzija SJ3."
40 = "Procitaj Register.Txt sada!"
41 = "Ukoliko zelis da budes najpopularnija"
42 = "faca u komsiluku,"
43 = "Zelis da te postuju"
44 = "prijatelji?  Registruj, covece!"
45 = "Ovo nije besplatna igrica."
46 = "Uradi pravu stvar, registruj."
47 = "Samo dva igraca mogu da igraju"
48 = "u ovoj neregistrovanoj verziji!"
51 = "Vezbanje"
52 = "Trening"
53 = "Kvalifikacije"
54 = "Runda 1"
55 = "Runda 2"
56 = "Sledi..."
57 = "Kompjuter skace..."
58 = "Startna kapija:"
59 = "Pritisni (S) za Setup Meni"
60 = "S"
61 = "Trenutni plasman"
62 = "Potrebno za vodjstvo"
63 = "Potrebno za pobedu"
65 = "Rekord skakaonice"
67 = "Preostalo skakaca:"
68 = "Potrebno da nadmasis:"
69 = "Trenutno poslednji:"
70 = "Trenutni plasman u Svetskom Kupu"
71 = "Trenutni plasman u Timskom Kupu"
75 = "Propustas"
76 = "takmicenja"
77 = "rundu"
78 = "takmicenje"
79 = "je diskvalifikovan!"
81 = "Rezultati - Takmicenje"
82 = "Kvalifikacije - Takmicenje"
83 = "od 4"
84 = "Turneja 4 Skakaonice - Takmicenje"
85 = "Konacni rezultati Turneje 4 Skakaonice"
86 = "(kompaktna lista)"
87 = "Plasman posle takmicenja"
88 = "Skakac"
89 = "Statistika Svetskog Kupa za"
90 = "Konacni rezultati od"
91 = "Plasman Timskog Kupa posle takmicenja"
92 = "Konacni rezultati Timskog Kupa"
93 = "Statistika Timskog Kupa za"
94 = "Parovi u nok-aut sistemu"
95 = "Plasman"
96 = "Kralj Skakaonice"
97 = "Skor"
98 = "SK"
99 = "4 skakaonice:"
100 = "Ukupno:"
101 = "Ispao/li iz takmicenja:"
102 = "Vise ne skace/u:"
103 = "Eliminisan/i skakac/i:"
104 = "U svlacionici/ama:"
105 = "Nije/su vise sa nama:"
106 = "Gde?"
107 = "Tim:"
108 = "Poz."
109 = "Poena"
110 = "TK"
111 = "Pripremite se za Timski Kup"
112 = "Raspored Timskog Kupa:"
113 = "Dajte ime timu"
114 = "Tim"
115 = "Najbolji rezultat:"
116 = "Ucitaj set svojih skakaonica"
117 = "Sacuvaj set svojih skakaonica"
118 = "Izaberi skakaonice za svoj Kup"
119 = "Koristi strelice, ENTER startuje, ESC iskljucuje"
120 = "Kompjuterski skakaci:"
121 = "Igraj *Kralj Skakaonice*"
122 = "Izaberi nivo izazova"
123 = "Izaberi protivnike"
124 = "Skakaonica"
125 = "Vetar?"
126 = "Runde?"
127 = "Vrati se u Glavni Meni"
128 = "Novi rekord tvog seta!"
129 = "Stari rekord:"
130 = "K.S. nivo izazova"
131 = "KONACNI OBRACUN"
132 = "TVRDI ORASI"
133 = "POVREMENA OFANZIVA"
134 = "TOTALNO POBEDIVI"
135 = "STARCI U KUCI"
136 = "DEVOJCICE U ROZE SUKNJICAMA"
137 = "CUSTOM"
138 = "Izaberi svoje protivnike"
139 = "Koristi strelice da izaberes nivo"
140 = "ENTER bira, ESC iskljucuje"
141 = "Ime"
142 = "Plasman"
143 = "Kralj!"
146 = "(Koristi strelice, ENTER, DEL ili ESC)"
150 = "(Koristi strelice, ENTER ili ESC)"
151 = "Gde ti"
152 = "Zelis da skaces"
153 = "Danas?"
154 = "Izlaz"
155 = "Nasumice izabrana skakaonica SK"
156 = "Jos skakaonica..."
157 = "Stranica"
158 = "Sledeca stranica"
159 = "Prethodna stranica"
160 = "Izazovi Kralja Skakaonice"
161 = "Nije zavrsen"
162 = "Sacuvani najbolji rezultati napravljenih skakaonica"
163 = "Top 20 rezultata SJ3 Svetskog Kupa"
164 = "Top 10 rezultata Timskog Kupa"
165 = "Top 5 skorova Turneje 4 skakaonice"
166 = "Ime"
167 = "Poz."
168 = "Poena"
169 = "Kada?"
170 = "Rekordi skakaonica"
171 = "Ko?"
172 = "Koliko?"
173 = "Fajl"
174 = "Poeni"
175 = "Glavni Setup Meni"
176 = "Ovo su generalne opcije"
177 = "Neke opcije u vezi skokova"
178 = "Neke opcije u vezi hiscore-ova"
180 = "O da"
181 = "Sigurno"
182 = "Da gospodine"
183 = "Da"
184 = "To"
185 = "O ne"
186 = "Nema sanse"
187 = "Negativno"
188 = "Ne"
189 = "Nikako"
190 = "Reset"
191 = "Izbrisi"
192 = "Hiscore-ove?"
193 = "Da li si siguran?"
194 = "Oko brisanja"
195 = "Izadji iz setup-a"
196 = "Generalne opcije"
197 = "Skakacke opcije"
198 = "Hiscore i Setup Opcije"
199 = "Podesi tastere"
200 = "Postavi ciljeve za rekorde skakaonica"
201 = "Hill Maker"
203 = "Vrati se u Glavni Setup Meni"
204 = "Jezik?"
205 = "Bip?"
206 = "Nivo grafickih detalja?"
207 = "Set imena komp. protivnika (NAMES?.SKI)?"
208 = "Stavke u sivom su dostupne"
209 = "samo u registrovanoj verziji"
211 = "Vrati se u Glavni Setup Meni"
212 = "Trening runde?"
213 = "Dodatna statistika?"
214 = "Pokazi rezultate sa razlikama?"
215 = "Pokazi plasman SK-a sa razlikama?"
216 = "Kompaktna tabela?"
217 = "Nevidljive pozadine tabela?"
218 = "Automatski sacuvati snimke Rekorda skakaonica?"
219 = "Nacrtaj ciljeve za rekorde skakaonica?"
220 = "Izaberi gledanje kompjuterskih skakaca?"
221 = "Izaberi mesto vetrometra"
222 = "Koristi nok-aut sistem u 4 skakaonice?"
225 = "Izadji iz Hiscore Setup-a"
226 = "Mogu li komp. skakaci da postave rekorde?"
227 = "Dozvoli vise Identicnih imena na listi"
228 = "Resetuj Hiscore-ove"
229 = "Vrati Hiscore-ove"
230 = "Vrati Default vrednosti Setupa"
231 = "Nikada"
232 = "Ne na 4 skakaonice"
233 = "Uvek"
235 = "Lider"
236 = "Top 3"
237 = "Top 5"
238 = "Top 10"
239 = "Svi!"
240 = "Niko"
242 = "Cilj"
243 = "Koristi strelice, ESC izlazi"
245 = "Vec odlazis?"
246 = "PRET"
247 = "SLED"
248 = "KRAJ"
251 = "Dakle odlazis..."
252 = "Da li zaista zelis da iskljucis?"
253 = "Oh, ovako rano odlazis?"
256 = "Da li si siguran u vezi ovoga?"
257 = "Da li si apsolutno siguran?"
258 = "Pritisni D da napustis igricu."
261 = "Ahaj! Moras imati cetiri (4)"
262 = "ili osam (8) prijavljenih igraca"
263 = "da bi igrao Timski Kup!"
264 = "Idi i pitaj svoje drugove da se pridruze"
265 = "ili samo kloniraj sebe cetiri puta."
270 = "SJ3 Hill Maker"
271 = "(koristi strelice, DEL,"
272 = " ENTER ili ESC)"
273 = "Ime fajla"
274 = "Ime skakaonice"
275 = "*Dodaj novu skakaonicu*"
276 = "-Izlaz-"
277 = "-Start-"
278 = "Testiraj svoju skakaonicu!"
280 = "Strelica gore"
281 = "Strelica levo"
282 = "Strelica desno"
283 = "Strelica dole"
285 = "(U)citaj set"
286 = "(S)acuvaj set"
287 = "(N)asumicni set"
288 = "S(O)rtiraj po poenima u Svetskom Kupu"
289 = "S(O)rtiraj po ukupnom broju poena"
290 = "Nisu pronadjeni snimci!"
291 = "Autor:"
292 = "Ime:"
293 = "Ime fajla:"
294 = "Skakaonica:"
295 = "Izadji, nemoj da sacuvas"
296 = "Izadji i sacuvaj"
298 = "(S)acuvaj snimak"
300 = "Skakaci"
301 = "Izaberi skakace"
302 = "*Kreiraj novog skakaca*"
304 = "Ime:"
305 = "Pravo ime:"
306 = "Boja odela:"
307 = "Boja skija:"
308 = "Menja:"
309 = "Trener:"
310 = "Preskoci kvalifikacije:"
311 = "Resetuj skakaca"
312 = "Izlaz"
313 = "Ukupno skokova:"
314 = "Zavrsenih SK-a:"
315 = "Pobeda:"
316 = "Osvojenih SK-a:"
317 = "Najbolji rezultat u SK-u:"
318 = "Najbolji rezultat na 4S:"
319 = "Najduzi skok u SK-u:"
320 = "Najduzi skok:"
321 = "Nivo Kralja skakaonice:"
322 = "(Koristi strelice,"
323 = "ENTER edituje skakaca,"
324 = "DEL sklanja iz redosleda)"
325 = "ENTER prijavljuje skakaca,"
326 = "DEL brise skakaca)"
328 = "Brise skakaca"
329 = "Resetuje skakaca"
330 = "Kljucna mapa"
331 = "Odraz"
332 = "Rotiraj napred"
333 = "Rotiraj nazad"
334 = "Telemark doskok"
335 = "Doskok na dve noge"
336 = "Vraca default"
337 = "Izlaz"
340 = "Vreme leta"
341 = "Duzina"
342 = "Brzina:"
343 = "Napravljeni"
345 = "vec postoji."
346 = "Prekopiraj?"
350 = "Snimak je dobro sacuvan."
351 = "Snimak nije sacuvan."
352 = "Napravljeni set je dobro sacuvan."
353 = "Napravljeni set nije sacuvan."
354 = "Ekstra skakaonica je dobro sacuvana."
355 = "Ekstra skakaonica nije sacuvana."
356 = "Nisu pronadjeni napravljeni setovi!"
360 = "Dobrodosao u SJ3 i sport skijaskih skokova."
361 = "Evo kratkog uvoda u igricu."
362 = "Ideja u ovom sportu je da letis sto je duze"
363 = "moguce i izvedes bezbedan doskok."
364 = "Tvoj skakac sedi na klupi na pocetku"
365 = "zaletista.  Koristi strelicu desno kako bi poceo da klizis."
366 = "Vetrometar je lociran u donjem levom uglu. Vetar"
367 = "u glavu (negativan) je bolji jer te podize."
368 = "Kljuc uspesnog skoka je tajming kod"
369 = "odraza.  Koristi strelicu gore da se odrazis."
370 = "Sada treba da rotiras skakaca napred da bi"
371 = "smanjio otpor vetra.  Koristi strelicu desno."
372 = "Nekad te nalet vetra moze izbaciti iz"
373 = "ravnoteze.  Koristi strelicu levo da popravis poziciju."
374 = "Kako se priblizavas zemlji bilo bi dobro da"
375 = "pocnes da razmisljas o bezbednom doskoku skakaca."
376 = "'T' taster oznacava Telemark doskok.  Izvodi se"
377 = "sporije i manje je bezbedan ali donosi bolje poene za stil."
378 = "'R' taster oznacava doskok na dve noge,"
379 = "bezbedniji je i dobar je za dugacke skokove."
380 = "To je to! Mozes videti ovaj uvod ponovo iz"
381 = "menija Snimci a za vise informacija, procitaj MANUAL.TXT."
390 = "Gore"
391 = "Sredina"
392 = "Dole"
393 = "Levo"
394 = "Centar"
395 = "Desno"
396 = "Skakac"
400 = "Trenerov ugao:"
401 = "Profesionalan"
402 = "Pokusaj da se ne spustis toliko u letu."
403 = "Dobra pozicija u letu."
404 = "Pozicija u letu ti je suvise uspravna."
405 = "Sledeci put - doskoci."
406 = "Zapocni doskok ranije."
407 = "Uh, steta za ovo."
410 = "To je bedan skok."
411 = "Jos uvek ne izgleda sjajno."
412 = "To je sasvim dobar skok."
413 = "Dobar skok."
414 = "Odlican skok!"
415 = "Neverovatno!  Skidam ti kapu!"
418 = "Mnogo ranije se odrazi."
419 = "Suvise si zakasnio sa odrazom."
420 = "Tajming jos uvek malo kasni."
421 = "Bolji tajming ovog puta."
422 = "Savrsen tajming kod odraza!"
423 = "Malo si poranio sa odrazom."
424 = "Nemoj tako rano da se odrazis."
425 = "To je ocajan odraz. Odrazi se mnogo kasnije."
428 = "Mislim mnogo ranije."
429 = "Ovog puta si jednostavno zakasnio."
430 = "Doskok je bio na samoj ivici."
431 = "Ok tajming kod doskoka."
432 = "To bi trebalo da ti donese dobre poene za stil."
433 = "Mogao si jos da cekas pre doskoka."
434 = "Nemoj da se plasis da letis duze."
435 = "Pritisni 'T' ili 'R' taster, molicu."
441 = "Opusten"
442 = "Au, ne rotiraj previse, covece."
443 = "To je slatka pozicija u letu."
444 = "Ne plasi se da se vise nagnes napred, sinovac."
445 = "Molim te doskoci sledeci put, to boli."
446 = "I dalje doskaces na lice, decko."
447 = "Pa, ne mozes uvek da ustanes, znas."
450 = "Previse si se opustio."
451 = "Jea, pokusaj da se ne oznojis."
452 = "To vec izgleda bolje."
453 = "To ja nazivam lepim letom."
454 = "O da, ribama ce se ovo dopasti!"
455 = "To je ogromno! Zelim da upoznas Supermena!"
458 = "Kakav bedan odraz..."
459 = "Ako zelis da letis, odrazi se ranije."
460 = "Tajming ti nije sjajan."
461 = "Veoma dobar odraz, covece."
462 = "Hej, dopao mi se tvoj odraz!"
463 = "Malo si poranio sa odrazom."
464 = "Nemoj da zuris sa odrazom."
465 = "Oh, povredices se jednog dana."
468 = "Trebao bi da poradis na tom doskoku."
469 = "Zar se ne plasis da ces poginuti?"
470 = "Vau, taj doskok je bio na ivici."
471 = "Doskok - cvrst kao stena."
472 = "Oh, Mr. Perfektan Doskok je u gradu."
473 = "Nemoj da zuris sa osecajem za doskok..."
474 = "Nemoj da se uplasis u letu."
475 = "Ne plasi se tastature, deckonjo."
481 = "Strog"
482 = "Suvise si se nagnuo napred u letu, glupane."
483 = "To je solidna pozicija u letu."
484 = "Casna sestro! Rotiraj u skoku kao muskarac."
485 = "O Boze! Gde ti je doskok?"
486 = "Ne! Zapocni prokleti doskok na vreme!"
487 = "Dizi zadnjicu i vrati se na posao!"
490 = "Nikada nisam video gori skok."
491 = "Moja baba skace bolje od tebe."
492 = "Sta nije u redu? Hoces kuci kod mamice?"
493 = "Mozes mnogo bolje."
494 = "Neki treneri bi bili srecni ovim."
495 = "Sada skaces kao sto sam ti rekao."
498 = "Ocajno! Gde ti je prokleti odraz!"
499 = "Opet si se kasno odrazio. 50 sklekova!"
500 = "Tajming ti je i dalje los. 25 sklekova!"
501 = "Zar ne mozes da se odrazis malo ranije?"
502 = "Sada je odraz kakav sam i zeleo da bude."
503 = "Prerano!  Zar ne mozes da naucis?"
504 = "Katastrofalan odraz! Uradi mi 50 sklekova!"
505 = "Nikada nisam video gori odraz. Idi kuci."
508 = "Da li ti je doskok pretezak, mamina mazo?"
509 = "Ne! Zapocni prokleti doskok na vreme!"
510 = "Taj doskok je previse rizican."
511 = "To je skoro licilo na doskok."
512 = "Izgleda da je to dobar doskok."
513 = "Nemoj da se plasis doskoka."
514 = "Cega se plasis? Leti, do djavola!"
515 = "Da li si glup? Doskoci ili idi kuci!"
