id = "suomi"
name = "Suomi"

[strings]
1 = "Yksi"
2 = "Kaksi"
3 = "Kolme"
4 = "Neljä"
5 = "Viisi"
6 = "Kyllä"
7 = "Ei"
8 = "/"
9 = "Ei yhtään"
11 = "Rekisteröity"
12 = "Shareware"
13 = "Normaali"
14 = "Matala"
15 = "Paina jotain..."
17 = "Päävalikko"
18 = "Hyppyvalikko"
20 = "Hyppäämään!"
21 = "Ilmoita Hyppääjät"
22 = "Asetukset"
23 = "Kunniataulut"
24 = "Mäkiennätykset"
25 = "Uusinnat"
26 = "Lopeta SJ3"
27 = "SJ3 Maailmancup"
28 = "Tee-Se-Itse-Cup"
29 = "Mäkiviikko"
30 = "Joukkuemäkicup"
31 = "Kukkulan Kuningas"
32 = "Harjoitukset"
33 = "Päävalikkoon"
34 = "Hyppääjät:"
35 = "Tämän version ylpeä"
36 = "omistaja on:"
38 = "Tämä on rekisteröimätön"
39 = "versio SJ3:sta."
40 = "Lue Register.Txt"
41 = "Haluatko olla kyläsi"
42 = "kovin jätkä?,"
43 = "Kaipaatko lisää uskottavuutta"
44 = "kaveripiirissäsi?"
45 = "Tue kotimaista peliteollisuutta."
46 = "Ole mies, rekisteröi."
47 = "Rekisteröimätön versio"
48 = "sallii vain kaksi pelaajaa."
51 = "Harjoitukset"
52 = "Harjoituskierros"
53 = "Karsintakierros"
54 = "1. kierros"
55 = "2. kierros"
56 = "Seuraavana..."
57 = "Tietokonehyppääjät..."
58 = "Lähtölava:"
59 = "Paina (A) muuttaaksesi asetuksia"
60 = "A"
61 = "Tällä hetkellä"
62 = "Johtoon riittää"
63 = "Voittoon riittää"
65 = "Mäkiennätys"
67 = "Hyppääjiä jäljellä:"
68 = "Jatkoon riittää:"
69 = "Viimeinen:"
70 = "Nykyinen MC-tilanne"
71 = "Nykyinen JC-tilanne"
75 = "Poissa"
76 = "kilpailua"
77 = "seur. kierroksen"
78 = "seur. kilpailun"
79 = "on Hylätty!"
81 = "Tulosluettelo - Kilpailu"
82 = "Karsinta - Kilpailu"
83 = "/ 4"
84 = "Mäkiviikko - Kilpailu"
85 = "Mäkiviikon lopputulokset"
86 = "(tiivistetty luettelo)"
87 = "Tilanne - Kilpailu"
88 = "Hyppääjä"
89 = "Maailmancuptilastot:"
90 = "Lopputulokset"
91 = "Joukkuemäkitilanne - Kilpailu"
92 = "Joukkuemäkicupin lopputulokset"
93 = "Joukkuemäkitilastot - Joukkue:"
94 = "Pudotuskilpailun parit"
95 = "Tulokset"
96 = "Kukkulan Kuningas"
97 = "Tulos"
98 = "MC"
99 = "Mviikko:"
100 = "Yhteensä:"
101 = "Pukuhuoneen Puolella:"
102 = "Kisasta Pudonneet:"
103 = "Keskuudestamme Poistuneet:"
104 = "Hyppylupa evätty:"
105 = "Jo Suihkun Puolella:"
106 = "Missä?"
107 = "Joukkue:"
108 = "Sij"
109 = "Pst"
110 = "JM"
111 = "Valmistaudu Joukkuemäkeen"
112 = "Joukkuemäen aikataulu:"
113 = "Nimeä joukkue"
114 = "Joukkue"
115 = "Paras tulos:"
116 = "Lataa Tee-Se-Itse-sarja"
117 = "Tallenna Tee-Se-Itse-sarja"
118 = "Valitse mäet Tee-Se-Itse-Cupiin"
119 = "Käytä nuolia, ENTER aloittaa, ESC poistuu"
120 = "Tietokonehyppääjät:"
121 = "Aloita *Kukkulan Kuningas*"
122 = "Valitse Haastetaso"
123 = "Valitse Vastustajat"
124 = "Hypätään:"
125 = "Tuuli?"
126 = "Kierroksia?"
127 = "Palaa Päävalikkoon"
128 = "Uusi Tee-Se-Itse-sarjan ennätys!"
129 = "Vanha ennätys:"
130 = "K.K. Haastetaso"
131 = "Äärimmäinen Haaste"
132 = "Paha nakki"
133 = "Vaihtelevaa Maastoa"
134 = "Täysin Hoideltavissa"
135 = "Vanhainkodin Vastus"
136 = "Pikkutyttöjä kukkamekoissa"
137 = "Tee-Se-Itse"
138 = "Valitse Vastustajasi"
139 = "Valitse nuolilla taso"
140 = "ENTER hyväksyy, ESC poistuu"
141 = "Nimi"
142 = "Taso"
143 = "Kunkku!"
146 = "(Kursorit, ENTER, DEL ja ESC)"
150 = "(Kursorit, ENTER ja ESC)"
151 = "Missä Sinä"
152 = "Haluat Hypätä"
153 = "Tänään?"
154 = "Poistu"
155 = "Satunnainen"
156 = "Lisää Mäkiä..."
157 = "Sivu"
158 = "Seuraava sivu"
159 = "Edellinen sivu"
160 = "Kukkulan Kuningas Haasteet"
161 = "Selvittämättä"
162 = "Tallennetut Tee-Se-Itse-sarjat"
163 = "20 Parasta SJ3 Maailmancuptulosta"
164 = "10 Parasta Joukkuemäkitulosta"
165 = "5 Parasta Mäkiviikon pistesaalista"
166 = "Nimi"
167 = "Sij"
168 = "Pisteet"
169 = "Milloin?"
170 = "Mäkiennätykset"
171 = "Kuka?"
172 = "Paljonko?"
173 = "Tiedosto"
174 = "Pisteet"
175 = "Asetuksien Päävalikko"
176 = "Yleisasetukset"
177 = "Hyppäämiseen liittyvät asetukset"
178 = "Kunniatauluasetukset"
180 = "Joo"
181 = "Toki"
182 = "Kyllä"
183 = "Jep"
184 = "Juu"
185 = "Ei ei"
186 = "Ei käy"
187 = "Ei"
188 = "Ei sovi"
189 = "Älä"
190 = "Alusta"
191 = "Nollaa"
192 = "Kunniataulut?"
193 = "Oletko ihan varma?"
194 = "Poistamassa"
195 = "Poistu Asetuksista"
196 = "Yleiset Asetukset"
197 = "Hyppäämiseen liittyvät asetukset"
198 = "Kunniataulujen asetukset"
199 = "Valitse näppäimet"
200 = "Aseta Pituustavoitteet"
201 = "Mäkien hallinta"
203 = "Paluu Asetukset.Päävalikkoon"
204 = "Kieli?"
205 = "Äänimerkit?"
206 = "Lisägrafiikan taso?"
207 = "Vastustajien nimitiedosto (NAMES?.SKI)?"
208 = "Harmaat valinnat toimivat"
209 = "vain rekisteröidyssä versiossa"
211 = "Palaa Pääasetusvalikkoon"
212 = "Harjoituskierroksia?"
213 = "Lisätilastoja?"
214 = "Näytä tuloslistat erotuksina?"
215 = "Näytä MC-tuloslistat erotuksina?"
216 = "Tiivistetyt tuloslistat?"
217 = "Läpinäkyvät listojen taustat?"
218 = "Tallenna mäkiennätykset automaattisesti?"
219 = "Piirrä Pituustavoitteet?"
220 = "Valitse katsotut tietokonehyppääjät"
221 = "Valitse tuulimittarin paikka"
222 = "Käytä Pudotuskilpailua mäkiviikolla?"
225 = "Poistu Edelliseen"
226 = "Tietokoneen tekemät mäkienkat?"
227 = "Saako listalla olla samoja nimiä?"
228 = "Alusta Kunniataulut"
229 = "Nollaa Kunniataulut"
230 = "Palauta Asetusten Alkuarvot"
231 = "Ei"
232 = "Ei MViikolla"
233 = "Aina"
235 = "Johtaja"
236 = "3 Parasta"
237 = "5 Parasta"
238 = "10 Parasta"
239 = "Kaikki!"
240 = "Ei yhtään"
242 = "Tavoite"
243 = "Käytä nuolia, ESC poistuu"
245 = "Lähdössä pois?"
246 = "EDEL"
247 = "SEUR"
248 = "VALM"
251 = "Lähdet sitten menemään..."
252 = "Haluatko varmasti pois?"
253 = "Älä nyt näin aikaisin lähde."
256 = "Oletko ihan varma?"
257 = "Oletko tosissasi?"
258 = "Kirjaimella K poistutaan."
261 = "Stoi! Sinun pitää ilmoittaa neljä (4)"
262 = "tai kahdeksan (8) pelaajaa, että"
263 = "voisit osallistua joukkuekisaan!"
264 = "Pyydä pari kaveria mukaan tai"
265 = "ilmoita itsesi mukaan neljä kertaa..."
270 = "SJ3 Mäkieditori"
271 = "(käytä nuolia,"
272 = " ENTERiä tai ESCiä)"
273 = "Tiedosto"
274 = "Mäki"
275 = "*Lisää Uusi*"
276 = "-Poistu-"
277 = "-Aloita-"
278 = "Kokeile!"
280 = "Nuoli Ylös"
281 = "Nuoli Vasen"
282 = "Nuoli Oikea"
283 = "Nuoli Alas"
285 = "(L)ataa"
286 = "(T)allenna"
287 = "(S)atunnainen"
288 = "(J)ärjestä MC-pisteiden mukaan"
289 = "(J)ärjestä kokonaispisteiden mukaan"
290 = "Uusintoja ei löytynyt!"
291 = "Tekijä:"
292 = "Nimi:"
293 = "Tiedosto:"
294 = "Mäki:"
295 = "Poistu, älä tallenna"
296 = "Poistu ja tallenna"
298 = "(T)allenna Uusinta"
300 = "Hyppääjät"
301 = "Valitse hyppääjät"
302 = "*Luo uusi hyppääjä*"
304 = "Nimi:"
305 = "Oikea nimi:"
306 = "Puvun väri:"
307 = "Suksien väri:"
308 = "Korvaa:"
309 = "Valmentaja:"
310 = "Jätä karsinta:"
311 = "Nollaa Hyppääjä"
312 = "Poistu"
313 = "Hypyt yhteensä:"
314 = "Käydyt Maailmancupit:"
315 = "Osakilpailuvoitot:"
316 = "Maailmancupvoitot:"
317 = "Paras MC-tulos:"
318 = "Paras mäkiviikko:"
319 = "Pisin MC-hyppy:"
320 = "Pisin hyppy:"
321 = "Kukkulan kuningas-taso:"
322 = "(Käytä nuolia,"
323 = "ENTER editoi hyppääjää,"
324 = "DEL poistaa järjestyksestä)"
325 = "ENTER valitsee,"
326 = "DEL poistaa hyppääjän)"
328 = "Poista hyppääjä"
329 = "Nollaa hyppääjä"
330 = "Näppäimet"
331 = "Ponnistus"
332 = "Kierrä eteenpäin"
333 = "Nosta hyppääjää"
334 = "Telemark-alastulo"
335 = "Tasajalka-alastulo"
336 = "Palauta asetusarvot"
337 = "Poistu"
340 = "Lentoaika"
341 = "Pituus"
342 = "Katselunopeus:"
343 = "Autom."
345 = "on jo olemassa."
346 = "Kirjoita päälle?"
350 = "Uusinta tallennettiin."
351 = "Uusintaa ei tallennettu."
352 = "Sarja tallennettiin."
353 = "Sarjaa ei tallennettu."
354 = "Lisämäki tallennettiin."
355 = "Lisämäkeä ei tallennettu."
356 = "Tee-Se-Itse-sarjoja ei löydy!"
360 = "Tervetuloa SJ3:n ja mäkihypyn pariin."
361 = "Seuraavassa on pieni esittely peliin."
362 = "Mäkihypyssä idea on lentää mahdollisimman"
363 = "pitkälle ja laskeutua turvallisesti."
364 = "Hyppääjäsi istuu puomilla ylämäen päässä."
365 = "Käytä Nuoli Oikealle-näppäintä aloittaaksesi laskun."
366 = "Tuulimittari sijaitsee ruudun vasemmassa alareunassa."
367 = "Vastatuuli on parempi, sillä se parantaa nostetta."
368 = "Hyvän hypyn A ja O on ponnistuksen ajoitus."
369 = "Ponnistus tapahtuu painamalla Nuoli Ylös-näppäintä."
370 = "Sen jälkeen kannattaa kiertää hyppääjää eteenpäin"
371 = "Nuoli Oikea-näppäimellä.  Näin ilmanvastus pienenee."
372 = "Joskus tuulenpuuska saattaa osua hyppääjääsi."
373 = "Nuoli Vasemmalle-näppäin nostaa hyppääjää."
374 = "Maapallon lähestyessä on syytä ajatella"
375 = "hyppääjäsi tuomista turvallisesti alas."
376 = "'T'-näppäin aloittaa Telemark-laskeutumisen.  Se on"
377 = "hitaampi ja alttimpi kaatumiselle, mutta tyylikkäämpi."
378 = "'R'-näppäin aloittaa Tasajalka-alastulon, joka on"
379 = "nopeampi tehdä ja turvallisempi pitkiin hyppyihin."
380 = "Siinäpä se!  Voit katsoa tämän esittelyn uudestaan"
381 = "Uusinnat-valikosta. Lisätietoja lukemalla MANUAL.TXT."
390 = "Ylä"
391 = "Keski"
392 = "Ala"
393 = "Vasen"
394 = "Keski"
395 = "Oikea"
396 = "Hyppääjä"
400 = "Valmentaja sanoo:"
401 = "Asiallinen"
402 = "Yritä olla päästämättä lentoasentoa noin alas."
403 = "Hyvä lentoasento."
404 = "Lennät hieman liian pystyssä."
405 = "Koita tehdä alastulo ensi kerralla."
406 = "Aloita alastulo aikaisemmin."
407 = "Oho, huonoa tuuria."
410 = "Ei ollut häävi hyppy."
411 = "Ei vieläkään ole oikein hyvä."
412 = "Ihan hyvin hypätty."
413 = "Hyvää meininkiä."
414 = "Erinomainen hyppy!"
415 = "Uskomaton! Onko sulla siivet?"
418 = "Aloita ponnistus paljon aikaisemmin."
419 = "Ponnistuksen ajoitus oli myöhässä."
420 = "Ponnistus oli vähän myöhässä."
421 = "Ihan hyvä ajoitus tällä kertaa."
422 = "Loistava ponnistuksen ajoitus."
423 = "Vähän liian aikaisin ponnistettu."
424 = "Älä aloita ponnistusta noin aikaisin."
425 = "Kauhea ponnistus.  Aloita se myöhemmin."
428 = "Paljon aikaisemmin."
429 = "Alastulo oli vähän myöhässä."
430 = "Alastulo oli ihan hilkulla."
431 = "Hyvä rauhallinen alastulo."
432 = "Nyt pitäisi tulla hyvät tyylipisteet."
433 = "Alastulo oli vähän liian varovainen."
434 = "Ei alastulolla noin kiire ole."
435 = "Paina 'T' tai 'R' näppäintä."
441 = "Rento"
442 = "Kato älä mee liikaa päälle."
443 = "Toi on siisti lentoasento."
444 = "Älä hannaa nojaa kunnol eteen."
445 = "Hei spede, tee ny ees alastulo."
446 = "Jätkä tulee lärvillee alas."
447 = "Oho, oli vähä paska flaksi."
450 = "No toi on ihan hanurista."
451 = "Koita ny vähän vetää ees."
452 = "Tsemii hei. Mimmit tsiigaa."
453 = "Tos oli ihan jees meininki."
454 = "Jees, tosi bueno veto."
455 = "Viddu! Äijä vetää ku Teris!"
458 = "Toi sun ponnistus imee munia."
459 = "Vedä se ponnistus kato ajoissa."
460 = "Vieläki myöhäs toi sun pomppu."
461 = "Aika nasta ajoitus tossa."
462 = "Äijän ajoitus oli tosi jees."
463 = "Vähän ajoissa vedetty."
464 = "Mikä kiire sull on?"
465 = "Toi menee ihan miten sattuu."
468 = "Kantsis vähä kelaa tota alastuloo."
469 = "Älä vedä tolleen.  Studaa glyyvis."
470 = "Just hikinen toi alastulo."
471 = "Ihan rento alastulo hei."
472 = "Hei kato kundii, magee alastulo."
473 = "Aika ajoissa otit sen alas."
474 = "Mitä sä skagaat?  Lennä kunnolla."
475 = "Älä hannaa skulaa sitä näppistä."
481 = "Tiukkapipo"
482 = "Lentoasento ihan liian edessä."
483 = "Lentoasento ehkä kelpaa."
484 = "Kierrä kunnolla päälle, nynny!"
485 = "Missäs laskeutuminen oli, häh?"
486 = "Ei! Aloita se alastulo ajoissa!"
487 = "Ylös perseeltäsi ja takaisin ylös!"
490 = "En ole koskaan nähnyt surkeampaa."
491 = "Äitinikin hyppää paremmin."
492 = "Mikäs nyt? Haluatko lähteä kotiin?"
493 = "Sinä pystyt paljon parempaan."
494 = "Olen juuri ja juuri tyytyväinen."
495 = "Kerrankin hyppäsit ohjeitteni mukaan."
498 = "Hirveää! Missäs ponnistus oli?!"
499 = "Ponnistus myöhässä. 50 punnerrusta!"
500 = "Ajoitus edelleen huono. 25 punnerrusta!"
501 = "Etkö sinä osaa ponnistaa ajoissa?"
502 = "Nyt se ponnistus oli siellä päin."
503 = "Ponnistus liian ajoissa! Yritä vähän."
504 = "Hirvittävä ponnistus! 50 punnerrusta!"
505 = "Kukaan ei ole noin huono. Lähde kotiin."
508 = "Onko alastulo vaikeaa, mammanpoika?"
509 = "Ei! Aloita nyt se alastulo ajoissa!"
510 = "Otit tyhmän riskin tuossa alastulossa."
511 = "Tuo melkein näytti alastulolta."
512 = "Alastulo oli vähän sinne päin."
513 = "Älä arkaile sen alastulon kanssa."
514 = "Mitä sinä pelkäät? Lennä kunnolla!"
515 = "Idiootti! Laskeudu tai lähde kotiin!"
520 = "Load Cup"
521 = "Save cup state?"
522 = "Current jump is lost."
523 = "No saved cups"
524 = "MULTIPLAYER"
