id = "svenska"
name = "Svenska"

[strings]
1 = "En"
2 = "Två"
3 = "Tre"
4 = "Fyra"
5 = "Fem"
6 = "Ja"
7 = "Nej"
8 = "av"
9 = "Ingen"
11 = "Registrerad"
12 = "Shareware"
13 = "Normal"
14 = "Låg"
15 = "Tryck valfri tangent..."
17 = "Huvudmeny"
18 = "Hoppmeny"
20 = "Hoppa!"
21 = "Ny hoppare"
22 = "Inställningar"
23 = "Hall of Fame"
24 = "Backrekord"
25 = "Repriser"
26 = "Avsluta SJ3"
27 = "SJ3 Världscup"
28 = "Egen Världscup"
29 = "Backvecka"
30 = "Lagtävling"
31 = "Backarnas Konung"
32 = "Träna"
33 = "Huvudmenyn"
34 = "Backhoppare:"
35 = "Denna version"
36 = "är registrerad till:"
38 = "Detta är en oregistrerad"
39 = "version av SJ3."
40 = "Läs Register.Txt Nu!"
41 = "För att veta hur man blir"
42 = "coolast i sta'n:"
43 = "Bli respekterad av dina vänner."
44 = "Registrera SJ3 nu!"
45 = "Detta spel är ej freeware."
46 = "Gör det rätta, registrera."
47 = "Endast 2 spelare är tillåtna"
48 = "i denna shareware version."
51 = "Träna"
52 = "Träningsrunda"
53 = "Kvalificering"
54 = "Hoppomgång 1"
55 = "Hoppomgång 2"
56 = "Nästa..."
57 = "Datorhoppare..."
58 = "Startport:"
59 = "Tryck (S) För Inställningar"
60 = "S"
61 = "För tillfället"
62 = "Krävs för ledning"
63 = "Krävs för vinst"
65 = "Backrekord"
67 = "Hoppare kvar:"
68 = "Krävs att slå:"
69 = "Sist för tillfället:"
70 = "Nuvarande VC Placeringar"
71 = "Nuvarande Lagtävlingsplaceringar"
75 = "Missar nästa"
76 = "Tävlingar"
77 = "Hoppomgång"
78 = "Tävling"
79 = "är Diskvalificerad!"
81 = "Resultat - Tävling"
82 = "Kvalificering - Tävling"
83 = "av 4"
84 = "Backveckan - Tävling"
85 = "Slutresultat i Backveckan"
86 = "(kompakt lista)"
87 = "- Ställning efter tävling"
88 = "Hoppare"
89 = "VC Statistik för"
90 = "Slutresultat i"
91 = "Ställning i lagtävlingen efter omgång"
92 = "Slutresultat i lagtävlingen"
93 = "Lagtävlingsinfo för"
94 = "Par i utsslagssystem"
95 = "Ställning"
96 = "Backarnas Konung"
97 = "P"
98 = "VC"
99 = "Backv.:"
100 = "Totalt:"
101 = "Ute ur tävlingen:"
102 = "Hoppar inte längre:"
103 = "Eliminerade hoppare:"
104 = "I Omklädningsrummet:"
105 = "Tävlar ej längre:"
106 = "Var?"
107 = "Lag:"
108 = "Pos"
109 = "P"
110 = "LT"
111 = "Gör dig klar för lagtävlingen"
112 = "Program för lagtävlingen:"
113 = "Namnge laget"
114 = "Lag"
115 = "Bästa Resultat:"
116 = "Ladda Eget Backset"
117 = "Spara Eget Backset"
118 = "Välj backar till din egen Världscup"
119 = "Använd Pilarna, ENTER startat, ESC avslutar"
120 = "Datorhoppare:"
121 = "Börja *Backarnas Konung*"
122 = "Välj Svårighetsgrad"
123 = "Välj Motståndare"
124 = "Hoppar på"
125 = "Vind?"
126 = "Omgångar?"
127 = "Huvudmeny"
128 = "Nytt Rekord för eget backset!"
129 = "Gammalt Rekord:"
130 = "UTMANARNIVÅ"
131 = "Det Ultimata Motståndet"
132 = "Hårdingarna"
133 = "Varierat Motstånd"
134 = "Helt Slagbara"
135 = "Gamlingarna"
136 = "Småflickorna"
137 = "Tillämpad"
138 = "Välj dina motståndare"
139 = "Använd pilarna för att välja nivå"
140 = "ENTER väljer, ESC avslutar"
141 = "Namn"
142 = "Rank"
143 = "Kungen!"
146 = "(Pilar, ENTER, DEL el ESC)"
150 = "(Pilar, ENTER el ESC)"
151 = "Var vill"
152 = "Du hoppa"
153 = "Idag?"
154 = "Avsluta"
155 = "Slumpmässig VC-backe"
156 = "Mera backar..."
157 = "Sida"
158 = "Nästa Sida"
159 = "Föregående Sida"
160 = "Backarnas Konung utmaningar"
161 = "Icke genomförd"
162 = "Spara Rekorden i eget backset"
163 = "Top 20 SJ3 Världscup Resultat"
164 = "Top 10 Lagtävlingsresultat"
165 = "Top 5 Resultat i Backveckan"
166 = "Namn"
167 = "Pos"
168 = "Poäng"
169 = "När?"
170 = "Backrekorden"
171 = "Vem?"
172 = "Hur Mycket?"
173 = "Fil"
174 = "Pts"
175 = "Inställningar"
176 = "Huvudinställningar"
177 = "Hoppinställningar"
178 = "Övriga Inställningar"
180 = "Ja"
181 = "Ja"
182 = "Ja"
183 = "Ja"
184 = "Ja"
185 = "Nej"
186 = "Nej"
187 = "Nej"
188 = "Nej"
189 = "Nej"
190 = "Återställ"
191 = "Nollställ"
192 = "Rekorden?"
193 = "Är du säker?"
194 = "Tar bort"
195 = "Lämna inställningar"
196 = "Huvudinställningar"
197 = "Hoppinställningar"
198 = "Övriga Inställningar"
199 = "Tangetinställningar"
200 = "Sätt målsättning för backrekorden"
201 = "Skapa Ny Backe"
203 = "Tillbaka till Inställningar"
204 = "Språk?"
205 = "PC Ljud?"
206 = "Grafiknivå?"
207 = "Motståndare (NAMES?.SKI)?"
208 = "* Endast tillgängligt i den"
209 = "den registrerade versionen"
211 = "Tillbaka till Inställningar"
212 = "Träningsrunda?"
213 = "Extra Statistik?"
214 = "Visa Resultat med skillnader ?"
215 = "Visa VC resultat med skillnader?"
216 = "Kompakta Resultat?"
217 = "Resultatrutans bakgrund osynlig?"
218 = "Automatiskt Spara Repriser av Backrekord?"
219 = "Rita ut målsättning för backrekord?"
220 = "Välj visade datorhoppare?"
221 = "Placera vindmätare"
222 = "Använd utslagssystem i 4H?"
225 = "Tillbaka till Inställningar"
226 = "Datorhoppare hoppar Backrekord?"
227 = "Tillåta många likadana namn i rekordlistan?"
228 = "Återställ Rekorden"
229 = "Nollställ Rekorden"
230 = "Återställ Inställningar"
231 = "Aldrig"
232 = "Inte i 4H"
233 = "Alltid"
235 = "Ledare"
236 = "Top 3"
237 = "Top 5"
238 = "Top 10"
239 = "Alla!"
240 = "Inga"
242 = "Målsättning"
243 = "Använd pilarna, ESC avslutar"
245 = "Går du redan?"
246 = "FÖRE"
247 = "NÄST"
248 = "KLAR"
251 = "Så du går nu..."
252 = "Vill du verkligen avsluta?"
253 = "Skall du faktiskt gå redan?"
256 = "Är du säker?"
257 = "Är du helt säker?"
258 = "Skriv J för att avsluta."
261 = "OBS! Du måste ha fyra (4)"
262 = "eller åtta (8) spelare anmälda"
263 = "för att starta Lagtävlingen!"
264 = "Gå och be dina vänner komma med"
265 = "eller klona dig själv fyra gånger."
270 = "SJ3 Backskaparen"
271 = "(Pilar, DEL,"
272 = " ENTER el ESC)"
273 = "Filnamn"
274 = "Backnamn"
275 = "*Lägg till ny backe*"
276 = "-Avsluta-"
277 = "-Start-"
278 = "Testa Din Backe!"
280 = "Uppåtpil"
281 = "Vänsterpil"
282 = "Högerpil"
283 = "Neråtpil"
285 = "(L)adda set"
286 = "(S)para set"
287 = "(R)andom set"
288 = "S(O)rtera Utifrån WC-poäng"
289 = "S(O)rtera Utifrån Totalpoäng"
290 = "Inga repriser funna!"
291 = "Skapare:"
292 = "Namn:"
293 = "Filnamn:"
294 = "Backe:"
295 = "Avsluta, Spare ej"
296 = "Avsluta samt spara"
298 = "(S)para Repris"
300 = "Hoppare"
301 = "Välj Hoppare"
302 = "*Skapa ny hoppare*"
304 = "Namn:"
305 = "Riktigt Namn:"
306 = "Dräktfärg:"
307 = "Skidfärg:"
308 = "Skriv Över:"
309 = "Tränare:"
310 = "Skippa Kval"
311 = "Nollställ Hoppare"
312 = "Tillbaka"
313 = "Totala Hopp:"
314 = "Antal VC-turneringar:"
315 = "Vunna omgångar:"
316 = "Vunna VC-turneringar:"
317 = "Bästa VC-resultat:"
318 = "Bästa fyrbacksresultat:"
319 = "Längsta VC-hopp:"
320 = "Längsta hopp:"
321 = "KOTH nivå:"
322 = "(Använd pilarna,"
323 = "ENTER konfigurerar hoppare,"
324 = "DEL tar bort från listan)"
325 = "ENTER anmäler,"
326 = "DEL raderar hoppare)"
328 = "Radera hoppare"
329 = "Återställer Hoppare"
330 = "Tangentkarta"
331 = "Avhopp"
332 = "Rotera framåt"
333 = "Rotera bakåt"
334 = "Telemarklandning"
335 = "Tvåfotslandning"
336 = "Grundinställningar"
337 = "Avsluta"
340 = "Flygtid"
341 = "Längd"
342 = "Hastighet:"
343 = "Egen"
345 = "Finns redan"
346 = "Skriv ÷ver?"
350 = "Repris sparad."
351 = "Repris ej sparad."
352 = "Eget set sparat."
353 = "Eget set ej sparat."
354 = "Extra backe sparad."
355 = "Extra backe ej sparad."
356 = "Inga egna set funna!"
360 = "Välkommen till SJ3 och backhoppningens värld."
361 = "Härnäst följer en kort introduktion av spelet."
362 = "Iden med sporten är att flyga så långt"
363 = "som möjligt och landa utan att skada sig"
364 = "Din hoppare sitter på en balk i början av"
365 = "backen. Använd höger pil för att påbörja hoppet."
366 = "Vindmätaren är belägen nere till vänster på"
367 = "skärmen. Motvind är bättre eftersom lyftkraften ökar."
368 = "Nyckeln till ett lyckat hopp är timing i"
369 = "uthoppet.  Använd uppåtpilen för att starta uthoppet."
370 = "Nu borde du rotera hopparen framåt för att"
371 = "minska vindmotståndet.  Använd höger pil."
372 = "Ibland kan en vindpust kasta dig ur"
373 = "balans.  Använd vänster pil för att korrigera."
374 = "Allteftersom marken närmar sig vore det vist att"
375 = "börja tänka på att göra en säker landning."
376 = "'T' knappen påbörjar telemarklandning.  Den är"
377 = "långsammare och osäkrare men ger högre stilpoäng."
378 = "'R' knappen påbörjar den säkrare tvåfotslandningen,"
379 = "vilken är bra vid långa hopp."
380 = "Det var allt! Du kan se denna introduktion igen från"
381 = "Reprismenyn och för mera info, läs MANUAL.TXT."
390 = "Toppen"
391 = "Mitten"
392 = "Botten"
393 = "Vänster"
394 = "Centrum"
395 = "Höger"
396 = "Hoppare"
400 = "Tränarn:"
401 = "Saklig"
402 = "Försök att inte flyga så lågt."
403 = "Bra flygposition."
404 = "Din flygposition är för lodrät!."
405 = "Försök landa nästa gång."
406 = "Starta landningen tidigare."
407 = "Det där berodde bara på otur."
410 = "Uselt hopp!."
411 = "Det ser inte tillräckligt bra ut ännu."
412 = "Ett rätt bra hopp."
413 = "Skickligt hoppat."
414 = "Perfekt hopp!"
415 = "Otroligt! Är du Stålmannen?"
418 = "Starta uthoppet mycket tidigare."
419 = "Uthoppet var för sent."
420 = "Fortfarande lite sen timing."
421 = "Rätt bra timing."
422 = "Perfekt timing vid uthoppet!"
423 = "Uthoppet var lite för tidigt."
424 = "Starta inte uthoppet så tidigt."
425 = "Förfärligt uthopp! Starta det mycket senare."
428 = "Jag menar mycket tidigare!."
429 = "För sent denna gång."
430 = "Landningen var nästan för sen."
431 = "Helt okej timing vid landningen."
432 = "Det borde ge höga stilpoäng."
433 = "Du kunde ha väntat längre före landning."
434 = "Var inte rädd att hoppa längre."
435 = "Tryck på 'T' eller 'R' knappen, tack."
441 = "Avslappnad"
442 = "Luta dig lite bakåt istället, kompis."
443 = "Sköön flygposition."
444 = "Var inte rädd att luta längre framåt, polarn."
445 = "Försök landa nästa gång, det där gör ont."
446 = "Du landar fortfarande huvudstupa, pojke lilla."
447 = "Oj, oj, oj..."
450 = "För avslappnat."
451 = "Ja, Ja..."
452 = "Det där ser bättre ut."
453 = "Det där är vad jag kallar ett bra hopp."
454 = "Tjejerna kommer att gilla det där!"
455 = "Enormt! Är du stålmannen?"
458 = "Vilket trögt uthopp..."
459 = "Tänkt komma någon vart? Starta uthoppet tidigare."
460 = "Din timing är inte den bästa."
461 = "Rätt bra timing faktiskt, mannen."
462 = "Wow! Vilket uthopp!"
463 = "Lite,lite senare uthopp, tack."
464 = "Har du bråttom? Starta senare..."
465 = "Nå'n dag kommer du att skada dig."
468 = "Du borde nog träna på landningen, min vän."
469 = "Är du inte rädd för att dö, dummer?.."
470 = "Den där landningen var nära att sluta illa."
471 = "Landningen satt som en sten."
472 = "Är det lilla proffset som hoppar?"
473 = "Landningen var i sista sekunden..."
474 = "Var inte rädd att flyga lite."
475 = "Tangetbordet bits inte..."
481 = "Strikt"
482 = "Alldeles för mycket framåtlutad, dumskalle."
483 = "Perfekt flygposition."
484 = "Pucko! Håll balansen som en man!."
485 = "Herre Gud, var det där en landning?"
486 = "Försök landa i tid, tjockskalle!"
487 = "Kämpa lite, då!"
490 = "Jag har aldrig i mitt liv sett ett sämre hopp."
491 = "Min morsa hoppar bättre än dig."
492 = "Vad är lilla fegisen rädd för?"
493 = "Bättre kan du, din lata hund!."
494 = "Det där var väl bra..."
495 = "Okej, så där skall det se ut."
498 = "Fasansfullt! Var är uthoppet!"
499 = "För sent uthopp. 50 armhävningar!"
500 = "Dålig timing. 25 armhävningar!"
501 = "Går det inte att starta uthoppet lite tidigare?"
502 = "Nu var uthoppet precis som det skall vara."
503 = "För tidigt!  Har du svårt att fatta?"
504 = "Katastrofalt uthopp, 50 armhävningar!"
505 = "Jag har aldrig sett ett sämre uthopp!."
508 = "Är det för svårt att landa, fegis?"
509 = "Nej! Starta den förbannade landningen i tid!"
510 = "Den landningen är alldeles för riskabel!."
511 = "Det där såg till och med ut som en landning."
512 = "Det där borde ha varit en okej landning."
513 = "Strula inte bort landningen."
514 = "Vad är du rädd för? Flyg!"
515 = "Är du tokig! Landa eller stick hem!"
520 = "Load Cup"
521 = "Save cup state?"
522 = "Current jump is lost."
523 = "No saved cups"
524 = "MULTIPLAYER"
