id = "original"
name = "World Cup 2024/25"
source = "FIS rankings 2025"
title = "FIS World Cup 2024/25 Top 77"

names = [
  "Domen Prevc",
  "Ryoyu Kobayashi",
  "Daniel Tschofenig",
  "Ren Nikaido",
  "Anze Lanisek",
  "Stephan Embacher",
  "Philipp Raimund",
  "Jan Hoerl",
  "Felix Hoffmann",
  "Stefan Kraft",
  "Johann Andre Forfang",
  "Marius Lindvik",
  "Manuel Fettner",
  "Naoki Nakamura",
  "Kristoffer Eriksen Sundal",
  "Valentin Foubert",
  "Maximilian Ortner",
  "Jonas Schuster",
  "Gregor Deschwanden",
  "Vladimir Zografski",
  "Tomofumi Naito",
  "Antti Aalto",
  "Kacper Tomasiak",
  "Niko Kytosaho",
  "Andreas Wellinger",
  "Halvor Egner Granerud",
  "Timi Zajc",
  "Karl Geiger",
  "Pius Paschke",
  "Isak Andreas Langmo",
  "Kamil Stoch",
  "Sandro Hauswirth",
  "Piotr Żyła",
  "Yukiya Sato",
  "Jason Colby",
  "Kevin Bickner",
  "Artti Aigro",
  "Benjamin Oestvold",
  "Maciej Kot",
  "Rok Oblak",
  "Tate Frantz",
  "Ilyja Mizernykh",
  "Paweł Wąsek",
  "Dawid Kubacki",
  "Clemens Aigner",
  "Hektor Kapustik",
  "Felix Trunz",
  "Simon Ammann",
  "Sakutaro Kobayashi",
  "Roman Koudelka",
  "Markus Mueller",
  "Alex Insam",
  "Danil Vassilyev",
  "Giovanni Bresadola",
  "Eetu Nousiainen",
  "Yevhen Marusiak",
  "Robin Pedersen",
  "Francesco Cecon",
  "Adrian Thon Gundersrud",
  "Vilho Palosaari",
  "Ziga Jancar",
  "Juri Kesseli",
  "Luca Roth",
  "Jarkko Maatta",
  "Aleksander Zniszczoł",
  "Ben Bayer",
  "Zak Mogel",
  "Yanick Wasser",
  "Andrew Urlaub",
  "Junshiro Kobayashi",
  "Killian Peier",
  "Klemens Joniak",
  "Vitaliy Kalinichenko",
  "Joergen Oliver Stroem",
  "Mackenzie Boyd-Clowes",
  "Keiichi Sato",
  "Soelve Jokerud Strand",
]

[[teams]]
  name = "Austria"
  members = [2, 5, 7, 9]
[[teams]]
  name = "Japan"
  members = [1, 3, 13, 20]
[[teams]]
  name = "Norway"
  members = [10, 11, 14, 25]
[[teams]]
  name = "Germany"
  members = [6, 8, 24, 27]
[[teams]]
  name = "Slovenia"
  members = [0, 4, 26, 39]
[[teams]]
  name = "Poland"
  members = [22, 30, 32, 38]
[[teams]]
  name = "Finland"
  members = [21, 23, 54, 59]
[[teams]]
  name = "Switzerland"
  members = [18, 31, 46, 47]
[[teams]]
  name = "USA"
  members = [34, 35, 40, 68]
[[teams]]
  name = "Rest of the world"
  members = [12, 15, 16, 17]
